import {voiceProfile} from '../src/domain/voice-profiles.js';
import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID,createHash} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {PostgresStore} from '../src/persistence-postgres.js';import {migrate} from '../scripts/migrate.mjs';import {scriptFixture} from './fixtures/script.js';import {HumanProductionApproval} from '../src/application/human-production-approval.js';import {AssetRepository,readAssets} from '../src/assets-postgres.js';import {AssetService} from '../src/application/asset-service.js';import {hash} from '../src/domain/research.js';import {seal,verify,rights,routeBeat,chooseProvider,makeAssetPlan,nativeScene,validateAsset,makeManifest} from '../src/domain/assets.js';import {voiceInput,wavQA,verifyProvider} from '../src/providers/asset-boundaries.js';
const base=process.env.TEST_DATABASE_URL,u=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let db,admin;before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);u.pathname='/'+name;db=new PostgresStore(u.href);await migrate(db.pool)});after(async()=>{await db.close();await admin.query('DROP DATABASE '+name);await admin.end()});
const now='2026-01-01T00:00:00.000Z',layer=[{kind:'text',label:'Synthetic',x:0.5,y:0.5}],beat=(type='CONTROLLED_DIAGRAM',classification='SCIENTIFIC_VISUALIZATION')=>({visual_beat_id:'b',visual_type:type,visual_classification:classification,claim_refs:['C'],generation_eligibility:'ELIGIBLE_AFTER_REVIEW',duration_target:2,concrete_visual_brief:'Synthetic controlled diagram only',motion_intent:'reveal',asset_requirement:{requirement_id:'r',evidence_references:[],source_requirement:'synthetic',rights_requirement:'review',disclosure_requirement:'illustrative'}});
function plan(b=beat()){const script={script_id:'s',output_hash:'sh',voiceover_text:'Synthetic text',language:'en',estimated_duration:2},pkg={business_id:'tenant',content_job_id:'j',production_package_id:'p',content_hash:'ph',timeline_segments:[b],target_platform_profile:{aspect_ratio:'9:16'},policy_snapshot_refs:{},audio_plan:{music_intent:'bed',sfx_requirements:'cue'},subtitle_strategy:'aligned',publication_hold:true,release_allowed:false};return makeAssetPlan({id:'plan',approval:{selected_script_id:'s',script_hash:'sh',selected_package_id:'p',package_hash:'ph',approval_id:'a',publication_hold:true,release_allowed:false},script,pkg,created_at:now})}
const reseal=x=>{const {content_hash,...b}=x;return seal(b)},evidence={authority:'human-license-review',reference:'synthetic-license',basis:'Synthetic test clearance only'};
function native(p=plan()){const r=p.requirements[0],data=nativeScene(p,r,layer);return seal({asset_id:'asset',version:1,business_id:p.business_id,content_job_id:p.content_job_id,plan_hash:p.content_hash,production_package_hash:p.production_package_hash,script_hash:p.script_hash,type:'NATIVE_SCENE_SPEC',beat_ids:[r.visual_beat_id],claim_refs:r.claim_refs,classification:r.classification,disclosure:r.disclosure,aspect_ratio:r.aspect_ratio,data,data_hash:hash(data),rights:rights('CLEARED',evidence),provenance:{origin:'synthetic',created_at:now,generated:false},qa:{status:'PASS'}})}
function wav(seconds=2,silence=false){const n=Math.round(seconds*8000),b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(silence?0:Math.round(Math.sin(i/8)*10000),44+i*2);return b}
async function fixture(){const f=await scriptFixture(db),r=await f.service.run(f.command);await new HumanProductionApproval(f.repository).record({business_id:f.b,content_job_id:f.j.id,script_id:r.scripts[0].script_id,package_id:r.packages[0].production_package_id,decisions:{script_creative_quality:'APPROVED',script_factual_safety:'APPROVED',production_package:'APPROVED_FOR_NEXT_PRODUCTION_STAGE'}});const repository=new AssetRepository(f.repository),p=await repository.plan(f.b,f.j.id);const candidate=await repository.voiceProfiles.candidate(f.b,{provider:'test',model:'test',provider_voice_reference:'explicit',voice_kind:'CATALOGUE',language:'en'});const approved=await repository.voiceProfiles.decision(f.b,candidate.voice_profile_id,{expected_hash:candidate.content_hash,decision:'APPROVED',actor:{type:'human',id:'synthetic-human'},reference:'synthetic-decision'});return {...f,repository,p,profile:approved,assets:new AssetService(repository)}}
const profile=voiceProfile({voice_profile_id:'synthetic',business_id:'tenant',provider:'test',model:'test',provider_voice_reference:'explicit',voice_kind:'CATALOGUE',version:1,language:'en',status:'APPROVED',approved_by:'synthetic-human',approved_at:now,approval_reference:'synthetic-decision',created_at:now,updated_at:now}),provider=p=>({describe:()=>({id:'test',model:'test',external:false,capabilities:['VoiceGenerationProvider']}),request:async i=>({bytes:wav(p.voice.expected_duration),format:'wav',request_id:'synthetic',usage:{characters:i.text.length},cost:null})});
const auth=p=>({max_calls:1,plan_hash:p.content_hash,requirement_id:'VOICE'});
test('P2C01 approved ProductionPackage becomes immutable AssetPlan',()=>{assert.equal(verify(plan()).production_package_id,'p')});
test('P2C02 every beat has a unique resolved requirement',()=>{const p=plan();assert.equal(p.requirements.length,1);assert.equal(p.requirements[0].visual_beat_id,'b')});
test('P2C03 router is business agnostic and capability based',()=>{assert.equal(chooseProvider({provider_class:'ImageGenerationProvider'},[{id:'any',quality:2,available:true,capabilities:['ImageGenerationProvider'],aspect_ratios:['9:16']}],{allowed_providers:['any'],min_quality:1,aspect_ratio:'9:16'}).id,'any')});
test('P2C04 native visual route produces validated scene layers',()=>{assert.equal(nativeScene(plan(),plan().requirements[0],layer).schema,'native-scene/1')});
test('P2C05 observed media routes to source rights verification',()=>{assert.equal(routeBeat(beat('OFFICIAL_SOURCE_MEDIA','OBSERVED')).resolution_type,'SOURCE_ASSET')});
test('P2C06 illustrative still routes to image boundary',()=>{assert.equal(routeBeat(beat('GENERATED_STILL','ILLUSTRATIVE')).provider_class,'ImageGenerationProvider')});
test('P2C07 illustrative video and image to video route explicitly',()=>{assert.equal(routeBeat(beat('TEXT_TO_VIDEO','ILLUSTRATIVE')).resolution_type,'GENERATED_VIDEO');assert.equal(routeBeat(beat('IMAGE_TO_VIDEO','ILLUSTRATIVE')).resolution_type,'IMAGE_TO_VIDEO')});
test('P2C08 replaceable video interface accepts a Runway compatible adapter',()=>{const p={describe:()=>({capabilities:['VideoGenerationProvider']}),request:async()=>({})};assert.equal(verifyProvider(p,'VideoGenerationProvider'),p)});
test('P2C09 no forced video provider for native content',()=>{assert.equal(routeBeat(beat()).provider_class,null)});
test('P2C10 factual classification overrides generative visual choice',()=>{assert.equal(routeBeat(beat('GENERATED_STILL','DATA_DERIVED')).resolution_type,'NATIVE_SCENE')});
test('P2C11 blocked claims cannot enter an asset plan',()=>{const p=plan();assert.throws(()=>makeAssetPlan({id:'x',approval:{selected_script_id:'s',script_hash:'sh',selected_package_id:'p',package_hash:'ph',publication_hold:true,release_allowed:false},script:{script_id:'s',output_hash:'sh'},pkg:{production_package_id:'p',content_hash:'ph',publication_hold:true,release_allowed:false,timeline_segments:[beat()]},blocked_claim_ids:['C']}),/BLOCKED_CLAIM_USE/)});
test('P2C12 classification cannot change on an artifact',()=>{const p=plan();assert.throws(()=>validateAsset(p,reseal({...native(p),classification:'OBSERVED'})),/ASSET_SCOPE_MISMATCH/)});
test('P2C13 disclosure must survive asset normalization',()=>{const p=plan();assert.throws(()=>validateAsset(p,reseal({...native(p),disclosure:'none'})),/ASSET_SCOPE_MISMATCH/)});
test('P2C14 rights statuses preserve explicit evidence gates',()=>{assert.equal(rights().status,'UNKNOWN');assert.equal(rights('REVIEW_REQUIRED').status,'REVIEW_REQUIRED');assert.equal(rights('CLEARED',evidence).status,'CLEARED')});
test('P2C15 public URL alone is not a rights clearance',()=>{assert.throws(()=>rights('CLEARED',{reference:'https://example.org'}),/RIGHTS_EVIDENCE_REQUIRED/)});
test('P2C16 voice abstraction has no fixed vendor',()=>{assert(verifyProvider(provider(plan()),'VoiceGenerationProvider'))});
test('P2C17 missing voice profile fails before call',()=>{assert.throws(()=>voiceInput(plan(),null,true),/VOICE_PROFILE_MISSING/)});
test('P2C18 missing voice credential fails before call',()=>{assert.throws(()=>voiceInput(plan(),profile,false),/VOICE_PROVIDER_CREDENTIAL_NOT_AVAILABLE/)});
test('P2C19 TTS request uses exact approved script text and hash',()=>{const p=plan(),i=voiceInput(p,profile,true);assert.equal(i.text,p.voice.text);assert.equal(i.text_hash,hash(i.text))});
test('P2C20 voice artifact persists in PostgreSQL after response capture',async()=>{const f=await fixture(),a=await f.assets.produce({plan:f.p,requirement:'VOICE',provider:provider(f.p),profile:f.profile,credentialPresent:true,authorization:auth(f.p)});const rows=await f.repository.records(f.p);assert.equal(rows.artifacts[0].asset_id,a.asset_id);assert.equal(rows.responses.length,1);assert.equal(a.qa.status,'PASS')});
test('P2C21 WAV QA rejects corrupt silent clipped and implausible audio',()=>{assert.equal(wavQA(wav(),2).status,'PASS');assert.throws(()=>wavQA(Buffer.alloc(0),2));assert.throws(()=>wavQA(wav(3,true),3),/AUDIO_LONG_SILENCE/);assert.throws(()=>wavQA(wav(),20),/VOICE_DURATION_INVALID/);const b=wav();for(let i=44;i<b.length;i+=2)b.writeInt16LE(32767,i);assert.throws(()=>wavQA(b,2),/AUDIO_CLIPPING/)});
test('P2C22 failed validation retains recoverable paid response without raw secrets',async()=>{const f=await fixture(),p=provider(f.p);p.request=async()=>({bytes:Buffer.from('bad'),format:'wav',authorization:'must-not-persist',reasoning:'private'});await assert.rejects(f.assets.produce({plan:f.p,requirement:'VOICE',provider:p,profile:f.profile,credentialPresent:true,authorization:auth(f.p)}),/AUDIO_DECODE_FAILED/);const rows=await f.repository.records(f.p);assert.equal(rows.responses.length,1);assert.equal(rows.artifacts.length,0);const raw=(await db.pool.query("SELECT payload FROM evidence_records WHERE job_id=$1 AND type='asset_response'",[f.j.id])).rows[0].payload;assert(!JSON.stringify(raw).includes('must-not-persist'));assert(!JSON.stringify(raw).includes('private'))});
test('P2C23 immutable attempts prevent automatic or repeated paid calls',async()=>{const f=await fixture(),p=provider(f.p);let count=0;const fn=p.request;p.request=async x=>{count++;return fn(x)};const cmd={plan:f.p,requirement:'VOICE',provider:p,profile:f.profile,credentialPresent:true,authorization:auth(f.p)};await f.assets.produce(cmd);await assert.rejects(f.assets.produce(cmd),/ASSET_ATTEMPT_ALREADY_EXISTS/);assert.equal(count,1);await assert.rejects(db.pool.query("UPDATE evidence_records SET payload='{}' WHERE job_id=$1 AND type='asset_attempt'",[f.j.id]),e=>e.code==='23514')});
test('P2C24 offline reprocessing changes neither attempts nor provider count',async()=>{const f=await fixture();await f.assets.produce({plan:f.p,requirement:'VOICE',provider:provider(f.p),profile:f.profile,credentialPresent:true,authorization:auth(f.p)});const row=(await db.pool.query("SELECT payload FROM evidence_records WHERE job_id=$1 AND type='asset_response'",[f.j.id])).rows[0].payload;const a=f.assets.reprocess(f.p,row);assert.equal(a.qa.status,'PASS');assert.equal((await f.repository.records(f.p)).attempts.length,1)});
test('P2C25 image boundary rejects mismatched provider capabilities',()=>{assert.throws(()=>verifyProvider(provider(plan()),'ImageGenerationProvider'),/PROVIDER_CAPABILITY_MISMATCH/)});
test('P2C26 unknown provider cost remains unknown with attempt dimensions',async()=>{const f=await fixture(),a=await f.assets.produce({plan:f.p,requirement:'VOICE',provider:provider(f.p),profile:f.profile,credentialPresent:true,authorization:auth(f.p)});assert.equal(a.provenance.cost,null);assert.equal(a.provenance.cost_status,'UNKNOWN');assert.equal((await f.repository.records(f.p)).attempts[0].business_id,f.b)});
test('P2C27 native repeated production reuses immutable artifact identity',async()=>{const f=await fixture(),a=await f.assets.native(f.p,f.p.requirements[0],layer),b=await f.assets.native(f.p,f.p.requirements[0],layer);assert.equal(a.asset_id,b.asset_id);assert.equal((await f.repository.records(f.p)).artifacts.length,1)});
test('P2C28 visual asset validation rejects wrong dimensions and nonexistent beat',()=>{const p=plan();assert.throws(()=>validateAsset(p,reseal({...native(p),aspect_ratio:'16:9'})));assert.throws(()=>validateAsset(p,reseal({...native(p),beat_ids:['missing']})))});
test('P2C29 content hash detects artifact or version tampering',()=>{assert.throws(()=>verify({...native(),version:2}),/ASSET_HASH_MISMATCH/)});
test('P2C30 manifest preserves all immutable input identities',()=>{const p=plan(),m=makeManifest({id:'m',plan:p,assets:[native(p)],attempts:[],created_at:now});assert.equal(m.script_hash,p.script_hash);assert.equal(m.production_package_hash,p.production_package_hash);verify(m)});
test('P2C31 missing voice music and timing keep manifest partial',()=>{const p=plan(),m=makeManifest({id:'m',plan:p,assets:[native(p)],attempts:[],created_at:now});assert.equal(m.status,'ASSETS_PARTIAL');assert(m.unresolved.includes('VOICE'));assert(m.unresolved.includes('MUSIC'));assert.equal(m.renderer_ready,false)});
test('P2C32 ready requires cleared visuals and validated voice with no other required inputs',()=>{const p=reseal({...plan(),music:{required:false},sfx:{required:false},subtitles:{required:false}}),a=native(p),data={format:'wav',bytes_base64:wav().toString('base64')},v=reseal({...a,asset_id:'voice',type:'VOICE',beat_ids:[],text_hash:p.voice.text_hash,data,data_hash:hash(data),qa:wavQA(wav(),2)});const m=makeManifest({id:'m',plan:p,assets:[a,v],attempts:[],created_at:now});assert.equal(m.status,'ASSETS_READY');assert.equal(m.human_review_required,true)});
test('P2C33 assets survive store restart',async()=>{const f=await fixture();await f.assets.native(f.p,f.p.requirements[0],layer);const other=new PostgresStore(u.href);try{assert.equal((await other.getJob(f.j.id,f.b)).assetProduction.artifacts.length,1)}finally{await other.close()}});
test('P2C34 PostgreSQL plan is idempotent and centrally enters assets pending',async()=>{const f=await fixture();assert.equal((await f.repository.plan(f.b,f.j.id)).plan_id,f.p.plan_id);assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'ASSETS_PENDING')});
test('P2C35 asset reads and writes enforce tenant scope',async()=>{const f=await fixture();assert.equal((await readAssets(db.pool,'other',f.j.id)).assetProduction.plans.length,0);assert.throws(()=>validateAsset(plan(),reseal({...native(),business_id:'other'})),/ASSET_TENANT_MISMATCH/)});
test('P2C36 Job Detail contains persisted asset fields and UI uses textContent',async()=>{const f=await fixture();assert.equal((await db.getJob(f.j.id,f.b)).assetProduction.plans.length,1);const ui=await readFile('public/app.js','utf8');assert(ui.includes('renderAssets(d.assetProduction)'));assert(ui.includes("['VOICE'"));assert(ui.includes('pre.textContent=JSON.stringify(data'));assert((await readFile('public/index.html','utf8')).includes('id="assets"'))});
test('P2C37 publication HOLD survives manifest construction',()=>{assert.equal(makeManifest({id:'m',plan:plan(),assets:[],attempts:[],created_at:now}).publication_hold,true)});
test('P2C38 no release or assets ready bypass',async()=>{const f=await fixture(),d=await db.getJob(f.j.id,f.b);await assert.rejects(db.transition(f.j.id,d.job.state_version,'ASSETS_READY',{business_id:f.b,asset_plan_id:f.p.plan_id}),/PERSISTED_ASSET_MANIFEST_REQUIRED/);await assert.rejects(db.transition(f.j.id,d.job.state_version,'RELEASE_APPROVED',{business_id:f.b}))});
test('P2C39 renderer reference hashes unchanged',async()=>{for(const line of (await readFile('docs/SOURCE_HASHES.tsv','utf8')).trim().split(/\r?\n/).slice(1)){const [p,h]=line.split('\t');assert.equal(createHash('sha256').update(await readFile(new URL('../../arktrov-remotion/'+p,import.meta.url))).digest('hex'),h)}});
test('P2C40 Make remains untouched by asset production',async()=>{const {execFileSync}=await import('node:child_process');const changes=execFileSync('git',['diff','--name-only','v0.3.0-script-production','--','legacy'],{encoding:'utf8'});assert.equal(changes.trim(),'')});

import {deflateSync} from 'node:zlib';import {pngQA} from '../src/providers/asset-boundaries.js';
function png(){const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);let crc=0xffffffff;for(const v of b.subarray(4,-4)){crc^=v;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}b.writeUInt32BE((crc^0xffffffff)>>>0,b.length-4);return b};const h=Buffer.alloc(13);h.writeUInt32BE(9);h.writeUInt32BE(16,4);h[8]=8;h[9]=2;return {format:'png',bytes_base64:Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.alloc((9*3+1)*16))),chunk('IEND',Buffer.alloc(0))]).toString('base64')}}
test('P2CX01 real PNG decode validates dimensions and rejects corrupt bytes',()=>{assert.equal(pngQA(png()).aspect_ratio,'9:16');assert.throws(()=>pngQA({bytes_base64:Buffer.from('bad').toString('base64')}));const bad=png();const b=Buffer.from(bad.bytes_base64,'base64');b[20]^=1;assert.throws(()=>pngQA({...bad,bytes_base64:b.toString('base64')}))});
test('P2CX02 source and generated adapters recover actual PNG output offline',()=>{const service=new AssetService(null);for(const beatType of ['OFFICIAL_SOURCE_MEDIA','GENERATED_STILL']){const p=plan(beat(beatType,beatType==='OFFICIAL_SOURCE_MEDIA'?'OBSERVED':'ILLUSTRATIVE'));const response=seal({attempt_id:'a',plan_hash:p.content_hash,requirement_id:'r',data:png(),metadata:{provider:'synthetic',model:'synthetic',external_calls:0},source_reference:'synthetic-source',received_at:now});const a=service.reprocess(p,response,{decoder:pngQA,rightsEvidence:evidence});assert.equal(a.qa.status,'PASS');assert.equal(a.rights.status,'CLEARED');assert.equal(a.provenance.generated,beatType==='GENERATED_STILL')}});
test('P2CX03 unsupported video decoder cannot produce accepted asset',()=>{const p=plan(beat('TEXT_TO_VIDEO','ILLUSTRATIVE')),response=seal({attempt_id:'a',plan_hash:p.content_hash,requirement_id:'r',data:{bytes_base64:'AA=='},metadata:{},received_at:now});assert.throws(()=>new AssetService(null).reprocess(p,response),/VISUAL_DECODER_REQUIRED/)});
test('P2CX04 provided transcript mismatch fails voice QA without rewriting history',()=>{const p=plan(),response=seal({attempt_id:'a',plan_hash:p.content_hash,requirement_id:'VOICE',data:{format:'wav',bytes_base64:wav().toString('base64')},transcript:'Changed narration',metadata:{},received_at:now});assert.throws(()=>new AssetService(null).reprocess(p,response),/VOICE_TRANSCRIPT_MISMATCH/)});

import {spawn} from 'node:child_process';import {once} from 'node:events';import {chromium} from 'playwright';
test('P2CX05 actual Assets API UI and reserved evidence gate',async()=>{const f=await fixture();await f.assets.native(f.p,f.p.requirements[0],layer);await f.repository.manifest(f.p);const child=spawn(process.execPath,['src/server/index.js'],{env:{...process.env,DATABASE_URL:u.href,BUSINESS_ID:f.b,PORT:'0'},stdio:['ignore','pipe','pipe']});let browser,log='';try{const address=await new Promise((resolve,reject)=>{child.stdout.on('data',d=>{log+=d;for(const line of log.split('\n')){try{const e=JSON.parse(line);if(e.event==='ready')resolve('http://127.0.0.1:'+e.port)}catch{}}});child.on('exit',()=>reject(Error('APP_EXIT')))});const denied=await fetch(address+'/api/jobs/'+f.j.id+'/evidence',{method:'POST',headers:{'content-type':'application/json',origin:address},body:JSON.stringify({evidence_type:'asset_artifact',reference:'forged',payload:{}})});assert.equal(denied.status,403);const response=await fetch(address+'/api/jobs/'+f.j.id);assert.equal(response.status,200);assert.equal((await response.json()).assetProduction.artifacts.length,1);assert.equal((await fetch(address+'/api/jobs/'+f.j.id,{headers:{'x-business-id':'other'}})).status,403);browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();await page.goto(address);await page.locator('#jobs button').first().click();await page.locator('#assets h4').first().waitFor();const text=await page.locator('#assets').innerText();for(const expected of ['VOICE','VISUAL ASSETS','NATIVE_SCENE','REVIEW_REQUIRED','ASSETS_PARTIAL'])assert(text.includes(expected));}finally{await browser?.close();child.kill();await once(child,'exit')}});

test('P2CX06 observed classification cannot be routed to invented native imagery',()=>{assert.equal(routeBeat(beat('MOTION_GRAPHICS','OBSERVED')).resolution_type,'SOURCE_ASSET')});
test('P2CX07 forged successful voice QA cannot admit corrupted audio',()=>{const p=plan(),data={format:'wav',bytes_base64:'AAAA'},a=reseal({...native(p),type:'VOICE',text_hash:p.voice.text_hash,data,data_hash:hash(data),qa:{status:'PASS'}});assert.throws(()=>validateAsset(p,a),/AUDIO_DECODE_FAILED/)});
test('P2CX08 cost ceiling does not treat unknown cost as zero',()=>{assert.throws(()=>chooseProvider({provider_class:'ImageGenerationProvider'},[{id:'x',available:true,quality:1,capabilities:['ImageGenerationProvider']}],{allowed_providers:['x'],min_quality:1,max_cost:1}),/PROVIDER_NOT_AVAILABLE/)});

test('P2CX09 automatic voice routing reports missing authoritative profile before registry selection',async()=>{await assert.rejects(new AssetService(null).routeAndProduce({plan:plan(),requirement:'VOICE',registry:[],policy:{allowed_providers:[]},credentialPresent:false}),/VOICE_PROFILE_MISSING/)});


function voiceOnlyPlan(){return reseal({...plan(),requirements:[],music:{required:false},sfx:{required:false},subtitles:{required:false}})}
function voiceAsset(p,status='REVIEW_REQUIRED',slot='VOICE',id='voice'){
 const v=p.voice_requirements.find(v=>v.requirement_id===slot),data={format:'wav',bytes_base64:wav().toString('base64')};
 return seal({asset_id:id,type:'VOICE',business_id:p.business_id,content_job_id:p.content_job_id,plan_hash:p.content_hash,production_package_hash:p.production_package_hash,script_hash:p.script_hash,text_hash:v.text_hash,voice_requirement_id:slot,data,data_hash:hash(data),qa:wavQA(wav(),v.expected_duration),rights:rights(status,status==='CLEARED'?evidence:null),provenance:{origin:'synthetic',created_at:now}});
}
const voiceManifest=(p,assets)=>makeManifest({id:'m',plan:p,assets,attempts:[],created_at:now});
test('VM01 technically valid voice resolves synthesis while every uncleared rights status blocks readiness',()=>{
 const p=voiceOnlyPlan();for(const status of ['UNKNOWN','REVIEW_REQUIRED','RESTRICTED','NOT_ALLOWED']){
 const a=voiceAsset(p,status),snapshot=JSON.stringify(a),m=voiceManifest(p,[a]);assert.equal(m.voice_asset_id,a.asset_id);assert.equal(m.voice_assets[0].asset_id,a.asset_id);assert.deepEqual(m.unresolved,['VOICE_RIGHTS:VOICE']);assert.equal(m.voice_rights[0].rights_status,status);assert.equal(m.status,'ASSETS_PARTIAL');assert.equal(m.renderer_ready,false);assert.equal(m.publication_hold,true);assert.equal(m.release_allowed,false);assert.equal(m.human_review_required,true);assert.equal(JSON.stringify(a),snapshot);
 }});
test('VM02 cleared voice readiness still requires explicit rights evidence and human review',()=>{
 const p=voiceOnlyPlan(),a=voiceAsset(p,'CLEARED'),m=voiceManifest(p,[a]);assert.deepEqual(m.unresolved,[]);assert.equal(m.status,'ASSETS_READY');assert.equal(m.human_review_required,true);assert.equal(m.release_allowed,false);assert.throws(()=>voiceManifest(p,[reseal({...a,rights:{status:'CLEARED',evidence:null}})]),/RIGHTS_EVIDENCE_REQUIRED/);
});
test('VM03 absent failed mismatched or corrupt voice cannot resolve synthesis',()=>{
 const p=voiceOnlyPlan(),a=voiceAsset(p);assert.deepEqual(voiceManifest(p,[]).unresolved,['VOICE']);
 for(const [change,error] of [[{qa:{...a.qa,status:'FAIL'}},/VOICE_NOT_VALIDATED/],[{text_hash:'wrong'},/VOICE_NOT_VALIDATED/],[{business_id:'other'},/ASSET_TENANT_MISMATCH/],[{qa:{...a.qa,file_sha256:'wrong'}},/VOICE_QA_MISMATCH/]])assert.throws(()=>voiceManifest(p,[reseal({...a,...change})]),error);
 const data={format:'wav',bytes_base64:'AAAA'};assert.throws(()=>voiceManifest(p,[reseal({...a,data,data_hash:hash(data)})]));
});
test('VM04 multiple voice slots separate missing audio from pending rights',()=>{
 const base=voiceOnlyPlan(),v=base.voice_requirements[0],p=reseal({...base,voice_requirements:[{...v,requirement_id:'speaker-a'},{...v,requirement_id:'speaker-b'}]}),a=voiceAsset(p,'REVIEW_REQUIRED','speaker-a');
 const m=voiceManifest(p,[a]);assert.deepEqual(m.unresolved,['speaker-b','VOICE_RIGHTS:speaker-a']);assert.deepEqual(m.voice_assets,[{requirement_id:'speaker-a',asset_id:'voice'},{requirement_id:'speaker-b',asset_id:null}]);
 const complete=voiceManifest(p,[a,voiceAsset(p,'CLEARED','speaker-b','b')]);assert.deepEqual(complete.unresolved,['VOICE_RIGHTS:speaker-a']);assert.equal(complete.renderer_ready,false);
});
test('VM05 cleared matching voice is selected consistently before a pending alternative',()=>{
 const p=voiceOnlyPlan(),pending=voiceAsset(p),cleared=voiceAsset(p,'CLEARED','VOICE','cleared');for(const assets of [[pending,cleared],[cleared,pending]]){const m=voiceManifest(p,assets);assert.equal(m.voice_asset_id,'cleared');assert.equal(m.voice_assets[0].asset_id,'cleared');assert.deepEqual(m.unresolved,[])}
});
test('VM06 legacy voice plan resolves audio without rewriting original plan or rights',()=>{
 const current=voiceOnlyPlan(),{voice_requirements,voice_required,content_hash,...body}=current,p=seal(body),a=reseal({...voiceAsset(current),plan_hash:p.content_hash}),snapshot=JSON.stringify(p),m=voiceManifest(p,[a]);assert.equal(m.voice_asset_id,a.asset_id);assert.deepEqual(m.unresolved,['VOICE_RIGHTS:VOICE']);assert.equal(m.voice_rights[0].asset_id,a.asset_id);assert.equal(JSON.stringify(p),snapshot);assert.equal(a.rights.status,'REVIEW_REQUIRED');
});
