import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
import {PostgresStore} from '../src/persistence-postgres.js';import {migrate} from '../scripts/migrate.mjs';import {scriptFixture,proposalFor} from './fixtures/script.js';import {hash} from '../src/domain/research.js';import {proposeRealization,reviseRealization,validateRealization} from '../src/domain/claim-realization.js';import {resolveClaimUsage} from '../src/domain/claim-usage.js';import {validateScriptProposal,buildDrafts,segmentDuration} from '../src/domain/script-production.js';import {HumanScriptReview} from '../src/application/human-script-review.js';
import {appendRealization,loadRealizations} from '../src/claim-realizations-postgres.js';
const base=process.env.TEST_DATABASE_URL,u=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let db,admin;if(!['127.0.0.1','localhost'].includes(u.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);u.pathname='/'+name;db=new PostgresStore(u.href);await migrate(db.pool)});after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
const signed=r=>{const {content_hash,...b}=r;return {...b,content_hash:hash(b)}};
async function fixture(){const f=await scriptFixture(db),p=await proposalFor(f),input={...p.input,version:'script-production-input/2.2',realization_style_profile:'synthetic-spoken/1',claim_realizations:[]},proposal=p.proposal;for(const s of proposal.scripts)s.visual_beats=s.segments.map((seg,n)=>({visual_beat_id:'b'+n,narration_segment_id:seg.segment_id,duration_target:segmentDuration(seg.text,input.profiles[s.format]),claim_ids:seg.claim_id?[seg.claim_id]:[],visual_type:seg.visual_type,visual_classification:seg.visual_classification,visual_intent:'Explain linked test statement',concrete_visual_brief:'Reveal a controlled panel with the admitted label and preserve its limitation.',motion_intent:'Panel reveal',transition_intent:'Cut',factual_sensitivity:'Preserve limitation',source_requirement:'Linked evidence',rights_requirement:'Review required',disclosure_requirement:'Label illustration',generation_eligibility:'NOT_ELIGIBLE'}));const proposed=proposeRealization(input,{realization_id:randomUUID(),claim_id:'CLAIM-001',realization_text:'A synthetic alternative explicitly approved only in this test with its limitation intact.',created_at:new Date().toISOString()}),approved=reviseRealization(proposed,{status:'APPROVED',approved_by:'synthetic-human',approved_at:new Date().toISOString(),created_at:new Date().toISOString(),qualifier_semantics_preserved:true});return {...f,input,proposal,proposed,approved}}
const alt=f=>({...f.proposal.scripts[0].segments[1],text:f.proposed.realization_text});
test('REAL01 canonical text remains accepted without a catalog',async()=>{const f=await fixture();assert.equal(validateScriptProposal(f.input,f.proposal).status,'PASS')});
test('REAL02 exact human-approved variant accepted and traced in draft',async()=>{const f=await fixture();f.input.claim_realizations=[f.approved];f.proposal.scripts[0].segments[1]=alt(f);f.proposal.scripts[0].visual_beats[1].duration_target=segmentDuration(alt(f).text,f.input.profiles.SHORT);const d=buildDrafts(f.input,f.proposal,{script_ids:[randomUUID()],version:1,lineage_id:randomUUID(),created_at:new Date().toISOString()},{});assert.equal(d[0].claim_usage[0].usage_type,'QUALIFIED');assert.equal(d[0].claim_usage[0].approved_realization_reference.content_hash,f.approved.content_hash);assert.equal(d[0].validation.status,'PASS')});
test('REAL03 proposed realization rejected',async()=>{const f=await fixture();f.input.claim_realizations=[f.proposed];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/APPROVED_REALIZATION_REQUIRED/)});
test('REAL04 retired realization rejected',async()=>{const f=await fixture();f.input.claim_realizations=[reviseRealization(f.approved,{status:'RETIRED',created_at:new Date().toISOString()})];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/APPROVED_REALIZATION_REQUIRED/)});
test('REAL05 approval requires explicit qualifier semantics attestation',async()=>{const f=await fixture();assert.throws(()=>reviseRealization(f.proposed,{status:'APPROVED',approved_by:'human',approved_at:new Date().toISOString(),created_at:new Date().toISOString(),qualifier_semantics_preserved:false}),/REALIZATION_APPROVAL_REQUIRED/)});
test('REAL06 missing qualifier references rejected despite approval flag',async()=>{const f=await fixture();f.input.claim_realizations=[signed({...f.approved,required_qualifier_refs:[]})];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/REALIZATION_QUALIFIER_MISMATCH/)});
test('REAL07 blocked claim cannot be approved into factual use',async()=>{const f=await fixture();f.input.claim_realizations=[signed({...f.approved,claim_id:'BLOCKED'})];assert.throws(()=>resolveClaimUsage(f.input,{...alt(f),claim_id:'BLOCKED'}),/BLOCKED_CLAIM_USE/)});
test('REAL08 context restrictions and allowed mode survive alternative wording',async()=>{const f=await fixture(),p=proposeRealization(f.input,{realization_id:randomUUID(),claim_id:'CONTEXT',realization_text:'Limitation: Synthetic approved contextual wording.',created_at:new Date().toISOString()}),a=reviseRealization(p,{status:'APPROVED',approved_by:'human',approved_at:new Date().toISOString(),created_at:new Date().toISOString(),qualifier_semantics_preserved:true});f.input.claim_realizations=[a];assert.equal(resolveClaimUsage(f.input,{...alt(f),claim_id:'CONTEXT',text:a.realization_text}),'CONTEXT_ONLY');const bad=signed({...a,realization_text:'A factual assertion without context.'});f.input.claim_realizations=[bad];assert.throws(()=>resolveClaimUsage(f.input,{...alt(f),claim_id:'CONTEXT',text:bad.realization_text}),/CONTEXT_RESTRICTION_FAILED/)});
test('REAL09 changed text invalidates content hash',async()=>{const f=await fixture();assert.throws(()=>validateRealization({...f.approved,realization_text:'Changed'}),/REALIZATION_HASH_MISMATCH/)});
test('REAL10 cross-tenant catalog entry rejected',async()=>{const f=await fixture();f.input.claim_realizations=[signed({...f.approved,business_id:'another'})];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/REALIZATION_SCOPE_MISMATCH/)});
test('REAL11 altered source claim or scope cannot reuse approval',async()=>{const f=await fixture();f.input.claim_realizations=[signed({...f.approved,source_claim_hash:hash('other')})];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/REALIZATION_CLAIM_MISMATCH/);f.input.claim_realizations=[signed({...f.approved,fact_guard_scope_hash:hash('other')})];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/REALIZATION_SCOPE_MISMATCH/)});
test('REAL12 arbitrary similar paraphrase still rejected',async()=>{const f=await fixture();f.input.claim_realizations=[f.approved];assert.throws(()=>resolveClaimUsage(f.input,{...alt(f),text:alt(f).text+' Clearly proven.'}),/APPROVED_REALIZATION_REQUIRED/)});
test('REAL13 PostgreSQL versions append immutably and retirement replaces eligibility',async()=>{const f=await fixture();await appendRealization(f.repository,f.j.id,f.proposed);await appendRealization(f.repository,f.j.id,f.approved);await appendRealization(f.repository,f.j.id,f.approved);let rows=await loadRealizations(db.pool,f.b,f.j.id);assert.equal(rows.length,1);assert.equal(rows[0].status,'APPROVED');const retired=reviseRealization(f.approved,{status:'RETIRED',created_at:new Date().toISOString()});await appendRealization(f.repository,f.j.id,retired);rows=await loadRealizations(db.pool,f.b,f.j.id);assert.equal(rows[0].status,'RETIRED');await assert.rejects(db.pool.query("UPDATE evidence_records SET payload='{}' WHERE business_id=$1 AND type='claim_realization'",[f.b]),e=>e.code==='23514');await assert.rejects(appendRealization(f.repository,f.j.id,signed({...f.proposed,realization_text:'Changed'})),/IMMUTABLE_REALIZATION_VERSION/);assert.deepEqual(await loadRealizations(db.pool,'other',f.j.id),[])});
test('REAL14 old processing ignores catalogs and historical scripts stay unchanged',async()=>{const f=await fixture(),r=await f.service.run(f.command);await appendRealization(f.repository,f.j.id,f.proposed);const d=await db.getJob(f.j.id,f.b);assert.deepEqual(d.scripts,r.scripts);assert.deepEqual(d.productionPackages,r.packages);f.input.version='script-production-input/2.1';f.input.claim_realizations=[f.approved];assert.throws(()=>resolveClaimUsage(f.input,alt(f)),/QUALIFIER_OR_CLAIM_NOT_PRESERVED/)});

test('REAL15 retirement after input preparation blocks state admission before provider',async()=>{const f=await fixture(),v1=await f.service.run(f.command),review=await new HumanScriptReview(f.repository).record({business_id:f.b,content_job_id:f.j.id,script_id:v1.scripts[0].script_id,package_id:v1.packages[0].production_package_id,feedback:'Test explicit revision.'});await appendRealization(f.repository,f.j.id,f.proposed);await appendRealization(f.repository,f.j.id,f.approved);Object.assign(f.configuration,{contract_version:'script-production-input/2.2',realization_style_profile:'synthetic-spoken/1'});const cmd={...f.command,idempotency_key:'next',previous_execution_id:v1.execution.id,revision_directive_id:review.id},input=await f.service.prepare(cmd);assert.equal(input.claim_realizations[0].status,'APPROVED');await appendRealization(f.repository,f.j.id,reviseRealization(f.approved,{status:'RETIRED',created_at:new Date().toISOString()}));await assert.rejects(f.repository.begin(cmd,input),/STALE_REALIZATION_CATALOG/);assert.equal((await db.getJob(f.j.id,f.b)).scriptExecutions.length,1)});


test('REAL16 selected four approvals preserve eight proposals and canonical source in PostgreSQL',async()=>{const f=await fixture(),before=hash(f.input.approved_claims),records=[];for(let n=0;n<12;n++){const p=proposeRealization(f.input,{realization_id:randomUUID(),claim_id:'CLAIM-001',realization_text:'Synthetic reviewed variant '+n+' with its limitation intact.',created_at:new Date().toISOString()});await appendRealization(f.repository,f.j.id,p);if(n<4)await appendRealization(f.repository,f.j.id,reviseRealization(p,{status:'APPROVED',approved_by:'human',approved_at:new Date().toISOString(),created_at:new Date().toISOString(),qualifier_semantics_preserved:true}));records.push(p)}const rows=await loadRealizations(db.pool,f.b,f.j.id);assert.equal(rows.filter(r=>r.status==='APPROVED').length,4);assert.equal(rows.filter(r=>r.status==='PROPOSED').length,8);f.input.claim_realizations=rows;for(const r of rows){const seg={...alt(f),text:r.realization_text};assert.deepEqual(r.required_qualifier_refs,records.find(p=>p.realization_id===r.realization_id).required_qualifier_refs);if(r.status==='APPROVED')assert.equal(resolveClaimUsage(f.input,seg),'QUALIFIED');else assert.throws(()=>resolveClaimUsage(f.input,seg),/APPROVED_REALIZATION_REQUIRED/)}assert.equal(hash(f.input.approved_claims),before)});

test('REAL17 realization profile supplies explicit exact approved language without changing old prompt',async()=>{const {arktrovScriptRealizationConfiguration:c,arktrovScriptResolvedConfiguration:old}=await import('../src/config/script-production.js');assert.equal(c.contract_version,'script-production-input/2.2');assert.equal(c.realization_style_profile,'arktrov-short-spoken/1.0');assert.match(c.prompt,/exact APPROVED claim_realizations/);assert.match(c.prompt,/PROPOSED and RETIRED variants are forbidden/);assert.match(c.prompt,/do not force all preferred claims/);assert.equal(old.contract_version,'script-production-input/2.1');assert.notEqual(c.prompt_version,old.prompt_version)});
