import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
import {PostgresStore} from '../src/persistence-postgres.js';import {migrate} from '../scripts/migrate.mjs';
import {scriptFixture,proposalFor} from './fixtures/script.js';
import {HumanScriptReview} from '../src/application/human-script-review.js';
import {validateScriptProposal,segmentDuration} from '../src/domain/script-production.js';
import {ScriptService} from '../src/application/script-service.js';import {LocalScriptProvider} from '../src/providers/local-script.js';
import {scriptSchemaV2} from '../src/providers/openai-script.js';import {hash} from '../src/domain/research.js';
const base=process.env.TEST_DATABASE_URL,url=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
if(!['localhost','127.0.0.1'].includes(url.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});
after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
async function setup(){const f=await scriptFixture(db),v1=await f.service.run(f.command),review=new HumanScriptReview(f.repository),cmd={business_id:f.b,content_job_id:f.j.id,script_id:v1.scripts[0].script_id,package_id:v1.packages[0].production_package_id,feedback:'Human review: factual safety approved; improve curiosity, pacing and concrete shot planning.'},directive=await review.record(cmd);f.configuration.contract_version='script-production-input/2.0';const command={...f.command,idempotency_key:'revision-2',previous_execution_id:v1.execution.id,revision_directive_id:directive.id};const input=await f.service.prepare(command);const p=await proposalFor({...f,service:{prepare:async()=>input}});for(const s of p.proposal.scripts)s.visual_beats=s.segments.flatMap((seg,n)=>{const d=segmentDuration(seg.text,input.profiles[s.format]),a=Math.floor(d*500)/1000;return [a,d-a].map((seconds,k)=>({visual_beat_id:'beat-'+n+'-'+k,narration_segment_id:seg.segment_id,duration_target:seconds,claim_ids:seg.claim_id?[seg.claim_id]:[],visual_type:seg.visual_type,visual_classification:seg.visual_classification,visual_intent:'Explain the linked admitted statement without additional facts',concrete_visual_brief:'Reveal two outlined panels with the scoped statement label; highlight the selected panel without inventing observational imagery.',motion_intent:'Slow controlled panel reveal',transition_intent:'Match cut to next panel',factual_sensitivity:'Keep scoped qualifiers and context limitations visible',source_requirement:'Use the linked evidence only; verify any source image',rights_requirement:'Rights review required; no reuse permission inferred',disclosure_requirement:'Label non-observational diagrams as visualization',generation_eligibility:'NOT_ELIGIBLE'}))});return {...f,v1,review,cmd,directive,command,input,proposal:p.proposal}}
const mutation=async(fn,error)=>{const f=await setup();fn(f.proposal.scripts[0].visual_beats,f);assert.throws(()=>validateScriptProposal(f.input,f.proposal),error)};

import {HumanProductionApproval} from '../src/application/human-production-approval.js';

const decisions={script_creative_quality:'APPROVED',script_factual_safety:'APPROVED',production_package:'APPROVED_FOR_NEXT_PRODUCTION_STAGE'};
async function ready(){const f=await scriptFixture(db),r=await f.service.run(f.command);return {...f,r,approval:new HumanProductionApproval(f.repository),request:{business_id:f.b,content_job_id:f.j.id,script_id:r.scripts[0].script_id,package_id:r.packages[0].production_package_id,decisions}}}
test('HPA01 immutable human approval selects artifacts without mutating their state or content',async()=>{const f=await ready(),before=await db.getJob(f.j.id,f.b),a=await f.approval.record(f.request),after=await db.getJob(f.j.id,f.b);assert.equal(a.payload.actor,'human');assert.equal(a.content_hash,hash(a.payload));assert.equal(after.selectedProduction.selected_script_id,f.request.script_id);assert.equal(after.selectedProduction.selected_package_id,f.request.package_id);assert.deepEqual(after.scripts,before.scripts);assert.deepEqual(after.productionPackages,before.productionPackages);assert.deepEqual(after.job,before.job);assert.equal(after.selectedProduction.release_allowed,false);assert.equal(after.selectedProduction.publication_hold,true);await assert.rejects(db.pool.query("UPDATE evidence_records SET payload='{}' WHERE id=$1",[a.id]),e=>e.code==='23514')});
test('HPA02 repeated same approval is idempotent',async()=>{const f=await ready(),a=await f.approval.record(f.request),b=await f.approval.record(f.request);assert.equal(a.id,b.id)});
test('HPA03 cross tenant approval cannot select foreign artifacts',async()=>{const f=await ready();await assert.rejects(f.approval.record({...f.request,business_id:'wrong-tenant'}));assert.equal((await db.getJob(f.j.id,f.b)).selectedProduction,null)});
test('HPA04 human approval cannot clear publication hold or bypass release',async()=>{const f=await ready();await assert.rejects(f.approval.record({...f.request,decisions:{...decisions,publication:'APPROVED'}}),/EXPLICIT_HUMAN_APPROVAL_REQUIRED/);await f.approval.record(f.request);const d=await db.getJob(f.j.id,f.b);await assert.rejects(db.transition(f.j.id,d.job.state_version,'RELEASE_APPROVED',{business_id:f.b}));assert.equal(d.selectedProduction.publication_hold,true)});
test('HPA05 mismatched package cannot be approved',async()=>{const f=await ready(),other=await ready();await assert.rejects(f.approval.record({...f.request,package_id:other.request.package_id}),/APPROVAL_ARTIFACT_NOT_FOUND/)});
