import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import pg from 'pg';import {spawn} from 'node:child_process';import {once} from 'node:events';import {chromium} from 'playwright';
import {hash} from '../src/domain/research.js';import {seal,makeManifest} from '../src/domain/assets.js';import {musicRequirement} from '../src/domain/composition-music.js';import {musicAsset,musicCompatibility,musicPreferences,recommendMusic,audioMixPlan,applyMusicSelection,latestMusic} from '../src/domain/music.js';import {wavQA} from '../src/domain/asset-qa.js';import {PostgresStore} from '../src/persistence-postgres.js';import {migrate} from '../scripts/migrate.mjs';import {BusinessMusicRepository} from '../src/music-postgres.js';import {MusicSourceProvider,verifyMusicSourceProvider} from '../src/providers/music-source.js';import {scriptFixture} from './fixtures/script.js';import {HumanProductionApproval} from '../src/application/human-production-approval.js';import {AssetRepository} from '../src/assets-postgres.js';import {MusicSelectionService} from '../src/application/music-selection.js';
const now='2026-01-01T00:00:00.000Z';
function wav(seconds=2){const count=Math.round(seconds*8000),b=Buffer.alloc(44+count*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)b.writeInt16LE(Math.round(Math.sin(i/8)*9000),44+i*2);return b}
const license={license_type:'royalty-free',license_reference:'synthetic-license',license_evidence:{authority:'synthetic-human',reference:'synthetic-terms',basis:'Synthetic test license only',terms_hash:hash('terms')},commercial_use_allowed:true,social_media_use_allowed:true,platforms:['youtube','instagram'],territories:['DE'],expires_at:null,credit_required:true,credit_text:'Synthetic Artist',loop_allowed:true};
function track(more={}){const bytes=wav(),data={format:'wav',bytes_base64:bytes.toString('base64')},qa=wavQA(bytes,2);return musicAsset({music_asset_id:randomUUID(),business_id:'tenant',version:1,title:'Synthetic bed',creator:'Synthetic Artist',provider:'arbitrary-library',provider_asset_reference:'synthetic-track',source_reference:'synthetic-source',provenance:{origin:'CATALOG'},license,status:'APPROVED',rights_status:'CLEARED',approval:{actor:'human',reference:'synthetic-listening'},rights_decision:{actor:'human',reference:'synthetic-license-review'},suitability:{},audio:{format:'wav',duration:qa.duration,content_hash:qa.file_sha256,qa},data,created_at:now,...more})}
const context=(more={})=>({business_id:'tenant',commercial:true,social_media:true,platforms:['youtube'],territory:'DE',duration:5,narration_presence:true,use_case:'documentary',as_of:now,...more});
const prefs=(more={})=>musicPreferences({business_id:'tenant',created_at:now,automatic_recommendation_enabled:true,...more});
const revise=(a,more)=>{const {content_hash,...x}=a;return musicAsset({...x,...more})};
function plan(voice=false,music=false){return seal({plan_id:'p',business_id:'tenant',content_job_id:'j',script_id:'s',script_hash:'sh',production_package_id:'pkg',production_package_hash:'ph',voice_required:voice,voice_requirements:voice?[{requirement_id:'VOICE',text:'Synthetic',text_hash:hash('Synthetic'),expected_duration:2}]:[],requirements:[],music:{required:music,intent:'restrained'},sfx:{required:false},subtitles:{required:false}})}
function voiceAsset(p){const data={format:'wav',bytes_base64:wav().toString('base64')};return seal({asset_id:'voice',type:'VOICE',business_id:p.business_id,content_job_id:p.content_job_id,plan_hash:p.content_hash,production_package_hash:p.production_package_hash,script_hash:p.script_hash,text_hash:hash('Synthetic'),data,data_hash:hash(data),qa:wavQA(wav(),2),rights:{status:'CLEARED',evidence:{authority:'human',reference:'synthetic',basis:'test'}},provenance:{origin:'synthetic',created_at:now}})}
function selectedManifest(voice=false){const p=plan(voice,true),m=makeManifest({id:'m',plan:p,assets:voice?[voiceAsset(p)]:[],attempts:[],created_at:now}),a=track(),mix=audioMixPlan({id:'mix',business_id:'tenant',content_job_id:'j',voice_asset_id:m.voice_asset_id,music_asset:a,duration:5,audio_intent:'restrained'}),selection=seal({selection_id:'sel',business_id:'tenant',content_job_id:'j',plan_hash:p.content_hash,package_id:'pkg',package_hash:'ph',music_asset_id:a.music_asset_id,music_asset_hash:a.content_hash,mix_plan_hash:mix.content_hash});return {p,m,a,mix,selection}}
test('MU01 explicit optional music overrides descriptive intent without changing legacy plans',()=>{assert.equal(musicRequirement({music_configuration:{music_required:false},audio_plan:{music_intent:'bed'}}).required,false);assert.equal(musicRequirement({audio_plan:{music_intent:'bed'}}).required,true);assert.equal(musicRequirement({music_configuration:{music_required:true},audio_plan:{}}).required,true);assert.throws(()=>musicRequirement({music_configuration:{music_required:'yes'}}),/MUSIC_REQUIREMENT_INVALID/)});
test('MU02 neither music nor voice is a valid ready configuration',()=>{const m=makeManifest({id:'m',plan:plan(),assets:[],attempts:[],created_at:now});assert.equal(m.status,'ASSETS_READY');assert.deepEqual(m.unresolved,[]);assert.equal(m.release_allowed,false)});
test('MU03 voice-only workflow does not require music',()=>{const p=plan(true,false),m=makeManifest({id:'m',plan:p,assets:[voiceAsset(p)],attempts:[],created_at:now});assert.equal(m.status,'ASSETS_READY');assert(!m.unresolved.includes('MUSIC'))});
test('MU04 required music stays unresolved without an actual selected track',()=>{const m=makeManifest({id:'m',plan:plan(false,true),assets:[],attempts:[],created_at:now});assert.deepEqual(m.unresolved,['MUSIC']);assert.equal(m.status,'ASSETS_PARTIAL')});
test('MU05 music-only and voice-plus-music selections resolve only the music requirement',()=>{for(const voice of [false,true]){const f=selectedManifest(voice),m=applyMusicSelection(f.m,f.selection,f.a,context(),f.mix);assert.equal(m.status,'ASSETS_READY');assert.equal(m.audio_mix_plan.voice_asset_id,voice?'voice':null);assert.equal(m.music.rights_status,'CLEARED');assert.equal(m.publication_hold,true);assert.equal(m.release_allowed,false)}});
test('MU06 royalty-free label never substitutes for license evidence or approval',()=>{assert.throws(()=>track({license:{...license,license_evidence:null}}),/MUSIC_LICENSE_EVIDENCE_REQUIRED/);const a=track({rights_status:'REVIEW_REQUIRED'});assert.equal(musicCompatibility(a,context()).compatible,false);assert.equal(musicCompatibility(track({status:'CANDIDATE'}),context()).compatible,false)});
test('MU07 commercial social platform territory and expiry restrictions are enforced',()=>{const a=track();for(const c of [context({platforms:['tiktok']}),context({territory:'US'}),context({as_of:null})])assert.equal(musicCompatibility(a,c).compatible,false);for(const l of [{commercial_use_allowed:false},{social_media_use_allowed:false},{expires_at:'2025-12-31T00:00:00Z'},{territories:[]},{platforms:[]},{loop_allowed:false}])assert.equal(musicCompatibility(track({license:{...license,...l}}),context()).compatible,false)});
test('MU08 user selection is explicit and cannot select an incompatible or foreign track',()=>{const a=track(),b=track();assert.equal(recommendMusic([a,b],context(),prefs(),{selected_id:b.music_asset_id}).asset.music_asset_id,b.music_asset_id);assert.throws(()=>recommendMusic([track({business_id:'other'})],context(),prefs(),{selected_id:a.music_asset_id}),/MUSIC_SELECTION_NOT_COMPATIBLE/)});
test('MU09 ambiguous recommendations never select a random fallback',()=>{const a=track(),b=track();for(const tracks of [[a,b],[b,a]]){const r=recommendMusic(tracks,context(),prefs());assert.equal(r.status,'RECOMMENDATIONS');assert.equal(r.asset,null);assert.equal(r.recommendations.length,2)}assert.equal(recommendMusic([],context(),prefs()).status,'NO_COMPATIBLE_MUSIC')});
test('MU10 business default and unique favorite resolve compatible choices without bypassing rights',()=>{const a=track(),b=track(),p=prefs({defaults:[{music_asset_id:b.music_asset_id,when:{use_case:'documentary'}}]});assert.equal(recommendMusic([a,b],context(),p).asset.music_asset_id,b.music_asset_id);assert.equal(recommendMusic([a,b],context(),prefs({favorites:[a.music_asset_id]})).asset.music_asset_id,a.music_asset_id);assert.notEqual(recommendMusic([a,revise(b,{status:'RETIRED',version:2})],context(),p).asset?.music_asset_id,b.music_asset_id)});
test('MU11 all suitability dimensions and narration presence constrain recommendation',()=>{for(const field of ['brand','language','format','channel','use_case','content_type','emotional_tone','audience','platform','pacing','audio_intent']){const a=track({suitability:{[field]:['expected']}});assert.equal(musicCompatibility(a,context({[field]:'different'})).compatible,false);assert.equal(musicCompatibility(a,context({[field]:'expected'})).compatible,true)}assert.equal(musicCompatibility(track({suitability:{narration_presence:['false']}}),context()).compatible,false)});
test('MU12 owned upload requires usage authorization and never gains automatic clearance',()=>{assert.throws(()=>track({provenance:{origin:'UPLOAD'}}),/UPLOAD_USAGE_CONFIRMATION_REQUIRED/);assert.equal(track({provenance:{origin:'UPLOAD',usage_confirmation:{actor:'human',reference:'synthetic-ownership'}}}).provenance.origin,'UPLOAD')});
test('MU13 generic and generated provider provenance stays independent of provider name',async()=>{for(const provider of ['independent-one','library-two'])assert.equal(track({provider}).provider,provider);assert.throws(()=>track({provenance:{origin:'GENERATED'}}),/MUSIC_GENERATION_PROVENANCE_REQUIRED/);assert.equal(track({provenance:{origin:'GENERATED',model:'synthetic',generation_reference:'synthetic-request'}}).provenance.model,'synthetic');const p=verifyMusicSourceProvider(new MusicSourceProvider());await assert.rejects(p.fetchAsset(),/MUSIC_ACQUISITION_NOT_AUTHORIZED/);assert.equal(p.describe().available,false)});
test('MU14 mix plan retains audibility ducking fade hook SFX and pending final QA without invented loudness',()=>{const a=track(),m=audioMixPlan({id:'mix',business_id:'tenant',content_job_id:'j',voice_asset_id:'v',music_asset:a,duration:5,audio_intent:'restrained',hook_music_intent:'mystery',section_intensity_changes:[{section:'hook',intent:'restrained'}],sfx_interaction:'No masking'});assert.equal(m.music_start,0);assert.equal(m.music_end,5);assert.equal(m.loop_strategy,'LICENSED_LOOP_WITH_TRANSITION_REVIEW');assert.match(m.ducking_intent,/Voice primary/);assert.match(m.perceptual_audibility_requirement,/actually audible/);assert.equal(m.loudness_targets,null);assert.equal(m.fade_in.seconds,null);assert.equal(m.qa_status,'NOT_RUN');assert.equal(m.credit_text,'Synthetic Artist')});
test('MU15 latest retired/restricted track versions cannot fall back to historical approvals',()=>{const a=track();for(const status of ['RETIRED','RESTRICTED']){const b=revise(a,{version:2,status});assert.equal(latestMusic([b,a])[0].status,status);assert.equal(recommendMusic([a,b],context(),prefs()).asset,null)}});
test('MU16 manifest rejects forged foreign stale or missing music selection bindings',()=>{const f=selectedManifest();const sel=more=>{const {content_hash,...s}=f.selection;return seal({...s,...more})};for(const change of [{business_id:'other'},{package_hash:'wrong'},{music_asset_hash:'wrong'},{mix_plan_hash:'wrong'}])assert.throws(()=>applyMusicSelection(f.m,sel(change),f.a,context(),f.mix),/MUSIC_SELECTION_IDENTITY_MISMATCH/);assert.throws(()=>applyMusicSelection(f.m,f.selection,f.a,context({business_id:'other'}),f.mix),/MUSIC_SELECTION_IDENTITY_MISMATCH/)});
test('MU17 automatic recommendation can be disabled independently of required music',()=>{const a=track();assert.equal(recommendMusic([a],context(),prefs({automatic_recommendation_enabled:false})).status,'HUMAN_SELECTION_REQUIRED')});
const base=process.env.TEST_DATABASE_URL,url=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let admin,db,library;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool);library=new BusinessMusicRepository(db);for(const b of ['tenant','other'])await db.seed({id:b,tenant_id:b,name:'Synthetic',brand:{}})});after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
const input=(more={})=>({title:'Uploaded synthetic audio',creator:'Synthetic Artist',provider:'test-upload',provider_asset_reference:'synthetic',source_reference:'fixture.wav',provenance:{origin:'UPLOAD'},expected_duration:2,data:{format:'wav',bytes_base64:wav().toString('base64')},...more});
async function cleared(b='tenant'){const a=await library.importCandidate(b,input());return library.decision(b,a.music_asset_id,{expected_hash:a.content_hash,status:'APPROVED',rights_status:'CLEARED',license,usage_confirmation:{actor:'human',reference:'synthetic-ownership'},actor:'human',reference:'synthetic-license-review'})}
test('MU18 PostgreSQL upload persists bytes provenance and license evidence as immutable revisions',async()=>{const a=await cleared(),rows=await library.list('tenant');assert.equal(rows.find(x=>x.music_asset_id===a.music_asset_id&&x.version===1).rights_status,'REVIEW_REQUIRED');assert.deepEqual(rows.find(x=>x.content_hash===a.content_hash).license.license_evidence,license.license_evidence);assert.deepEqual((await library.preview('tenant',a.music_asset_id)).bytes,wav());await assert.rejects(db.pool.query('DELETE FROM business_music_assets WHERE business_id=$1 AND music_asset_id=$2',['tenant',a.music_asset_id]),e=>e.code==='23514')});
test('MU19 multiple business tracks playlists defaults favorites persist across restart without tenant leaks',async()=>{const a=await cleared(),b=await cleared();const p=await library.savePreferences('tenant',{music_enabled:true,automatic_recommendation_enabled:true,favorites:[a.music_asset_id],defaults:[{music_asset_id:a.music_asset_id,when:{use_case:'science'}},{music_asset_id:b.music_asset_id,when:{format:'LONG'}}],playlists:[{name:'Documentary',music_asset_ids:[a.music_asset_id,b.music_asset_id]}]});const fresh=new PostgresStore(url.href);try{assert.deepEqual(await new BusinessMusicRepository(fresh).preferences('tenant'),p);assert.equal((await new BusinessMusicRepository(fresh).list('other')).length,0)}finally{await fresh.close()}await assert.rejects(library.preview('other',a.music_asset_id),/MUSIC_NOT_FOUND/);await assert.rejects(library.savePreferences('other',{favorites:[a.music_asset_id]}),/MUSIC_PREFERENCE_TRACK_NOT_FOUND/)});
test('MU20 uploaded audio validation secret handling and fake clearance fail closed',async()=>{await assert.rejects(library.importCandidate('tenant',input({data:{format:'wav',bytes_base64:'AAAA'}})));await assert.rejects(library.importCandidate('tenant',input({provenance:{origin:'UPLOAD',api_key:'synthetic'}})),/UNSAFE_PAYLOAD/);const a=await library.importCandidate('tenant',input({status:'APPROVED',rights_status:'CLEARED',license}));assert.equal(a.status,'CANDIDATE');assert.equal(a.rights_status,'REVIEW_REQUIRED');await assert.rejects(library.decision('tenant',a.music_asset_id,{expected_hash:a.content_hash,status:'APPROVED',actor:'agent',reference:'synthetic'}),/HUMAN_MUSIC_DECISION_REQUIRED/)});
async function production(musicEnabled){const f=await scriptFixture(db),r=await f.service.run(f.command);await new HumanProductionApproval(f.repository).record({business_id:f.b,content_job_id:f.j.id,script_id:r.scripts[0].script_id,package_id:r.packages[0].production_package_id,decisions:{script_creative_quality:'APPROVED',script_factual_safety:'APPROVED',production_package:'APPROVED_FOR_NEXT_PRODUCTION_STAGE'}});const repo=new AssetRepository(f.repository);if(musicEnabled!==undefined)await library.savePreferences(f.b,{music_enabled:musicEnabled});const p=await repo.plan(f.b,f.j.id);return {f,repo,p,service:new MusicSelectionService(repo)}}
test('MU21 actual selected music and mix persist and resolve MUSIC while other blockers remain',async()=>{const x=await production(),a=await cleared(x.f.b),r=await x.service.select({plan:x.p,context:context({business_id:x.f.b}),selected_id:a.music_asset_id});assert.equal(r.status,'SELECTED');assert.equal(r.selection.context.narration_presence,true);assert(!r.manifest.unresolved.includes('MUSIC'));assert(r.manifest.unresolved.includes('VOICE'));assert.equal(r.manifest.status,'ASSETS_PARTIAL');assert.equal(r.manifest.release_allowed,false);const d=await x.repo.records(x.p);assert.equal(d.musicSelections.length,1);assert.equal(d.audioMixPlans.length,1);assert.equal(d.attempts.length,0)});
test('MU22 retirement after attachment makes future manifests unresolved without changing history',async()=>{const x=await production(),a=await cleared(x.f.b),r=await x.service.select({plan:x.p,context:context({business_id:x.f.b}),selected_id:a.music_asset_id});const bytes=wav(x.p.voice.expected_duration),data={format:'wav',bytes_base64:bytes.toString('base64')};const v=seal({asset_id:'later-voice',type:'VOICE',business_id:x.p.business_id,content_job_id:x.p.content_job_id,plan_hash:x.p.content_hash,production_package_hash:x.p.production_package_hash,script_hash:x.p.script_hash,text_hash:x.p.voice.text_hash,data,data_hash:hash(data),qa:wavQA(bytes,x.p.voice.expected_duration),rights:{status:'REVIEW_REQUIRED',evidence:null},provenance:{origin:'synthetic',created_at:now}});await x.repo.artifact(x.p,v);const changed=await x.repo.manifest(x.p);assert(changed.unresolved.includes('MUSIC'));assert(changed.music.blocking_reasons.includes('VOICE_BINDING_CHANGED'));await library.decision(x.f.b,a.music_asset_id,{expected_hash:a.content_hash,status:'RETIRED',actor:'human',reference:'synthetic-retirement'});const m=await x.repo.manifest(x.p);assert(m.unresolved.includes('MUSIC'));assert(m.music.blocking_reasons.includes('TRACK_NOT_APPROVED'));assert.equal((await x.repo.records(x.p)).manifests[0].content_hash,r.manifest.content_hash)});
test('MU23 business foreign keys and tenant restrictions reject forged library operations',async()=>{await assert.rejects(library.importCandidate('missing-business',input()),e=>e.code==='23503');await assert.rejects(library.importCandidate('tenant',input({business_id:'other'})),/MUSIC_TENANT_MISMATCH/);await assert.rejects(library.savePreferences('tenant',{business_id:'other'}),/MUSIC_TENANT_MISMATCH/)});
test('MU24 real HTTP music UI preview preferences and cross-tenant protection work offline',async()=>{const a=await cleared(),child=spawn(process.execPath,['src/server/index.js'],{env:{...process.env,DATABASE_URL:url.href,BUSINESS_ID:'tenant',PORT:'0'},stdio:['ignore','pipe','pipe']});let browser;try{const address=await new Promise((resolve,reject)=>{let log='';child.stdout.on('data',b=>{log+=b;for(const line of log.split('\n')){try{const e=JSON.parse(line);if(e.event==='ready')resolve('http://127.0.0.1:'+e.port)}catch{}}});child.once('exit',()=>reject(Error('APP_EXIT')))});const list=await(await fetch(address+'/api/music')).json();assert(list.assets.some(t=>t.music_asset_id===a.music_asset_id));assert(list.assets.every(t=>!t.data));assert.equal((await fetch(address+'/api/music',{headers:{'x-business-id':'other'}})).status,403);const preview=await fetch(address+'/api/music/'+a.music_asset_id+'/preview');assert.equal(preview.status,200);assert.deepEqual(Buffer.from(await preview.arrayBuffer()),wav());const denied=await fetch(address+'/api/music/preferences',{method:'POST',headers:{origin:address,'content-type':'application/json'},body:JSON.stringify({business_id:'other'})});assert.equal(denied.status,403);browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();await page.goto(address);await page.locator('#music-library audio').first().waitFor();assert.match(await page.locator('#music-settings').innerText(),/Rechte/);assert.equal(await page.locator('#music-preferences input[name=music_enabled]').count(),1);assert.equal(await page.locator('#music-upload input[type=file]').count(),1);assert((await page.locator('#music-library textarea[name=terms_text]').count())>0)}finally{await browser?.close();child.kill();await once(child,'exit')}});

test('MU25 business music settings apply to new plans without mutating an existing plan',async()=>{const x=await production(false);assert.equal(x.p.music.required,false);assert(x.p.music_preference_hash);const original=x.p.content_hash;await library.savePreferences(x.f.b,{music_enabled:true});assert.equal((await x.repo.plan(x.f.b,x.f.j.id)).content_hash,original);const explicit={business_id:'tenant',music_configuration:{music_required:true},audio_plan:{music_intent:'bed'}};assert.equal(musicRequirement(explicit,prefs({music_enabled:false})).required,true)});
test('MU26 voice-only and silent AudioMixPlans require no fabricated music or loudness',()=>{for(const voice of [null,'voice']){const m=audioMixPlan({id:'mix',business_id:'tenant',content_job_id:'j',voice_asset_id:voice,duration:5});assert.equal(m.music_asset_id,null);assert.equal(m.ducking_intent,'NOT_REQUIRED');assert.equal(m.loudness_targets,null);assert.equal(m.release_allowed,false)}});

test('MU27 changed license terms invalidate previous clearance until renewed explicit human approval',async()=>{const a=await cleared(),changed=await library.decision('tenant',a.music_asset_id,{expected_hash:a.content_hash,license:{...license,license_reference:'replacement-terms'},actor:'human',reference:'changed-terms'});assert.equal(changed.rights_status,'REVIEW_REQUIRED');assert.equal(changed.rights_decision,null);assert.equal(musicCompatibility(changed,context()).compatible,false);assert.equal((await library.list('tenant')).find(t=>t.content_hash===a.content_hash).rights_status,'CLEARED')});
