import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import pg from 'pg';
import {hash} from '../src/domain/research.js';import {seal} from '../src/domain/assets.js';import {nativeFixture,designFor,manifestFor,nativeNow} from './fixtures/native-scenes.js';import {createNativeSceneAsset,validateNativeSceneAsset,applyNativeScenes} from '../src/domain/native-scenes.js';
import {PostgresStore} from '../src/persistence-postgres.js';import {migrate} from '../scripts/migrate.mjs';import {scriptFixture} from './fixtures/script.js';import {HumanProductionApproval} from '../src/application/human-production-approval.js';import {AssetRepository} from '../src/assets-postgres.js';import {NativeSceneService} from '../src/application/native-scene-service.js';import {loadNativeContext} from '../src/native-scene-context.js';
const reseal=x=>{const {content_hash,...b}=x;return seal(b)};
const asset=(c=nativeFixture(),d=designFor(c),beat=c.pkg.timeline_segments[0])=>createNativeSceneAsset(c,{id:randomUUID(),version:2,beat_id:beat.visual_beat_id??beat.segment_id,design:d,created_at:nativeNow});
function all(c=nativeFixture()){return {c,assets:c.pkg.timeline_segments.map(b=>asset(c,designFor(c,b),b))}}
test('NS01 detailed immutable native scene creation',()=>{const c=nativeFixture(),a=asset(c);assert.equal(validateNativeSceneAsset(c,a),a);assert.equal(a.data.schema,'native-scene/2');assert(a.content_hash);assert(a.data.design.foreground_elements.length)});
test('NS02 all eleven beats resolve against their exact current package',()=>{const {c,assets}=all(),m=applyNativeScenes(c,manifestFor(c),assets);assert.equal(m.mapping.length,11);assert(m.mapping.every(x=>x.ready));assert(m.unresolved.every(x=>!/^B\d+$/.test(x)))});
test('NS03 stale production package cannot be admitted',()=>{const c=nativeFixture(),a=asset(c);assert.throws(()=>validateNativeSceneAsset(c,reseal({...a,production_package_hash:'old'})),/STALE_NATIVE_PACKAGE/)});
test('NS04 voice timed bounds and audio identity are preserved',()=>{const c=nativeFixture(),a=asset(c,designFor(c,c.pkg.timeline_segments[10]),c.pkg.timeline_segments[10]);assert.equal(a.data.timeline_start,50);assert.equal(a.data.timeline_end,55);assert.equal(a.data.voice_binding.audio_hash,'audio');assert.throws(()=>validateNativeSceneAsset(c,reseal({...a,data:{...a.data,duration:49}})),/NATIVE_ASSET_MISMATCH/)});
test('NS05 exact claims evidence and full narration are retained',()=>{const c=nativeFixture(),a=asset(c);assert.deepEqual(a.claim_refs,['A']);assert.deepEqual(a.data.evidence_references,c.plan.requirements[0].evidence_references);assert.equal(a.data.narration.text,c.script.segments[0].text)});
test('NS06 blocked and context-only claims cannot enter native scenes',()=>{for(const key of ['blocked_claim_ids','context_only_claim_ids']){const c=nativeFixture(),{content_scope_hash,...s}=c.scope;s[key]=['A'];c.scope={...s,content_scope_hash:hash(s)};c.pkg=reseal({...c.pkg,scope_hash:c.scope.content_scope_hash});assert.throws(()=>asset(c),/NATIVE_BLOCKED_CLAIM/)}});
test('NS07 factual classification cannot be relabeled',()=>{const c=nativeFixture(),d=designFor(c);d.factual_classification='OBSERVED';assert.throws(()=>asset(c,d),/NATIVE_NOT_OBSERVED/)});
test('NS08 disclosure cannot be dropped or rewritten',()=>{const c=nativeFixture(),d=designFor(c);d.labels=[];assert.throws(()=>asset(c,d),/NATIVE_DISCLOSURE/);d.disclosure_requirement.visible=false;assert.throws(()=>asset(c,d),/NATIVE_DISCLOSURE/)});
test('NS09 native provenance excludes acquired media',()=>{const c=nativeFixture(),d=designFor(c);d.external_media=true;assert.throws(()=>asset(c,d),/NATIVE_PROVENANCE/)});
test('NS10 original scene rights are scoped to specification only',()=>{const a=asset();assert.equal(a.rights.status,'CLEARED');assert.equal(a.provenance.rights_scope,'SPECIFICATION_ONLY');assert.equal(a.release_allowed,false)});
test('NS11 third party dependencies remain rights review required',()=>{const c=nativeFixture(),d=designFor(c);d.third_party_dependencies=[{kind:'font',reference:'unverified-test-font'}];const a=asset(c,d),m=applyNativeScenes(c,manifestFor(c),[a]);assert.equal(a.rights.status,'REVIEW_REQUIRED');assert(m.unresolved.includes('B1'))});
test('NS12 scene composition is mandatory',()=>{const c=nativeFixture(),d=designFor(c);d.scene_composition={};assert.throws(()=>asset(c,d),/NATIVE_COMPOSITION/)});
test('NS13 concrete motion and animation are mandatory',()=>{const c=nativeFixture(),d=designFor(c);d.element_animation=[];assert.throws(()=>asset(c,d),/NATIVE_MOTION_ELEMENTS/)});
test('NS14 exact supported text persists and new factual text is rejected',()=>{const c=nativeFixture(),d=designFor(c);d.text_overlays=[{...d.labels[0],text:'84 candidates',category:'HOOK_TEXT',anchor:{kind:'narration',text:'84 candidates'}}];assert.equal(asset(c,d).data.design.text_overlays[0].text,'84 candidates');d.text_overlays[0].text='All sources are white dwarfs';assert.throws(()=>asset(c,d),/NATIVE_UNSUPPORTED_TEXT/)});
test('NS15 mobile safe areas and subtitle exclusion enforced',()=>{const c=nativeFixture(),d=designFor(c);assert.deepEqual(asset(c,d).data.design.safe_zone_notes.safe_areas,c.pkg.safe_areas);d.foreground_elements[0].y=.75;assert.throws(()=>asset(c,d),/NATIVE_ELEMENT_BOUNDS/)});
test('NS16 diagram semantics are required',()=>{const c=nativeFixture(),d=designFor(c);d.data_or_diagram_primitives=[];assert.throws(()=>asset(c,d),/NATIVE_DIAGRAM_SEMANTICS/)});
test('NS17 schematic positions cannot become measured coordinates',()=>{const c=nativeFixture(),d=designFor(c);d.data_or_diagram_primitives[0].positions='MEASURED_SKY';assert.throws(()=>asset(c,d),/NATIVE_SCHEMATIC/)});
const count=mode=>({mode,display:mode==='MINIMUM'?'At least six':'84 candidates',source_anchor:mode==='MINIMUM'?'At least six examples':'84 candidates',complete_census:false,spatial_positions:false,per_group_distribution:false});
test('NS18 candidate count cannot imply complete census',()=>{const c=nativeFixture(),d=designFor(c);d.data_or_diagram_primitives[0].counts=[count('SELECTED_SAMPLE')];asset(c,d);d.data_or_diagram_primitives[0].counts[0].complete_census=true;assert.throws(()=>asset(c,d),/NATIVE_COUNT_SCOPE/)});
test('NS19 minimum count cannot silently become exact six',()=>{const c=nativeFixture(),d=designFor(c),n=count('MINIMUM');d.data_or_diagram_primitives[0].counts=[n];asset(c,d);n.display='six';assert.throws(()=>asset(c,d),/NATIVE_MINIMUM_COUNT/)});
test('NS20 physical explanation never generalizes to all sources',()=>{const c=nativeFixture(),d=designFor(c);d.data_or_diagram_primitives[0].population_generalization=true;assert.throws(()=>asset(c,d),/NATIVE_IDENTITY_OVERCLAIM/)});
test('NS21 conceptual scenes cannot claim to be real observations',()=>{const c=nativeFixture(),d=designFor(c);d.data_or_diagram_primitives[0].real_observation=true;assert.throws(()=>asset(c,d),/NATIVE_IDENTITY_OVERCLAIM/)});
test('NS22 native authoring leaves provider routing unchanged',()=>{const c=nativeFixture(),before=JSON.stringify(c.plan);asset(c);assert.equal(JSON.stringify(c.plan),before);const d=structuredClone(c);d.plan=reseal({...d.plan,requirements:d.plan.requirements.map(x=>({...x,resolution_type:'GENERATED_STILL'}))});assert.throws(()=>asset(d),/NATIVE_BEAT_ROUTE/)});
test('NS23 native authoring uses zero provider calls',()=>{const old=globalThis.fetch;globalThis.fetch=()=>{throw Error('NETWORK_FORBIDDEN')};try{const {assets}=all();assert(assets.every(x=>x.provenance.external_calls===0))}finally{globalThis.fetch=old}});
test('NS24 manifest maps every beat to its new immutable asset',()=>{const {c,assets}=all(),m=applyNativeScenes(c,manifestFor(c),assets);for(const [i,r] of m.mapping.entries()){assert.equal(r.asset_id,assets[i].asset_id);assert.equal(r.timing_status,'BOUND_TO_CURRENT_PACKAGE')}});
for(const [id,field] of [['25','MUSIC'],['26','SFX'],['27','SUBTITLE_TIMING']])test('NS'+id+' '+field+' remains unresolved after visual specs',()=>{const {c,assets}=all();assert(applyNativeScenes(c,manifestFor(c),assets).unresolved.includes(field))});
test('NS28 publication HOLD remains true',()=>{const {c,assets}=all();assert.equal(applyNativeScenes(c,manifestFor(c),assets).publication_hold,true)});
test('NS29 renderer and release readiness remain blocked',()=>{const {c,assets}=all(),m=applyNativeScenes(c,manifestFor(c),assets);assert.equal(m.release_allowed,false);assert.equal(m.renderer_ready,false);assert.equal(m.human_review_required,true)});
test('NS30 foreign business asset cannot be admitted',()=>{const c=nativeFixture(),a=asset(c);assert.throws(()=>validateNativeSceneAsset(c,reseal({...a,business_id:'foreign'})),/NATIVE_TENANT/)});
const base=process.env.TEST_DATABASE_URL,url=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
async function persisted(){const f=await scriptFixture(db),r=await f.service.run(f.command);await new HumanProductionApproval(f.repository).record({business_id:f.b,content_job_id:f.j.id,script_id:r.scripts[0].script_id,package_id:r.packages[0].production_package_id,decisions:{script_creative_quality:'APPROVED',script_factual_safety:'APPROVED',production_package:'APPROVED_FOR_NEXT_PRODUCTION_STAGE'}});const repo=new AssetRepository(f.repository),plan=await repo.plan(f.b,f.j.id),context=await loadNativeContext(db.pool,plan,plan.production_package_id),command={plan,package_id:plan.production_package_id,designs:context.pkg.timeline_segments.map(b=>({beat_id:b.visual_beat_id??b.segment_id,design:designFor(context,b)})),source:{reference:'synthetic-authoring',sha256:hash('synthetic')}};return {f,repo,command,service:new NativeSceneService(repo)}}
test('NS31 PostgreSQL native assets survive restart with complete immutable bindings',async()=>{const x=await persisted(),r=await x.service.createBatch(x.command),fresh=new PostgresStore(url.href);try{const repo=new AssetRepository({store:fresh,withJobLock:x.f.repository.withJobLock.bind(x.f.repository)}),d=await repo.records(x.command.plan);assert.equal(d.artifacts.length,r.assets.length);assert.deepEqual(d.artifacts.map(a=>a.content_hash),r.assets.map(a=>a.content_hash));const m=await repo.manifest(x.command.plan);assert(m.mapping.every(x=>x.ready));assert.equal(d.attempts.length,0)}finally{await fresh.close()}});
test('NS32 renderer reference hashes remain unchanged',()=>{for(const line of readFileSync('docs/SOURCE_HASHES.tsv','utf8').trim().split(/\r?\n/).slice(1)){const [p,h]=line.split('\t');assert.equal(createHash('sha256').update(readFileSync(new URL('../../arktrov-remotion/'+p,import.meta.url))).digest('hex'),h)}});
test('NS33 Make originals remain unchanged',()=>{assert.equal(execFileSync('git',['diff','--name-only','v0.3.0-script-production','--','legacy'],{encoding:'utf8'}).trim(),'')});
test('NS34 duplicate concurrent batch reuses artifacts and one manifest',async()=>{const x=await persisted(),[a,b]=await Promise.all([x.service.createBatch(x.command),x.service.createBatch(x.command)]);assert.equal(a.manifest.manifest_id,b.manifest.manifest_id);assert.equal((await x.repo.records(x.command.plan)).manifests.length,1)});
test('NS35 failed batch rolls back and prior history cannot be overwritten',async()=>{const x=await persisted(),original=db.transaction.bind(db);db.transaction=fn=>original(async c=>{const query=c.query.bind(c);c.query=(q,p)=>{if(q.startsWith('INSERT INTO evidence_records')&&p[3]==='asset_manifest')throw Error('SYNTHETIC_STORAGE_FAILURE');return query(q,p)};try{return await fn(c)}finally{c.query=query}});try{await assert.rejects(x.service.createBatch(x.command),/SYNTHETIC_STORAGE_FAILURE/)}finally{db.transaction=original}assert.equal((await x.repo.records(x.command.plan)).artifacts.length,0);const r=await x.service.createBatch(x.command);await assert.rejects(db.pool.query("DELETE FROM evidence_records WHERE business_id=$1 AND type='asset_artifact'",[x.f.b]),e=>e.code==='23514');assert.equal((await x.repo.records(x.command.plan)).artifacts[0].content_hash,r.assets[0].content_hash)});

test('NS36 PostgreSQL scenes bind to the voice timing revision and reject the old package',async()=>{
 const x=await persisted(),plan=x.command.plan,seconds=plan.voice.expected_duration,rate=8000,count=Math.round(seconds*rate),bytes=Buffer.alloc(44+count*2);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(rate,24);bytes.writeUInt32LE(rate*2,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)bytes.writeInt16LE(Math.round(Math.sin(i/8)*5000),44+i*2);
 const {wavQA}=await import('../src/domain/asset-qa.js'),candidate=await x.repo.voiceProfiles.candidate(x.f.b,{provider:'synthetic',model:'local',provider_voice_reference:'test',voice_kind:'CATALOGUE',language:'en'}),profile=await x.repo.voiceProfiles.decision(x.f.b,candidate.voice_profile_id,{expected_hash:candidate.content_hash,decision:'APPROVED',actor:{type:'human',id:'test'},reference:'synthetic'});
 const data={format:'wav',bytes_base64:bytes.toString('base64')},voice=seal({asset_id:'test-voice',version:1,type:'VOICE',business_id:plan.business_id,content_job_id:plan.content_job_id,plan_hash:plan.content_hash,production_package_hash:plan.production_package_hash,script_hash:plan.script_hash,text_hash:plan.voice.text_hash,data,data_hash:hash(data),qa:wavQA(bytes,seconds),rights:{status:'REVIEW_REQUIRED',evidence:null},provenance:{origin:'synthetic',created_at:nativeNow,profile}});await x.repo.artifact(plan,voice);
 const {VoiceTimingService}=await import('../src/application/voice-timing.js'),{voiceDecisions}=await import('../src/domain/production-timing.js');
 const t=await new VoiceTimingService(x.repo).record({plan,voice_asset_id:voice.asset_id,actor:'human',decisions:voiceDecisions,source:{reference:'synthetic',sha256:hash('test')}});
 await assert.rejects(x.service.createBatch(x.command),/STALE_NATIVE_PACKAGE/);
 const c=await loadNativeContext(db.pool,plan,t.package.production_package_id),command={...x.command,package_id:c.pkg.production_package_id,designs:c.pkg.timeline_segments.map(b=>({beat_id:b.visual_beat_id??b.segment_id,design:designFor(c,b)}))};
 const r=await x.service.createBatch(command);assert(r.manifest.mapping.every(x=>x.ready));assert(r.assets.every(a=>a.production_package_hash===t.package.content_hash&&a.data.voice_binding.audio_hash===voice.qa.file_sha256));assert(r.manifest.unresolved.includes('VOICE_RIGHTS:VOICE'));const rebuilt=await x.repo.manifest(plan);assert(rebuilt.mapping.every(x=>x.ready));assert.equal(rebuilt.effective_production_package_hash,t.package.content_hash);
});

