import test from 'node:test';
import assert from 'node:assert/strict';
import {adapterFixture,sentinel,responseFixture} from './fixtures/openai-response.js';
import {providerFailure} from '../src/providers/failure.js';
import {recoverableResponse,reprocessResponseArtifact} from '../src/providers/openai-recovery.js';
import {openAIResearchConfig} from '../src/config/openai-research.js';
const final=e=>e.output.find(x=>x.phase==='final_answer');
for(const [name,mutate,ok] of [['valid',()=>{},true],['parser failure',e=>final(e).content[0].text='{broken',false],['schema failure',e=>final(e).content[0].text='{}',false]])test('REC capture before '+name+' and offline reprocessing has no calls',async()=>{const f=await adapterFixture(mutate);let saved;f.context.persistProviderResponse=async a=>{saved=structuredClone(a);assert.equal(a.payload.processing.capture_version,'sanitized-response/1.0');return {evidence_id:'saved',content_hash:a.content_hash}};if(ok)await f.provider.execute(f.request,f.context);else await assert.rejects(f.provider.execute(f.request,f.context));assert(saved);const calls=f.calls();const r=reprocessResponseArtifact(saved);assert.equal(r.success,ok);assert.equal(f.calls(),calls);assert.equal(saved.payload.tool_usage.web_search_calls,1);assert.equal(saved.payload.response.usage.output_tokens,567);assert.equal(saved.payload.response.usage.output_tokens_details.reasoning_tokens,200);assert(!JSON.stringify(saved).includes('PRIVATE_REASONING_FIXTURE'));assert(!JSON.stringify(saved).includes(sentinel));});
test('REC persistence failure stops before parser and retains usage',async()=>{const f=await adapterFixture(e=>final(e).content[0].text='{malformed');f.context.persistProviderResponse=async()=>{throw Error('sensitive storage error')};let error;try{await f.provider.execute(f.request,f.context)}catch(e){error=e}const m=providerFailure(error).metadata;assert.equal(m.diagnostics.exception_message,'RESPONSE_ARTIFACT_PERSISTENCE_FAILED');assert.equal(m.diagnostics.parser_stage,'A_RESPONSE_ARTIFACT');assert.equal(m.usage.total_tokens,1801);assert.equal(f.calls(),1)});
test('REC incorrect readback hash stops processing',async()=>{const f=await adapterFixture();f.context.persistProviderResponse=async()=>({evidence_id:'saved',content_hash:'wrong'});await assert.rejects(f.provider.execute(f.request,f.context),/RESPONSE_ARTIFACT_PERSISTENCE_FAILED/)});
test('REC missing sink prevents spending',async()=>{const f=await adapterFixture();delete f.context.persistProviderResponse;await assert.rejects(f.provider.execute(f.request,f.context),/RESPONSE_PERSISTENCE_REQUIRED/);assert.equal(f.calls(),0)});
test('REC secret and private reasoning fields excluded and redacted artifact cannot pass offline',async()=>{const {envelope}=await responseFixture();envelope.authorization='Bearer secret';envelope.password='password';envelope.output[0].encrypted_content='private encrypted';final(envelope).content[0].text=JSON.stringify({summary:sentinel,chain_of_thought:'hidden',password:'private password'});const a=recoverableResponse(envelope,{credential:sentinel,config:openAIResearchConfig({}),request_id:'req_safe',run_id:'run',request_hash:'hash'});const serialized=JSON.stringify(a);for(const text of [sentinel,'hidden','private encrypted','private password','PRIVATE_REASONING_FIXTURE','Bearer secret'])assert(!serialized.includes(text));assert.equal(a.payload.redacted,true);assert.equal(reprocessResponseArtifact(a).success,false)});
test('REC artifact tampering rejected',async()=>{const f=await adapterFixture();let saved;f.context.persistProviderResponse=async a=>{saved=structuredClone(a);return {evidence_id:'saved',content_hash:a.content_hash}};await f.provider.execute(f.request,f.context);saved.payload.response.status='failed';assert.throws(()=>reprocessResponseArtifact(saved),/HASH_MISMATCH/)});
test('REC malformed HTTP-success JSON still captures safe failure artifact',async()=>{const f=await adapterFixture(()=>{},{transport:async()=>new Response('{broken')});let saved;f.context.persistProviderResponse=async a=>{saved=a;return {evidence_id:'saved',content_hash:a.content_hash}};await assert.rejects(f.provider.execute(f.request,f.context),/OPENAI_INVALID_JSON/);assert(saved);assert.equal(saved.payload.response,null);assert.equal(reprocessResponseArtifact(saved).success,false)});

test('REC split final text cannot evade secret sanitization',async()=>{const {envelope}=await responseFixture();const msg=final(envelope),value=JSON.stringify({summary:sentinel,password:'not-for-storage'});msg.content=[{type:'output_text',text:value.slice(0,25)},{type:'output_text',text:value.slice(25)}];const a=recoverableResponse(envelope,{credential:sentinel,config:openAIResearchConfig({}),request_id:'req',run_id:'run',request_hash:'hash'});assert(!JSON.stringify(a).includes(sentinel));assert(!JSON.stringify(a).includes('not-for-storage'));assert.equal(a.payload.redacted,true)});

test('REC only final assistant content retained while analysis messages excluded',async()=>{const {envelope}=await responseFixture();envelope.output.unshift({type:'message',role:'assistant',phase:'analysis',content:[{type:'output_text',text:'HIDDEN_ANALYSIS_TEXT'}]});const a=recoverableResponse(envelope,{credential:sentinel,config:openAIResearchConfig({}),request_id:'req',run_id:'run',request_hash:'hash'});assert(!JSON.stringify(a).includes('HIDDEN_ANALYSIS_TEXT'));assert.equal(reprocessResponseArtifact(a).success,true)});
