import {researchRunReport} from '../src/application/research-run-report.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {adapterFixture,sentinel} from './fixtures/openai-response.js';
import {providerFailure} from '../src/providers/failure.js';
import {schemaIssue} from '../src/providers/openai-response.js';
const final=e=>e.output.find(x=>x.phase==='final_answer');
async function failure(f){let error;try{await f.provider.execute(f.request,f.context)}catch(e){error=e}assert(error);const d=providerFailure(error);assert(d);assert(!JSON.stringify(d).includes(sentinel));assert(!JSON.stringify(d).includes('PRIVATE_REASONING_FIXTURE'));assert.equal(f.calls(),1);return d;}
test('DIAG01 Tool and commentary before final structured message normalize correctly',async()=>{const f=await adapterFixture(),r=await f.provider.execute(f.request,f.context);assert.deepEqual(r.output,f.output);assert.equal(r.metadata.diagnostics.parser_stage,'COMPLETE');assert.equal(r.metadata.usage.total_tokens,1801);assert(!JSON.stringify(r).includes('PRIVATE_REASONING_FIXTURE'))});
test('DIAG02 Split text blocks of final message combine without commentary',async()=>{const f=await adapterFixture(e=>{const t=final(e).content[0];final(e).content=[{...t,text:t.text.slice(0,30)},{...t,text:t.text.slice(30)}]});assert.deepEqual((await f.provider.execute(f.request,f.context)).output,f.output)});
test('DIAG03 Malformed JSON retains HTTP request usage and exact parser stage',async()=>{const f=await adapterFixture(e=>final(e).content[0].text='{bad json');const d=await failure(f);assert.equal(d.category,'PARSING_FAILURE');assert.equal(d.metadata.diagnostics.parser_stage,'E_STRUCTURED_JSON');assert.equal(d.metadata.diagnostics.exception_class,'SyntaxError');assert.equal(d.metadata.diagnostics.http_status,200);assert.equal(d.metadata.provider_request_id,'req_diagnostic_fixture');assert.equal(d.metadata.usage.total_tokens,1801)});
test('DIAG04 Schema mismatch has a safe field path',async()=>{const f=await adapterFixture((e,o)=>{o.claims[0].needs_qualification=null;final(e).content[0].text=JSON.stringify(o)});const d=await failure(f);assert.equal(d.metadata.diagnostics.parser_stage,'F_SCHEMA_VALIDATION');assert.equal(d.metadata.diagnostics.validation_path,'$.claims[0].needs_qualification')});
test('DIAG05 Missing final output does not accept commentary',async()=>{const f=await adapterFixture(e=>e.output=e.output.filter(x=>x.phase!=='final_answer'));const d=await failure(f);assert.equal(d.metadata.diagnostics.parser_stage,'D_RESPONSE_EXTRACTION');assert.equal(d.metadata.diagnostics.final_text_present,false);assert.equal(d.metadata.usage.input_tokens,1234)});
test('DIAG06 Incomplete response retains supplied usage and token limit reason',async()=>{const f=await adapterFixture(e=>{e.status='incomplete';e.incomplete_details={reason:'max_output_tokens'}});const d=await failure(f);assert.equal(d.metadata.diagnostics.parser_stage,'B_COMPLETION_STATUS');assert.equal(d.metadata.diagnostics.incomplete_reason,'max_output_tokens');assert.equal(d.metadata.usage.output_tokens,567)});
test('DIAG07 Refusal text never persists but refusal flag does',async()=>{const f=await adapterFixture(e=>final(e).content=[{type:'refusal',refusal:'SENSITIVE_REFUSAL'}]);const d=await failure(f);assert.equal(d.metadata.diagnostics.refusal,true);assert.equal(d.metadata.diagnostics.exception_message,'OPENAI_REFUSAL');assert(!JSON.stringify(d).includes('SENSITIVE_REFUSAL'))});
test('DIAG08 Error response retains only allowlisted error code',async()=>{const f=await adapterFixture(e=>{e.status='failed';e.error={code:'server_error',message:'SENSITIVE_ERROR'}});const d=await failure(f);assert.equal(d.metadata.diagnostics.provider_error_code,'server_error');assert(!JSON.stringify(d).includes('SENSITIVE_ERROR'))});
test('DIAG09 Broken claim relation is rejected with relation field path',async()=>{const f=await adapterFixture((e,o)=>{o.evidence[0].claim_id='missing';final(e).content[0].text=JSON.stringify(o)});const d=await failure(f);assert.equal(d.metadata.diagnostics.parser_stage,'H_CLAIM_EVIDENCE_VALIDATION');assert.equal(d.metadata.diagnostics.validation_path,'$.evidence[0].claim_id')});
test('DIAG10 Missing search evidence and untraced source have distinct stages',async()=>{const f=await adapterFixture(e=>e.output=e.output.filter(x=>x.type!=='web_search_call'));assert.equal((await failure(f)).metadata.diagnostics.parser_stage,'C_WEB_SEARCH');const g=await adapterFixture((e,o)=>{o.sources[0].url='https://unconsulted.invalid';final(e).content[0].text=JSON.stringify(o)});const d=await failure(g);assert.equal(d.metadata.diagnostics.validation_rule,'consulted_source');assert.equal(d.metadata.diagnostics.validation_path,'$.sources[0].url')});
test('DIAG11 Required nullable fields arrays and unsupported extra fields stay strict',async()=>{const f=await adapterFixture();assert.equal(schemaIssue(f.output),null);const missing=structuredClone(f.output);delete missing.main_source;assert.equal(schemaIssue(missing).rule,'required');assert.equal(schemaIssue({...f.output,uncertainties:null}).path,'$.uncertainties');assert.equal(schemaIssue({...f.output,unknown:'private'}).rule,'additionalProperties');const nullable=structuredClone(f.output);nullable.sources[0].published_at=null;assert.equal(schemaIssue(nullable),null)});
test('DIAG12 Credential echoes are removed from diagnostics and exception text',async()=>{const f=await adapterFixture(e=>{e.id=sentinel;e.output[0].summary[0].text=sentinel});const d=await failure(f);assert.equal(d.category,'UNSAFE_PAYLOAD');assert.equal(d.metadata.diagnostics.response_id,null);assert.equal(d.metadata.usage.total_tokens,1801)});
test('DIAG13 Primitive or malformed envelopes fail without raw TypeErrors',async()=>{for(const payload of [null,[],42]){const f=await adapterFixture(()=>{},{transport:async()=>new Response(JSON.stringify(payload))});let e;try{await f.provider.execute(f.request,f.context)}catch(x){e=x}assert.equal(e.name,'ProviderFailure');assert.equal(providerFailure(e).metadata.diagnostics.parser_stage,'B_COMPLETION_STATUS')}});
test('DIAG14 Duplicate final answers are rejected rather than guessed',async()=>{const f=await adapterFixture(e=>e.output.push(structuredClone(final(e))));assert.equal((await failure(f)).metadata.diagnostics.exception_message,'OPENAI_AMBIGUOUS_FINAL_OUTPUT')});
test('DIAG15 Forged ordinary error metadata never enters trusted failure channel',()=>{const e=Error('sensitive');e.metadata={diagnostics:{exception_message:'sensitive'}};assert.equal(providerFailure(e),null)});

test('DIAG16 Local report uses persisted failure diagnostics without response contents',async()=>{const f=await adapterFixture(e=>e.status='incomplete'),failureData=await failure(f);const report=researchRunReport({run_id:'fixture',attempt:2,status:'FAILED',error_category:failureData.category,metadata:failureData.metadata,request:{ignored:'PRIVATE_REQUEST'},output:'PRIVATE_OUTPUT'});assert.equal(report.http_result,200);assert.equal(report.usage.total_tokens,1801);assert.equal(report.diagnostics.response_status,'incomplete');assert(!JSON.stringify(report).includes('PRIVATE_'));});
