import test from 'node:test';
import assert from 'node:assert/strict';
import {inspect} from 'node:util';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {OpenAIResearchProvider} from '../src/providers/openai-research.js';
import {researchOutputSchema} from '../src/providers/openai-research-schema.js';
import {openAIResearchConfig} from '../src/config/openai-research.js';
import {LocalResearchProvider} from '../src/providers/local.js';
import {researchPrompt,genericPolicy} from '../src/config/research.js';
import {canonical,hash,metadata,validateResearch} from '../src/domain/research.js';
import {prepareSingleOpenAIResearch,runSinglePreparedResearch} from '../src/application/openai-research-connection.js';
const sentinel='offline-transport-fixture-not-a-real-credential';
async function fixture(options={}){
 const calls=[];
 const canonicalResult=(await new LocalResearchProvider().execute({input:{topic:'Offline adapter contract'}},{attempt:1,run_id:'fixture'})).output;
 const envelope={id:'resp_mock',model:'gpt-5.6-sol',status:'completed',error:null,incomplete_details:null,usage:{input_tokens:120,output_tokens:240,total_tokens:360,input_tokens_details:{cached_tokens:10},output_tokens_details:{reasoning_tokens:40}},output:[{type:'reasoning',summary:[{text:'private-response-item-must-not-persist'}]},{type:'web_search_call',status:'completed',action:{type:'search',sources:canonicalResult.sources.map(s=>({url:s.url}))}},{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(canonicalResult),annotations:[]}]}]};
 const permit=(request,context)=>({run_id:context.run_id,business_id:request.business_id,content_job_id:request.content_job_id,idempotency_key:'offline-key',canonical_input_hash:hash(request),prompt_version:request.prompt.version,workflow_version:request.workflow_version,policy_version:request.policy.version,provider_config_hash:hash(request.provider)});
 const transport=async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify(envelope),{status:200,headers:{'x-request-id':'req_mock'}})};
 const provider=new OpenAIResearchProvider({credential:()=>sentinel,transport,authorizeDispatch:async(...args)=>permit(...args),...options});
 const request={business_id:'offline-business',content_job_id:'offline-job',operation:'research',input:{topic:'Offline adapter contract',starting_source_references:[{title:'Unverified starting reference',verification_status:'UNVERIFIED_STARTING_REFERENCE'}]},workflow_version:'phase-2a.1',prompt:researchPrompt,policy:genericPolicy,provider:provider.describe()};
 return {provider,request,context:{persistProviderResponse:async a=>({evidence_id:'offline-artifact',content_hash:a.content_hash}),attempt:1,run_id:'offline-run'},calls,envelope,canonicalResult,permit};
}
test('OAI01 Missing credential disables dispatch with clear error',async()=>{const f=await fixture({credential:()=>''});assert.equal(f.provider.credentialPresent(),false);await assert.rejects(f.provider.execute(f.request,f.context),/OPENAI_API_KEY_MISSING/);assert.equal(f.calls.length,0)});
test('OAI02 No explicit permit means no HTTP request',async()=>{const f=await fixture({authorizeDispatch:async()=>null});await assert.rejects(f.provider.execute(f.request,f.context),/LIVE_DISPATCH_NOT_AUTHORIZED/);assert.equal(f.calls.length,0)});
test('OAI03 Responses request uses required live search and strict canonical schema',async()=>{const f=await fixture();await f.provider.execute(f.request,f.context);assert.equal(f.calls.length,1);const {url,init}=f.calls[0],body=JSON.parse(init.body);assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(init.method,'POST');assert.equal(init.redirect,'error');assert.equal(body.model,'gpt-5.6-sol');assert.equal(body.store,false);assert.equal(body.background,false);assert.equal(body.tool_choice,'required');assert.deepEqual(body.tools,[{type:'web_search',external_web_access:true}]);assert.deepEqual(body.include,['web_search_call.action.sources']);assert.equal(body.text.format.strict,true);assert.deepEqual(body.text.format.schema,researchOutputSchema);assert.equal(body.max_output_tokens,6000);assert.equal(body.max_tool_calls,4);assert(!init.body.includes(sentinel));assert.equal(init.headers.authorization,'Bearer '+sentinel)});
test('OAI04 Canonical result and usage survive existing metadata contract',async()=>{const f=await fixture(),r=await f.provider.execute(f.request,f.context);assert.deepEqual(validateResearch(r.output),f.canonicalResult);const m=metadata(r.metadata);assert.equal(m.synthetic,false);assert.equal(m.provider_request_id,'req_mock');assert.equal(m.usage.input_tokens,120);assert.equal(m.usage.tool_usage.web_search_calls,1);assert.equal(m.cost.actual,null);assert.equal(m.cost.estimated,null);assert(!canonical(r).includes('private-response-item'));assert(!canonical(r).includes(sentinel))});
test('OAI05 Credential never appears in serialization or descriptor',async()=>{const f=await fixture();assert(!inspect(f.provider,{showHidden:true}).includes(sentinel));assert(!JSON.stringify(f.provider).includes(sentinel));assert(!canonical(f.provider.describe()).includes(sentinel))});
test('OAI06 Repeated or concurrent executions consume one HTTP allowance',async()=>{const f=await fixture();const r=await Promise.allSettled([f.provider.execute(f.request,f.context),f.provider.execute(f.request,f.context)]);assert.equal(r.filter(x=>x.status==='fulfilled').length,1);assert.equal(f.calls.length,1);await assert.rejects(f.provider.execute(f.request,f.context),/ALREADY_CONSUMED/)});
test('OAI07 Retry attempts are refused before HTTP',async()=>{const f=await fixture();await assert.rejects(f.provider.execute(f.request,{...f.context,attempt:2}),/LIVE_RETRY_REQUIRES_RECONCILIATION/);assert.equal(f.calls.length,0)});
test('OAI08 Changed config and invalid permits fail before HTTP',async()=>{const f=await fixture();await assert.rejects(f.provider.execute({...f.request,provider:{...f.request.provider,model:'different'}},f.context),/CONFIGURATION_MISMATCH/);const g=await fixture({authorizeDispatch:async()=>({idempotency_key:'k',canonical_input_hash:'wrong'})});await assert.rejects(g.provider.execute(g.request,g.context),/NOT_AUTHORIZED/);assert.equal(f.calls.length+g.calls.length,0)});
test('OAI09 HTTP failures never expose body or retry',async()=>{let calls=0;const f=await fixture({transport:async()=>{calls++;return new Response('sensitive upstream body '+sentinel,{status:429})}});await assert.rejects(f.provider.execute(f.request,f.context),e=>e.message==='OPENAI_HTTP_429'&&!e.stack.includes(sentinel));await assert.rejects(f.provider.execute(f.request,f.context),/ALREADY_CONSUMED/);assert.equal(calls,1)});
test('OAI10 Transport exceptions are redacted',async()=>{const f=await fixture({transport:async()=>{throw Error(sentinel)}});await assert.rejects(f.provider.execute(f.request,f.context),e=>e.message==='OPENAI_TRANSPORT_FAILURE'&&!e.stack.includes(sentinel)&&!e.cause)});
test('OAI11 Timeout aborts transport without automatic retry',async()=>{let calls=0;const f=await fixture({config:openAIResearchConfig({OPENAI_RESEARCH_TIMEOUT_MS:'100'}),transport:async(_,init)=>{calls++;return new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(Error('aborted')),{once:true}))}});await assert.rejects(f.provider.execute(f.request,f.context),/OPENAI_TIMEOUT/);assert.equal(calls,1)});
test('OAI12 Incomplete responses never become ResearchResult',async()=>{const f=await fixture();f.envelope.status='incomplete';await assert.rejects(f.provider.execute(f.request,f.context),/INCOMPLETE_RESPONSE/)});
test('OAI13 Missing search execution fails closed',async()=>{const f=await fixture();f.envelope.output=f.envelope.output.filter(x=>x.type!=='web_search_call');await assert.rejects(f.provider.execute(f.request,f.context),/WEB_SEARCH_NOT_VERIFIED/)});
test('OAI14 Source URL absent from consulted sources is rejected',async()=>{const f=await fixture();f.envelope.output.find(x=>x.type==='web_search_call').action.sources=[];await assert.rejects(f.provider.execute(f.request,f.context),/UNTRACED_SOURCE/)});
test('OAI15 Refusal and malformed research are rejected',async()=>{const f=await fixture();f.envelope.output.at(-1).content=[{type:'refusal',refusal:'not included in error'}];await assert.rejects(f.provider.execute(f.request,f.context),/OPENAI_REFUSAL/);const g=await fixture();g.envelope.output.at(-1).content[0].text='{}';await assert.rejects(g.provider.execute(g.request,g.context),/INVALID_RESEARCH_RESULT/)});
test('OAI16 Raw and JSON-escaped credential echoes are rejected',async()=>{for(const escaped of [false,true]){const f=await fixture();f.envelope.output.at(-1).content[0].text=JSON.stringify({...f.canonicalResult,summary:sentinel});const response=JSON.stringify(f.envelope);const g=await fixture({transport:async()=>new Response(escaped?response.replaceAll(sentinel,sentinel.split('').map(c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')).join('')):response)});await assert.rejects(g.provider.execute(g.request,g.context),/UNSAFE_PROVIDER_RESPONSE/)}});
test('OAI17 Central model is configurable and cannot carry arbitrary secret config',()=>{assert.equal(openAIResearchConfig({OPENAI_RESEARCH_MODEL:'alternative-model'}).model,'alternative-model');assert.throws(()=>openAIResearchConfig({OPENAI_RESEARCH_MODEL:'https://evil.invalid'}),/INVALID_OPENAI_MODEL/);assert.throws(()=>new OpenAIResearchProvider({config:{...openAIResearchConfig({}),api_key:'forbidden'}}),/INVALID_OPENAI_CONFIGURATION/);assert.throws(()=>openAIResearchConfig({OPENAI_RESEARCH_MAX_TOOL_CALLS:'99'}),/INVALID_OPENAI_CONFIGURATION/)});
test('OAI18 Input and response limits fail closed',async()=>{const f=await fixture();f.request.input.topic='x'.repeat(70000);await assert.rejects(f.provider.execute(f.request,f.context),/INPUT_LIMIT/);assert.equal(f.calls.length,0);const g=await fixture({transport:async()=>new Response('x'.repeat(2097153))});await assert.rejects(g.provider.execute(g.request,g.context),/RESPONSE_LIMIT/)});
test('OAI19 JSON schema keeps every object closed and required',()=>{const walk=s=>{if(s.type==='object'){assert.equal(s.additionalProperties,false);assert.deepEqual(s.required,Object.keys(s.properties));Object.values(s.properties).forEach(walk)}if(s.items)walk(s.items)};walk(researchOutputSchema)});
test('OAI20 Environment example has no key and secret files are ignored',async()=>{const example=await readFile('.env.example','utf8');assert.match(example,/^OPENAI_API_KEY=$/m);const ignored=execFileSync('git',['check-ignore','.env.local','.env'],{encoding:'utf8'});assert.match(ignored,/\.env.local/);const server=await readFile('src/server/index.js','utf8');assert(!server.includes('OpenAIResearchProvider'));assert(!server.includes('OPENAI_API_KEY'))});
function storedInput(){
 const input={topic:'Confirmed offline fixture',business_id:'business',content_job_id:'job',content_format:'SHORT',workflow_version:'phase-2a.1',research_policy_snapshot:genericPolicy,research_policy_content_hash:hash(genericPolicy),research_policy_reference:genericPolicy.id,research_policy_version:genericPolicy.version};
 const detail={job:{current_state:'RESEARCH_PENDING',format:'SHORT',workflow_version:'phase-2a.1',content_item_id:'real-content'},research:[],evidence:[{evidence_id:'input-id',evidence_type:'confirmed_research_input',content_hash:hash(input),payload:{input,canonical_input_hash:hash(input),canonical_input_representation:canonical(input)}}]};
 return {detail,store:{getJob:async()=>structuredClone(detail)}};
}
test('OAI21 Read-only preparation pins complete stored input and versions',async()=>{const f=storedInput(),p=await prepareSingleOpenAIResearch({store:f.store,business_id:'business',content_job_id:'job'});assert.equal(p.confirmed_input_hash,hash(f.detail.evidence[0].payload.input));assert.equal(p.canonical_input_hash,hash(p.request));assert.equal(p.policy_version,'1.0');assert.equal(f.detail.job.current_state,'RESEARCH_PENDING');assert.equal(f.detail.research.length,0)});
test('OAI22 Corrupt saved input or existing live attempt blocks preparation',async()=>{const f=storedInput();f.detail.evidence[0].payload.input.topic='changed';await assert.rejects(prepareSingleOpenAIResearch({store:f.store,business_id:'business',content_job_id:'job'}),/HASH_MISMATCH/);const g=storedInput();g.detail.research=[{provider:'openai'}];await assert.rejects(prepareSingleOpenAIResearch({store:g.store,business_id:'business',content_job_id:'job'}),/ALREADY_EXISTS/)});
test('OAI23 Missing key or approval cannot start prepared execution',async()=>{const f=storedInput();await assert.rejects(runSinglePreparedResearch({store:f.store,business_id:'business',content_job_id:'job'}),/OPENAI_API_KEY_MISSING|EXPLICIT_LIVE_APPROVAL_REQUIRED/);assert.equal(f.detail.research.length,0)});

test('OAI24 Explicit attempt authorization preserves descriptor and permits only that attempt once',async()=>{
 const first=await fixture(),retry=await fixture({authorizedAttempt:2});
 assert.deepEqual(first.provider.describe(),retry.provider.describe());
 for(const attempt of [1,3])await assert.rejects(retry.provider.execute(retry.request,{...retry.context,attempt}),/LIVE_RETRY_REQUIRES_RECONCILIATION/);
 await retry.provider.execute(retry.request,{...retry.context,attempt:2});
 await assert.rejects(retry.provider.execute(retry.request,{...retry.context,attempt:2}),/ALREADY_CONSUMED/);
 assert.equal(retry.calls.length,1);
});
test('OAI25 Explicit retry still requires a dispatch permit',async()=>{const f=await fixture({authorizedAttempt:2,authorizeDispatch:async()=>null});await assert.rejects(f.provider.execute(f.request,{...f.context,attempt:2}),/LIVE_DISPATCH_NOT_AUTHORIZED/);assert.equal(f.calls.length,0)});
