import {openAIResearchConfig} from '../src/config/openai-research.js';
import {adapterFixture} from './fixtures/openai-response.js';
import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {PostgresStore} from '../src/persistence-postgres.js';
import {ResearchRepository} from '../src/research-postgres.js';
import {ResearchService} from '../src/application/research-service.js';
import {OpenAIResearchProvider} from '../src/providers/openai-research.js';
import {LocalResearchProvider,LocalFactGuardProvider} from '../src/providers/local.js';
import {prepareSingleOpenAIResearch} from '../src/application/openai-research-connection.js';
import {researchPrompt,genericPolicy} from '../src/config/research.js';
import {hash,canonical} from '../src/domain/research.js';
import {migrate} from '../scripts/migrate.mjs';
const base=process.env.TEST_DATABASE_URL;if(!base)throw Error('TEST_DATABASE_URL_REQUIRED');const url=new URL(base);if(!['127.0.0.1','localhost'].includes(url.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');
const name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});
after(async()=>{await db?.close();if(admin){await admin.query('DROP DATABASE IF EXISTS '+name+' WITH (FORCE)');await admin.end()}});
async function fixture(){
 const business_id='adapter-test-'+randomUUID();await db.seed({id:business_id,tenant_id:business_id,name:'Offline adapter integration fixture',brand:{}});
 let job=await db.createJob({business_id,format:'SHORT',content_item_id:'offline-adapter-contract',idempotency_key:randomUUID(),workflow_version:'phase-2a.1'});
 const input={topic:'Offline synthetic integration fixture',business_id,content_job_id:job.id,content_format:'SHORT',workflow_version:job.workflow_version,research_policy_snapshot:genericPolicy,research_policy_content_hash:hash(genericPolicy),research_policy_reference:genericPolicy.id,research_policy_version:genericPolicy.version};
 await db.addEvidence({business_id,content_job_id:job.id,evidence_type:'confirmed_research_input',reference:'offline:'+job.id,content_hash:hash(input),payload:{input,canonical_input_hash:hash(input),canonical_input_representation:canonical(input)}});
 for(const to of ['DISCOVERY_COMPLETE','RESEARCH_PENDING'])job=await db.transition(job.id,job.state_version,to,{business_id});
 return {business_id,job,input};
}
test('OAI DB preparation reads persisted input without creating a run',async()=>{const f=await fixture(),before=await db.getJob(f.job.id,f.business_id);const p=await prepareSingleOpenAIResearch({store:db,business_id:f.business_id,content_job_id:f.job.id});assert.equal(p.confirmed_input_hash,hash(f.input));assert.equal(p.canonical_input_hash,hash(p.request));assert.deepEqual(await db.getJob(f.job.id,f.business_id),before)});
test('OAI DB canonical adapter output persists safely and changed input conflicts',async()=>{
 const f=await fixture(),sentinel='offline-integration-credential-sentinel';let calls=0;
 const output=(await new LocalResearchProvider().execute({input:{topic:'Offline fixture'}},{attempt:1,run_id:'fixture'})).output;
 const provider=new OpenAIResearchProvider({credential:()=>sentinel,transport:async()=>{calls++;return new Response(JSON.stringify({id:'resp_fixture',status:'completed',model:'gpt-5.6-sol',output:[{type:'web_search_call',status:'completed',action:{sources:output.sources.map(s=>({url:s.url}))}},{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(output)}]}]}),{headers:{'x-request-id':'req_fixture'}})},authorizeDispatch:async(request,context)=>{const d=await db.getJob(f.job.id,f.business_id),r=d.research.find(x=>x.run_id===context.run_id);assert.equal(r.status,'RUNNING');return {run_id:r.run_id,idempotency_key:r.idempotency_key,canonical_input_hash:r.canonical_input_hash,business_id:f.business_id,content_job_id:f.job.id,prompt_version:r.prompt_version,policy_version:r.policy_version,workflow_version:r.workflow_version,provider_config_hash:hash(r.request.provider)}}});
 const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const command={business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'offline-single',input:f.input};
 const r=await service.run(command);assert.equal(r.status,'SUCCEEDED');assert.equal(r.provider,'openai');assert.equal(r.metadata.provider_request_id,'req_fixture');assert.equal(r.metadata.usage.tool_usage.web_search_calls,1);const d=await db.getJob(f.job.id,f.business_id);assert.equal(d.factGuard.length,0);assert(!JSON.stringify(d).includes(sentinel));assert.equal((await service.run(command)).run_id,r.run_id);await assert.rejects(service.run({...command,input:{...f.input,topic:'Changed'}}),/IDEMPOTENCY_CONFLICT/);assert.equal(calls,1);
});

test('OAI DB explicit retry preserves failed attempt and request hash with one mock dispatch',async()=>{
 const f=await fixture();let calls=0;
 const out=(await new LocalResearchProvider().execute({input:{topic:'Offline fixture'}},{attempt:1,run_id:'fixture'})).output;
 const permit=async(request,ctx)=>{const d=await db.getJob(f.job.id,f.business_id),r=d.research.find(x=>x.run_id===ctx.run_id);assert.equal(r.status,'RUNNING');assert.equal(r.attempt,ctx.attempt);return {run_id:r.run_id,idempotency_key:r.idempotency_key,canonical_input_hash:r.canonical_input_hash,business_id:f.business_id,content_job_id:f.job.id,prompt_version:r.prompt_version,policy_version:r.policy_version,workflow_version:r.workflow_version,provider_config_hash:hash(request.provider)}};
 const make=(attempt,transport)=>new OpenAIResearchProvider({authorizedAttempt:attempt,credential:()=> 'offline-retry-sentinel',transport,authorizeDispatch:permit});
 const first=make(1,async()=>new Response('',{status:429}));
 const service=p=>new ResearchService({repository:new ResearchRepository(db),researchProvider:p,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const command={business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'retry-contract',input:f.input};
 const failed=await service(first).run(command),snapshot=JSON.stringify(failed);assert.equal(failed.status,'FAILED');
 const second=make(2,async()=>{calls++;return new Response(JSON.stringify({id:'resp_retry',status:'completed',model:'gpt-5.6-sol',output:[{type:'web_search_call',status:'completed',action:{sources:out.sources.map(s=>({url:s.url}))}},{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(out)}]}]}))});
 const retryService=service(second),result=await retryService.run({...command,retry:true});
 assert.equal(result.status,'SUCCEEDED');assert.equal(result.attempt,2);assert.notEqual(result.run_id,failed.run_id);assert.equal(result.canonical_input_hash,failed.canonical_input_hash);assert.equal(result.operation_id,failed.operation_id);
 const d=await db.getJob(f.job.id,f.business_id);assert.equal(JSON.stringify(d.research.find(r=>r.run_id===failed.run_id)),snapshot);assert.equal(d.factGuard.length,0);assert.equal(d.job.current_state,'RESEARCH_COMPLETE');
 assert.equal((await retryService.run({...command,retry:true})).run_id,result.run_id);assert.equal(calls,1);
});

for(const [label,mutate,stage] of [
 ['malformed JSON',e=>e.output.at(-1).content[0].text='{broken','E_STRUCTURED_JSON'],
 ['incomplete response',e=>{e.status='incomplete';e.incomplete_details={reason:'max_output_tokens'}},'B_COMPLETION_STATUS'],
 ['schema mismatch',e=>e.output.at(-1).content[0].text='{}','F_SCHEMA_VALIDATION']
])test('DIAG DB '+label+' retains safe usage after restart and isolates tenant',async()=>{
 const f=await fixture(),a=await adapterFixture(mutate);
 const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'diagnostic',input:f.input});
 assert.equal(r.status,'FAILED');assert.equal(r.output,null);assert.equal(r.metadata.diagnostics.parser_stage,stage);assert.equal(r.metadata.diagnostics.http_status,200);assert.equal(r.metadata.usage.total_tokens,1801);assert.equal(r.metadata.provider_request_id,'req_diagnostic_fixture');assert.equal(a.calls(),1);
 const reopened=new PostgresStore(url.href);try{const d=await reopened.getJob(f.job.id,f.business_id);assert.equal(d.job.current_state,'FAILED');assert.deepEqual(d.research[0].metadata,r.metadata);assert.equal(d.factGuard.length,0);assert.equal(await reopened.getJob(f.job.id,'wrong-business'),null);assert(!JSON.stringify(d).includes('PRIVATE_REASONING_FIXTURE'));}finally{await reopened.close()}
 for(const table of ['research_claims','research_sources','research_claim_evidence'])assert.equal(Number((await db.pool.query('SELECT count(*) n FROM '+table+' WHERE run_id=$1',[r.run_id])).rows[0].n),0);
});
test('DIAG DB persistence failure retains received usage and diagnostics',async()=>{
 const f=await fixture(),a=await adapterFixture();
 const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 await db.pool.query("CREATE FUNCTION fail_diagnostic_output() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='SUCCEEDED' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_diagnostic_output BEFORE INSERT ON research_outcomes FOR EACH ROW EXECUTE FUNCTION fail_diagnostic_output()");
 try{const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'db-diagnostic',input:f.input});assert.equal(r.error_category,'PERSISTENCE_FAILURE');assert.equal(r.metadata.diagnostics.parser_stage,'I_PERSISTENCE');assert.equal(r.metadata.usage.total_tokens,1801);assert.equal(r.metadata.provider_request_id,'req_diagnostic_fixture');assert.equal((await db.getJob(f.job.id,f.business_id)).job.current_state,'FAILED');assert.equal(a.calls(),1);}finally{await db.pool.query('DROP TRIGGER fail_diagnostic_output ON research_outcomes; DROP FUNCTION fail_diagnostic_output()')}
});
test('DIAG DB arbitrary provider exception cannot persist message or forged metadata',async()=>{
 const f=await fixture(),a=await adapterFixture();a.provider.execute=async()=>{const e=Error('PRIVATE_EXCEPTION');e.metadata={diagnostics:{exception_message:'PRIVATE_EXCEPTION'}};throw e;};
 const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'unknown-error',input:f.input});assert.equal(r.error_category,'PROVIDER_FAILURE');assert.equal(r.metadata.diagnostics.parser_stage,'UNKNOWN_PROVIDER_EXCEPTION');assert(!JSON.stringify(r).includes('PRIVATE_EXCEPTION'));
});

test('BUDGET DB incomplete 16000 profile persists failure diagnostics and no partial research',async()=>{
 const f=await fixture(),a=await adapterFixture(e=>{e.status='incomplete';e.incomplete_details={reason:'max_output_tokens'}},{config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'})});
 const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'budget-failure',input:f.input});
 const d=await db.getJob(f.job.id,f.business_id);assert.equal(r.status,'FAILED');assert.equal(d.job.current_state,'FAILED');assert.equal(r.output,null);assert.equal(r.request.provider.configuration.max_output_tokens,16000);assert.equal(r.metadata.diagnostics.incomplete_reason,'max_output_tokens');assert.equal(r.metadata.usage.reasoning_tokens,200);assert.equal(a.calls(),1);assert.equal(d.factGuard.length,0);
 for(const table of ['research_sources','research_claims','research_claim_evidence'])assert.equal(Number((await db.pool.query('SELECT count(*) n FROM '+table+' WHERE run_id=$1',[r.run_id])).rows[0].n),0);
});
test('BUDGET DB changed profile cannot bypass existing operation hash on retry',async()=>{
 const f=await fixture(),first=await adapterFixture(e=>{e.status='incomplete';e.incomplete_details={reason:'max_output_tokens'}});
 const service=p=>new ResearchService({repository:new ResearchRepository(db),researchProvider:p,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const command={business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'pinned-budget',input:f.input};await service(first.provider).run(command);const before=await db.getJob(f.job.id,f.business_id);
 const next=await adapterFixture(()=>{},{config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'}),authorizedAttempt:2});await assert.rejects(service(next.provider).run({...command,retry:true}),/IDEMPOTENCY_CONFLICT/);assert.equal(next.calls(),0);assert.deepEqual(await db.getJob(f.job.id,f.business_id),before);
});

test('TOOL DB budget failure persists counts and configured limit after restart',async()=>{const f=await fixture(),a=await adapterFixture(e=>{const item=e.output.find(x=>x.type==='web_search_call');e.output.unshift(...Array.from({length:8},(_,i)=>({...structuredClone(item),id:'extra_'+i})))},{config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'})});const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'tool-budget',input:f.input});assert.equal(r.status,'FAILED');assert.equal(r.output,null);assert.equal(r.metadata.diagnostics.exception_message,'TOOL_BUDGET_EXCEEDED');assert.equal(a.calls(),1);const reopened=new PostgresStore(url.href);try{const d=await reopened.getJob(f.job.id,f.business_id);assert.deepEqual(d.research[0].metadata,r.metadata);assert.equal(d.research[0].metadata.diagnostics.tool_budget_limit,8);assert.equal(d.research[0].metadata.diagnostics.observed_web_search_calls,9);assert.equal(d.job.current_state,'FAILED');assert.equal(d.factGuard.length,0)}finally{await reopened.close()}});

test('SEM DB completed and extra incomplete diagnostics persist after restart without profile change',async()=>{const f=await fixture(),a=await adapterFixture(e=>{const item=e.output.find(x=>x.type==='web_search_call');e.output.unshift(...Array.from({length:8},(_,i)=>({...structuredClone(item),id:'ws_extra_'+i,status:i===0?'incomplete':'completed'})));},{config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'})});const service=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'semantics',input:f.input});assert.equal(r.status,'SUCCEEDED');assert.equal(a.calls(),1);assert.equal(r.request.provider.configuration.profile_version,'1.1');const reopened=new PostgresStore(url.href);try{const d=await reopened.getJob(f.job.id,f.business_id),m=d.research[0].metadata.diagnostics;assert.deepEqual(d.research[0].metadata,r.metadata);assert.equal(m.web_search_count_by_status.incomplete,1);assert.equal(m.completed_web_search_calls,8);assert.equal(m.web_search_items.length,9);assert.equal(m.adapter_processing_version,'responses-research-processing/1.2');assert.equal(m.parser_revision,'responses-parser/2.3');assert.equal(m.validator_version,'completed-tool-budget/1.0');assert.equal(d.job.current_state,'RESEARCH_COMPLETE');assert.equal(d.factGuard.length,0)}finally{await reopened.close()}});

for(const [label,mutate] of [['parser',e=>e.output.at(-1).content[0].text='{broken'],['schema',e=>e.output.at(-1).content[0].text='{}'],['success',()=>{}]])test('REC DB '+label+' artifact persists independently and offline check leaves history immutable',async()=>{const {reprocessStoredResponse}=await import('../src/providers/openai-recovery.js');const f=await fixture(),a=await adapterFixture(mutate),repository=new ResearchRepository(db);const service=new ResearchService({repository,researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const run=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'recovery',input:f.input});const before=await db.getJob(f.job.id,f.business_id);const saved=await repository.loadProviderResponse(f.business_id,f.job.id,run.run_id);assert.equal(saved.payload.request_hash,run.canonical_input_hash);assert.equal(saved.payload.run_id,run.run_id);assert(!JSON.stringify(saved).includes('PRIVATE_REASONING_FIXTURE'));assert.equal(saved.payload.response.usage.total_tokens,1801);assert.equal(saved.payload.response.output.filter(x=>x.type==='web_search_call').length,1);const reopened=new PostgresStore(url.href);try{const r=await reprocessStoredResponse(new ResearchRepository(reopened),{business_id:f.business_id,content_job_id:f.job.id,run_id:run.run_id});assert.equal(r.success,label==='success');assert.deepEqual(await reopened.getJob(f.job.id,f.business_id),before);await assert.rejects(new ResearchRepository(reopened).loadProviderResponse('wrong-business',f.job.id,run.run_id),/NOT_VERIFIED/);await assert.rejects(reopened.pool.query('UPDATE evidence_records SET payload=$1 WHERE id=$2',[{},saved.id]),e=>e.code==='23514');}finally{await reopened.close()}assert.equal(a.calls(),1)});
test('REC DB capture failure persists FAILED and never Research complete',async()=>{const f=await fixture(),a=await adapterFixture(),repository=new ResearchRepository(db);repository.captureProviderResponse=async()=>{throw Error('storage unavailable')};const service=new ResearchService({repository,researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'capture-failure',input:f.input});assert.equal(r.status,'FAILED');assert.equal(r.output,null);assert.equal(r.metadata.diagnostics.exception_message,'RESPONSE_ARTIFACT_PERSISTENCE_FAILED');assert.equal((await db.getJob(f.job.id,f.business_id)).job.current_state,'FAILED');assert.equal(a.calls(),1)});
test('REC DB result persistence failure preserves earlier response capture',async()=>{const f=await fixture(),a=await adapterFixture(),repository=new ResearchRepository(db),finish=repository.finish.bind(repository);repository.finish=async(...args)=>{if(args[5])throw Error('forced result failure');return finish(...args)};const service=new ResearchService({repository,researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const r=await service.run({business_id:f.business_id,content_job_id:f.job.id,operation:'research',idempotency_key:'result-failure',input:f.input});assert.equal(r.status,'FAILED');assert.equal(r.error_category,'PERSISTENCE_FAILURE');assert(await repository.loadProviderResponse(f.business_id,f.job.id,r.run_id));assert.equal(a.calls(),1)});
