import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {PostgresStore} from '../src/persistence-postgres.js';
import {ResearchRepository} from '../src/research-postgres.js';
import {ResearchService} from '../src/application/research-service.js';
import {LocalResearchProvider,LocalFactGuardProvider} from '../src/providers/local.js';
import {researchPrompt,genericPolicy} from '../src/config/research.js';
import {openAIResearchConfig} from '../src/config/openai-research.js';
import {OpenAIResearchProvider} from '../src/providers/openai-research.js';
import {hash} from '../src/domain/research.js';
import {migrate} from '../scripts/migrate.mjs';
const base=process.env.TEST_DATABASE_URL;if(!base)throw Error('TEST_DATABASE_URL_REQUIRED');const url=new URL(base);if(!['localhost','127.0.0.1'].includes(url.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');
const name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});
after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
async function fixture(mode='provider_failure'){
 const business_id='lineage-'+randomUUID();await db.seed({id:business_id,tenant_id:business_id,name:'Synthetic lineage fixture',brand:{}});
 let job=await db.createJob({business_id,format:'SHORT',idempotency_key:randomUUID(),content_item_id:'synthetic:lineage',workflow_version:'phase-2a.1'});
 for(const to of ['DISCOVERY_COMPLETE','RESEARCH_PENDING'])job=await db.transition(job.id,job.state_version,to,{business_id});
 const provider=new LocalResearchProvider(mode),original=provider.describe.bind(provider);let budget=6000;
 provider.describe=()=>({...original(),configuration:{...original().configuration,max_output_tokens:budget,reasoning_effort:'medium'}});
 const repository=new ResearchRepository(db),service=new ResearchService({repository,researchProvider:provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const command={business_id,content_job_id:job.id,operation:'research',idempotency_key:'original',input:{topic:'Synthetic unchanged research',core_research_question:'What does the fixture establish?'}};
 return {business_id,job,provider,repository,service,command,budget:n=>budget=n,run:(extra={})=>service.run({...command,...extra}),revision:(previous_run_id,extra={})=>service.retryResearchRunWithRevision({...command,previous_run_id,reason:'Explicit technical budget revision',explicit_retry:true,...extra})};
}
const detail=f=>db.getJob(f.job.id,f.business_id);
test('LINEAGE01 Same request explicit retry retains revision and increases attempt',async()=>{const f=await fixture(),a=await f.run(),b=await f.run({retry:true});assert.equal(b.attempt,2);assert.equal(b.execution_revision,1);assert.equal(b.lineage_id,a.lineage_id);assert.equal(b.canonical_input_hash,a.canonical_input_hash)});
test('LINEAGE02 Three failures then revision produces attempt four in same lineage',async()=>{const f=await fixture();const old=[await f.run(),await f.run({retry:true}),await f.run({retry:true})];f.budget(16000);const before=await detail(f);const p=await f.service.prepareResearchRunRevision({...f.command,previous_run_id:old[2].run_id,reason:'Larger budget',explicit_retry:true});assert.equal(p.attempt_number,4);assert.equal(p.execution_revision,2);assert.equal(p.logical_input_hash,hash(f.command.input));assert.deepEqual(await detail(f),before);const r=await f.revision(old[2].run_id);assert.equal(r.attempt,4);assert.equal(r.execution_revision,2);assert.equal(r.lineage_id,old[0].lineage_id);assert.notEqual(r.idempotency_key,old[0].idempotency_key);assert.notEqual(r.canonical_input_hash,old[0].canonical_input_hash);assert.deepEqual((await detail(f)).research.slice(0,3),old)});
test('LINEAGE03 Normal new key cannot reset numbering',async()=>{const f=await fixture();await f.run();const before=await detail(f);await assert.rejects(f.run({retry:true,idempotency_key:'new-key'}),/EXPLICIT_REVISION_REQUIRED/);assert.deepEqual(await detail(f),before);assert.equal(f.provider.calls,1)});
test('LINEAGE04 Same key changed execution remains idempotency conflict',async()=>{const f=await fixture();await f.run();f.budget(16000);await assert.rejects(f.run({retry:true}),/IDEMPOTENCY_CONFLICT/);assert.equal(f.provider.calls,1)});
test('LINEAGE05 Changed topic or core question cannot become technical revision',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);for(const input of [{...f.command.input,topic:'Changed'},{...f.command.input,core_research_question:'Changed'}])await assert.rejects(f.revision(a.run_id,{input}),/LOGICAL_RESEARCH_INPUT_CHANGED/);assert.equal(f.provider.calls,1)});
test('LINEAGE06 Concurrent explicit revisions cannot consume the same previous attempt twice',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);const results=await Promise.allSettled([f.revision(a.run_id),f.revision(a.run_id)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected'&&/STALE_RESEARCH_REVISION/.test(x.reason.message)).length,1);const d=await detail(f);assert.deepEqual(d.research.map(x=>x.attempt),[1,2]);assert.equal(f.provider.calls,2)});
test('LINEAGE07 Historical runs outcomes and lineage mappings reject mutation',async()=>{const f=await fixture(),a=await f.run();for(const [table,column,value] of [['research_attempts','run_id',a.run_id],['research_outcomes','run_id',a.run_id],['research_lineages','lineage_id',a.lineage_id],['research_execution_revisions','operation_id',a.operation_id],['research_attempt_lineage','run_id',a.run_id]])await assert.rejects(db.pool.query('DELETE FROM '+table+' WHERE '+column+'=$1',[value]),e=>e.code==='23514');});
test('LINEAGE08 Cross tenant and cross job revision rejected',async()=>{const a=await fixture(),r=await a.run(),b=await fixture();await b.run();b.budget(16000);await assert.rejects(b.revision(r.run_id),/PREVIOUS_RESEARCH_NOT_FOUND/);await assert.rejects(a.revision(r.run_id,{business_id:b.business_id}),/JOB_NOT_FOUND/);assert.equal(a.provider.calls,1);assert.equal(b.provider.calls,1)});
test('LINEAGE09 Revision audit contains lineage hashes fields reason and timestamp',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);const r=await f.revision(a.run_id),d=await detail(f),t=d.stateHistory.find(x=>x.run_id===r.run_id&&x.to_state==='RESEARCH_RUNNING');assert.equal(t.metadata.previous_run_id,a.run_id);assert.equal(t.metadata.new_run_id,r.run_id);assert.equal(t.metadata.lineage_id,a.lineage_id);assert.equal(t.metadata.attempt_number,2);assert.equal(t.metadata.execution_revision,2);assert.equal(t.metadata.old_request_hash,a.canonical_input_hash);assert.equal(t.metadata.new_request_hash,r.canonical_input_hash);assert(t.metadata.changed_execution_fields.includes('provider.configuration.max_output_tokens'));assert.equal(t.metadata.revision_reason,'Explicit technical budget revision');assert(t.occurred_at)});
test('LINEAGE10 Restart retains lineage and revised execution',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);await f.revision(a.run_id);const before=await detail(f),restarted=new PostgresStore(url.href);try{assert.deepEqual(await restarted.getJob(f.job.id,f.business_id),before)}finally{await restarted.close()}});
test('LINEAGE11 Explicit retry required and successful attempt cannot be revised',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);await assert.rejects(f.revision(a.run_id,{explicit_retry:false}),/EXPLICIT_REVISION_REQUIRED/);const g=await fixture('success'),r=await g.run();g.budget(16000);await assert.rejects(g.revision(r.run_id),/PREVIOUS_RESEARCH_NOT_FAILED/);assert.equal(g.provider.calls,1)});
test('LINEAGE12 Database rejects duplicate or reset attempt number independently',async()=>{const f=await fixture(),a=await f.run();for(const attempt of [1,3])await assert.rejects(db.pool.query('INSERT INTO research_attempts(run_id,business_id,content_job_id,operation_id,attempt) VALUES($1,$2,$3,$4,$5)',[randomUUID(),f.business_id,f.job.id,a.operation_id,attempt]),e=>['23505','23514'].includes(e.code));assert.equal((await detail(f)).research.length,1)});
test('LINEAGE13 New provider profile prepares four without dispatch or mutation',async()=>{const f=await fixture();await f.run();await f.run({retry:true});const r=await f.run({retry:true}),before=await detail(f);let calls=0;const provider=new OpenAIResearchProvider({config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'}),credential:()=>'',transport:async()=>{calls++;throw Error('LIVE_FORBIDDEN')}});f.service.researchProvider=provider;const p=await f.service.prepareResearchRunRevision({...f.command,previous_run_id:r.run_id,reason:'Approved configuration preparation only',explicit_retry:true});assert.equal(p.attempt_number,4);assert.equal(p.request.provider.configuration.max_output_tokens,16000);assert.equal(p.request.provider.configuration.reasoning_effort,'medium');assert.equal(p.request.provider.model,'gpt-5.6-sol');assert.equal(calls,0);assert.deepEqual(await detail(f),before)});
test('LINEAGE14 Identical execution uses ordinary retry not a new revision',async()=>{const f=await fixture(),a=await f.run();await assert.rejects(f.revision(a.run_id),/EXECUTION_REVISION_UNCHANGED/);assert.equal(f.provider.calls,1)});

test('LINEAGE15 Ordinary retry in new revision continues global sequence and old key is stale',async()=>{const f=await fixture(),a=await f.run();f.budget(16000);const b=await f.revision(a.run_id);const c=await f.run({idempotency_key:b.idempotency_key,retry:true});assert.equal(c.attempt,3);assert.equal(c.execution_revision,2);assert.equal(c.lineage_id,a.lineage_id);f.budget(6000);await assert.rejects(f.run({retry:true}),/STALE_RESEARCH_REVISION/);assert.equal(f.provider.calls,3)});
async function legacyDatabase(){
 const name='abo_test_'+randomUUID().replaceAll('-','');await admin.query('CREATE DATABASE '+name);const u=new URL(base);u.pathname='/'+name;const store=new PostgresStore(u.href);
 for(const file of ['001_control_plane.sql','002_evidence_artifact_boundaries.sql','003_research_fact_guard.sql'])await store.pool.query(await readFile(new URL('../db/migrations/'+file,import.meta.url),'utf8'));
 await store.pool.query('CREATE TABLE schema_migrations(name text PRIMARY KEY)');for(const f of ['001_control_plane.sql','002_evidence_artifact_boundaries.sql','003_research_fact_guard.sql'])await store.pool.query('INSERT INTO schema_migrations VALUES($1)',[f]);
 const b='legacy-'+randomUUID();await store.seed({id:b,tenant_id:b,name:'Legacy synthetic fixture',brand:{}});let j=await store.createJob({business_id:b,format:'SHORT',idempotency_key:'legacy',workflow_version:'phase-2a.1'});for(const to of ['DISCOVERY_COMPLETE','RESEARCH_PENDING'])j=await store.transition(j.id,j.state_version,to,{business_id:b});
 const op=randomUUID(),provider=new LocalResearchProvider('provider_failure'),request={business_id:b,content_job_id:j.id,operation:'research',input:{topic:'Legacy synthetic unchanged input'},workflow_version:'phase-2a.1',prompt:researchPrompt,policy:genericPolicy,provider:provider.describe()};
 await store.pool.query("INSERT INTO research_operations(id,business_id,content_job_id,operation,idempotency_key,canonical_input_hash,request) VALUES($1,$2,$3,'research','legacy',$4,$5)",[op,b,j.id,hash(request),request]);
 let last;
 for(let attempt=1;attempt<=3;attempt++){
  if(attempt>1)j=await store.transition(j.id,j.state_version,'RESEARCH_PENDING',{business_id:b});last=randomUUID();
  await store.pool.query('INSERT INTO research_attempts(run_id,business_id,content_job_id,operation_id,attempt) VALUES($1,$2,$3,$4,$5)',[last,b,j.id,op,attempt]);
  j=await store.transition(j.id,j.state_version,'RESEARCH_RUNNING',{business_id:b,run_id:last});
  await store.pool.query("INSERT INTO research_outcomes(run_id,business_id,content_job_id,operation_id,status,metadata,error_category) VALUES($1,$2,$3,$4,'FAILED',$5,'PROVIDER_FAILURE')",[last,b,j.id,op,{synthetic:true}]);j=await store.transition(j.id,j.state_version,'FAILED',{business_id:b,run_id:last});
 }
 const snapshot=async()=>{const data={};for(const t of ['research_operations','research_attempts','research_outcomes','content_jobs','job_state_transitions'])data[t]=(await store.pool.query('SELECT to_jsonb(t) data FROM '+t+' t ORDER BY to_jsonb(t)::text')).rows;return data};
 return {store,b,j,op,request,last,snapshot,close:async()=>{await store.close();await admin.query('DROP DATABASE '+name)}};
}
test('LINEAGE16 Migration adds mappings to old three-attempt history without rewriting rows',async()=>{
 const f=await legacyDatabase();try{const before=await f.snapshot();await migrate(f.store.pool);await migrate(f.store.pool);for(const row of before.research_operations)row.data.research_processing_revision_id=null;assert.deepEqual(await f.snapshot(),before);const d=await f.store.getJob(f.j.id,f.b);assert.deepEqual(d.research.map(r=>r.attempt),[1,2,3]);assert(d.research.every(r=>r.lineage_id===f.op&&r.execution_revision===1));
 const provider=new OpenAIResearchProvider({config:openAIResearchConfig({OPENAI_RESEARCH_PROFILE:'arktrov-deep-research'}),credential:()=>'',transport:async()=>{throw Error('LIVE_FORBIDDEN')}});
 const service=new ResearchService({repository:new ResearchRepository(f.store),researchProvider:provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});
 const p=await service.prepareResearchRunRevision({business_id:f.b,content_job_id:f.j.id,input:f.request.input,previous_run_id:f.last,reason:'Offline migration verification',explicit_retry:true});assert.equal(p.attempt_number,4);assert.equal(p.execution_revision,2);assert.equal(p.lineage_id,f.op);assert.deepEqual(await f.snapshot(),before);
 }finally{await f.close()}
});
test('LINEAGE17 Ambiguous old logical inputs fail migration atomically',async()=>{const f=await legacyDatabase();try{const request={...f.request,input:{topic:'Different logical research'}};await f.store.pool.query("INSERT INTO research_operations(id,business_id,content_job_id,operation,idempotency_key,canonical_input_hash,request) VALUES($1,$2,$3,'research','other',$4,$5)",[randomUUID(),f.b,f.j.id,hash(request),request]);const before=await f.snapshot();await assert.rejects(migrate(f.store.pool),/LEGACY_LOGICAL_INPUT_CONFLICT/);assert.deepEqual(await f.snapshot(),before);assert.equal((await f.store.pool.query("SELECT to_regclass('research_lineages') name")).rows[0].name,null)}finally{await f.close()}});

test('TOOL DB fourth failure advances to fifth attempt third revision without changing history',async()=>{const f=await fixture();await f.run();await f.run({retry:true});const third=await f.run({retry:true});f.budget(16000);const fourth=await f.revision(third.run_id);const before=await detail(f);const describe=f.provider.describe.bind(f.provider);f.provider.describe=()=>({...describe(),configuration:{...describe().configuration,max_tool_calls:8}});await assert.rejects(f.service.run({...f.command,idempotency_key:fourth.idempotency_key,retry:true}),/IDEMPOTENCY_CONFLICT/);const command={...f.command,previous_run_id:fourth.run_id,reason:'Explicit tool budget revision',explicit_retry:true};const plan=await f.service.prepareResearchRunRevision(command);assert.equal(plan.attempt_number,5);assert.equal(plan.execution_revision,3);assert.equal(plan.lineage_id,fourth.lineage_id);assert.notEqual(plan.new_request_hash,fourth.canonical_input_hash);assert.notEqual(plan.idempotency_key,fourth.idempotency_key);assert.deepEqual(await detail(f),before);const fifth=await f.service.retryResearchRunWithRevision(command);assert.equal(fifth.attempt,5);assert.equal(fifth.execution_revision,3);assert.deepEqual((await detail(f)).research.slice(0,4),before.research);assert.equal(f.provider.calls,5)});
