import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import pg from 'pg';import {randomUUID} from 'node:crypto';
import {PostgresStore} from '../src/persistence-postgres.js';import {ResearchRepository} from '../src/research-postgres.js';import {ResearchRecoveryRepository} from '../src/research-recovery-postgres.js';import {ResearchService} from '../src/application/research-service.js';import {ResearchRecoveryService} from '../src/application/research-recovery-service.js';import {reprocessResponseArtifact,processingVersions} from '../src/providers/openai-recovery.js';import {ProviderFailure} from '../src/providers/failure.js';import {adapterFixture} from './fixtures/openai-response.js';import {researchPrompt,genericPolicy} from '../src/config/research.js';import {LocalFactGuardProvider} from '../src/providers/local.js';import {validateResearch,hash} from '../src/domain/research.js';import {migrate} from '../scripts/migrate.mjs';
const base=process.env.TEST_DATABASE_URL;if(!base)throw Error('TEST_DATABASE_URL_REQUIRED');const url=new URL(base);if(!['localhost','127.0.0.1'].includes(url.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');const name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
async function fixture(contextOnly=false){const b='recovery-'+randomUUID();await db.seed({id:b,tenant_id:b,name:'Synthetic recovery',brand:{}});let j=await db.createJob({business_id:b,format:'SHORT',idempotency_key:'job',workflow_version:'phase-2a.1'});for(const to of ['DISCOVERY_COMPLETE','RESEARCH_PENDING'])j=await db.transition(j.id,j.state_version,to,{business_id:b});const f=await adapterFixture((e,o)=>{o.evidence.push({...o.evidence[0],support_type:'context',evidence_reference:'Independent synthetic qualification'});if(contextOnly)o.evidence.forEach(e=>e.support_type='context');if(contextOnly==='mixed'){o.claims.push({...o.claims[0],claim_id:'SAFE-2'});o.evidence.push({...o.evidence[0],claim_id:'SAFE-2',support_type:'supports'})}e.output.at(-1).content[0].text=JSON.stringify(o)});const provider={describe:()=>f.provider.describe(),execute:async(r,c)=>{const value=await f.provider.execute(r,c);throw new ProviderFailure('OPENAI_INVALID_RESEARCH_RESULT','PARSING_FAILURE',{...value.metadata,diagnostics:{...value.metadata.diagnostics,parser_stage:'H_CLAIM_EVIDENCE_VALIDATION',validation_rule:'domain_contract',parser_revision:'responses-parser/2.2'}})}};const s=new ResearchService({repository:new ResearchRepository(db),researchProvider:provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const run=await s.run({business_id:b,content_job_id:j.id,operation:'research',idempotency_key:'paid',input:{topic:'Synthetic independent evidence relations'}});const repo=new ResearchRecoveryRepository(db),a=await repo.loadProviderResponse(b,j.id,run.run_id);const command={business_id:b,content_job_id:j.id,original_run_id:run.run_id,artifact_id:a.id,artifact_hash:a.content_hash,reason:'Offline correction of pair-only evidence identity',explicit_recovery:true};const service=new ResearchRecoveryService({repository:repo,processArtifact:reprocessResponseArtifact,versions:processingVersions});return {b,j,run,repo,a,command,service,f}}
const rows=(table,f,id)=>db.pool.query('SELECT * FROM '+table+' WHERE business_id=$1 AND content_job_id=$2'+(id?' AND processing_id=$3':''),id?[f.b,f.j.id,id]:[f.b,f.j.id]);
test('PROC01 old pair-only failure reproduced and distinct evidence preserved',async()=>{const f=await fixture(),r=reprocessResponseArtifact(f.a);assert(r.success);const pairs=r.output.evidence.map(e=>e.claim_id+'|'+e.source_id);assert(new Set(pairs).size<pairs.length);assert.equal(validateResearch(r.output),r.output);assert.throws(()=>validateResearch({...r.output,evidence:[...r.output.evidence,r.output.evidence[0]]}));assert.equal(f.run.status,'FAILED')});
test('PROC02 recovery creates separate revision sources claims relations and atomic completion',async()=>{const f=await fixture(),before=await db.getJob(f.j.id,f.b),r=await f.service.recover(f.command),after=await db.getJob(f.j.id,f.b);assert.equal(r.provider_call_executed,false);assert.equal(r.original_run_id,f.run.run_id);assert.equal(r.revision,1);assert.equal(r.artifact_id,f.a.id);assert.equal(r.output_hash,hash(r.output));assert.equal(after.job.current_state,'RESEARCH_COMPLETE');assert.deepEqual(after.research,before.research);assert.equal(after.research.length,1);assert.equal(after.factGuard.length,0);assert.equal(f.f.calls(),1);for(const [table,key] of [['recovered_research_sources','sources'],['recovered_research_claims','claims'],['recovered_research_evidence','evidence']])assert.equal((await rows(table,f,r.id)).rowCount,r.output[key].length);assert.deepEqual(r.versions,processingVersions);assert(after.stateHistory.some(e=>e.metadata.processing_revision_id===r.id&&e.to_state==='RESEARCH_COMPLETE'&&e.metadata.provider_call_executed===false))});
test('PROC03 invalid result rejected without state or persistence changes',async()=>{const f=await fixture(),before=await db.getJob(f.j.id,f.b);f.service.processArtifact=()=>({success:true,output:{},output_hash:hash({})});await assert.rejects(f.service.recover(f.command));assert.deepEqual(await db.getJob(f.j.id,f.b),before);assert.equal((await rows('research_processing_revisions',f)).rowCount,0)});
test('PROC04 cross tenant and wrong artifact rejected',async()=>{const f=await fixture();await assert.rejects(f.service.recover({...f.command,business_id:'wrong'}));await assert.rejects(f.service.recover({...f.command,artifact_id:randomUUID()}),/ARTIFACT_MISMATCH/);assert.equal((await rows('research_processing_revisions',f)).rowCount,0)});
test('PROC05 restart and immutable recovery retain failed original',async()=>{const f=await fixture(),r=await f.service.recover(f.command);const reopened=new PostgresStore(url.href);try{const saved=(await reopened.pool.query('SELECT * FROM research_processing_revisions WHERE id=$1',[r.id])).rows[0];assert.deepEqual(saved,r);const d=await reopened.getJob(f.j.id,f.b);assert.equal(d.research[0].status,'FAILED');assert.equal(d.job.current_state,'RESEARCH_COMPLETE');await assert.rejects(reopened.pool.query('UPDATE research_processing_revisions SET reason=$1 WHERE id=$2',['changed',r.id]),e=>e.code==='23514');await assert.rejects(reopened.pool.query('DELETE FROM research_outcomes WHERE run_id=$1',[f.run.run_id]),e=>e.code==='23514')}finally{await reopened.close()}});
test('PROC06 repeated and concurrent recovery is idempotent',async()=>{const f=await fixture(),rs=await Promise.all([f.service.recover(f.command),f.service.recover(f.command)]);assert.equal(rs[0].id,rs[1].id);assert.equal((await rows('research_processing_revisions',f)).rowCount,1);assert.equal(f.f.calls(),1)});
test('PROC07 missing recovered rows prevents complete and rolls entire transaction back',async()=>{const f=await fixture(),before=await db.getJob(f.j.id,f.b),transition=db.transitionInTransaction.bind(db);db.transitionInTransaction=async(c,id,v,to,m)=>{if(id===f.j.id&&to==='RESEARCH_COMPLETE')throw Error('FORCED_PERSISTENCE_FAILURE');return transition(c,id,v,to,m)};try{await assert.rejects(f.service.recover(f.command),/FORCED_PERSISTENCE_FAILURE/)}finally{db.transitionInTransaction=transition}assert.deepEqual(await db.getJob(f.j.id,f.b),before);assert.equal((await rows('research_processing_revisions',f)).rowCount,0);for(const t of ['recovered_research_claims','recovered_research_sources','recovered_research_evidence'])assert.equal((await rows(t,f)).rowCount,0)});
test('PROC08 central state machine rejects fabricated processing proof',async()=>{const f=await fixture();const j=await db.transition(f.j.id,(await db.getJob(f.j.id,f.b)).job.state_version,'RESEARCH_PENDING',{business_id:f.b});await assert.rejects(db.transition(j.id,j.state_version,'RESEARCH_COMPLETE',{business_id:f.b,run_id:f.run.run_id,processing_revision_id:randomUUID()}),/PERSISTED_EVIDENCE_REQUIRED/)});
test('PROC09 explicit authorization and fresh original run required',async()=>{const f=await fixture();await assert.rejects(f.service.recover({...f.command,explicit_recovery:false}),/EXPLICIT_RECOVERY_REQUIRED/);await db.transition(f.j.id,(await db.getJob(f.j.id,f.b)).job.state_version,'RESEARCH_PENDING',{business_id:f.b});await assert.rejects(f.service.recover(f.command),/INVALID_RECOVERY_STATE/)});

test('PROC10 missing recovered relation is detected by central completion guard',async()=>{const f=await fixture();await db.pool.query("CREATE FUNCTION recovery_test_skip() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$");await db.pool.query('CREATE TRIGGER recovery_test_skip BEFORE INSERT ON recovered_research_evidence FOR EACH ROW EXECUTE FUNCTION recovery_test_skip()');try{await assert.rejects(f.service.recover(f.command),/PERSISTED_EVIDENCE_REQUIRED/);assert.equal((await rows('research_processing_revisions',f)).rowCount,0);assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'FAILED')}finally{await db.pool.query('DROP TRIGGER recovery_test_skip ON recovered_research_evidence');await db.pool.query('DROP FUNCTION recovery_test_skip()')}});
test('PROC11 normal Research persistence also preserves multiple evidence records per pair',async()=>{const f=await fixture(),a=await adapterFixture((e,o)=>{o.evidence.push({...o.evidence[0],support_type:'context',evidence_reference:'Second synthetic excerpt'});e.output.at(-1).content[0].text=JSON.stringify(o)},{authorizedAttempt:2});const s=new ResearchService({repository:new ResearchRepository(db),researchProvider:a.provider,factGuardProvider:new LocalFactGuardProvider(),prompts:{research:researchPrompt},policy:genericPolicy});const r=await s.run({business_id:f.b,content_job_id:f.j.id,operation:'research',idempotency_key:'paid',input:f.run.request.input,retry:true});assert.equal(r.status,'SUCCEEDED');assert.equal((await db.pool.query('SELECT * FROM research_claim_evidence WHERE run_id=$1',[r.run_id])).rowCount,r.output.evidence.length)});

import {OfflineFactGuardProvider,offlineFactGuardPrompt} from '../src/providers/offline-fact-guard.js';
async function guardFixture(contextOnly=false){const f=await fixture(contextOnly),r=await f.service.recover(f.command);const payload={decision:'APPROVED_FOR_FACT_GUARD',processing_revision_id:r.id,research_output_hash:r.output_hash,publication_approved:false,known_limitations:['No independent verification']};const e=await db.addEvidence({business_id:f.b,content_job_id:f.j.id,evidence_type:'human_research_approval',reference:'approval:'+r.id,payload,content_hash:hash(payload)});const provider=new OfflineFactGuardProvider();let calls=0;const s=new ResearchService({repository:new ResearchRepository(db),researchProvider:{describe:()=>({provider:'disabled'}),execute:()=>{throw Error('RESEARCH_FORBIDDEN')}},factGuardProvider:{describe:()=>provider.describe(),execute:(...args)=>{calls++;return provider.execute(...args)}},prompts:{fact_guard:offlineFactGuardPrompt},policy:genericPolicy});const cmd={business_id:f.b,content_job_id:f.j.id,operation:'fact_guard',idempotency_key:'guard',input:{research_run_id:f.run.run_id,research_processing_revision_id:r.id,human_approval_evidence_id:e.id}};return {...f,r,e,s,cmd,calls:()=>calls}}
test('FG05 recovered Fact Guard persists decision audit and references and is idempotent after restart',async()=>{const f=await guardFixture(),before=await db.getJob(f.j.id,f.b),r=await f.s.run(f.cmd);assert.equal(r.status,'SUCCEEDED');assert.equal(r.output.decision,'REVIEW_REQUIRED');assert.equal(r.request.input.research_processing_revision_id,f.r.id);assert.equal(r.output_hash,hash(r.output));assert.equal(r.canonical_input_hash,hash(r.request));assert.equal(r.metadata.diagnostics.processing_version,'fact-guard-evidence/2.0');assert.equal((await f.s.run(f.cmd)).run_id,r.run_id);assert.equal(f.calls(),1);const reopened=new PostgresStore(url.href);try{const d=await reopened.getJob(f.j.id,f.b);assert.deepEqual(d.research,before.research);assert.equal(d.job.current_state,'REVIEW_REQUIRED');assert.equal(d.factGuard.length,1);assert(d.stateHistory.some(t=>t.run_id===r.run_id&&t.to_state==='REVIEW_REQUIRED'));assert.equal(d.factGuard[0].request.input.human_review.evidence_id,f.e.id)}finally{await reopened.close()}});
test('FG06 missing approval and cross tenant are rejected before invocation',async()=>{const f=await guardFixture();await assert.rejects(f.s.run({...f.cmd,input:{...f.cmd.input,human_approval_evidence_id:randomUUID()}}),/HUMAN_RESEARCH_APPROVAL_REQUIRED/);await assert.rejects(f.s.run({...f.cmd,business_id:'wrong'}));assert.equal(f.calls(),0);assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'RESEARCH_COMPLETE')});
test('FG07 changed research policy is rejected before invocation',async()=>{const f=await guardFixture();f.s.policy={...genericPolicy,version:'wrong'};await assert.rejects(f.s.run(f.cmd),/RESEARCH_POLICY_MISMATCH/);assert.equal(f.calls(),0)});

import {HumanFactGuardReview} from '../src/application/human-fact-guard-review.js';
import {loadContentPolicies,verifyPolicySnapshot} from '../src/config/content-policies.js';
async function humanFixture(mixed=false){const f=await guardFixture(mixed?'mixed':true),original=await f.s.run(f.cmd),policies=await loadContentPolicies('arktrov');for(const kind of ['brand','quality']){const p=policies[kind];p.business_id=f.b;p.content_hash=hash({business_id:p.business_id,kind:p.kind,sources:p.sources});p.version='source-sha256:'+p.content_hash}policies.research.policy=genericPolicy;const service=new HumanFactGuardReview(new ResearchRepository(db),async()=>policies);const command={business_id:f.b,content_job_id:f.j.id,fact_guard_run_id:original.run_id,decisions:{'CLAIM-001':'CONTEXT_ONLY'},publication_hold:true};return {...f,original,policies,humanService:service,humanCommand:command}}
test('HFG01 human context and HOLD decisions and exact policy hashes persist immutably',async()=>{const f=await humanFixture(),d=await f.humanService.record(f.humanCommand);assert.equal(d.payload.actor,'human');assert.equal(d.payload.decisions['CLAIM-001'],'CONTEXT_ONLY');assert.equal(d.payload.publication_hold,true);assert.equal(d.payload.fact_guard.output_hash,f.original.output_hash);for(const k of ['brand','quality'])assert.equal(d.payload.policies[k].content_hash,f.policies[k].content_hash);assert.equal(d.content_hash,hash(d.payload));assert.equal((await f.humanService.record(f.humanCommand)).id,d.id);await assert.rejects(db.pool.query('UPDATE evidence_records SET payload=$1 WHERE id=$2',[{},d.id]),e=>e.code==='23514');assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'REVIEW_REQUIRED')});
test('HFG02 blocked decision does not become factual approval',async()=>{const f=await humanFixture(),d=await f.humanService.record({...f.humanCommand,decisions:{'CLAIM-001':'BLOCKED'}}),r=await f.s.run({...f.cmd,idempotency_key:'human:'+d.id,input:{...f.cmd.input,human_decision_id:d.id}});assert.equal(r.status,'SUCCEEDED');assert.deepEqual(r.output.blocked_claims,['CLAIM-001']);assert.deepEqual(r.output.context_only_claims,[]);assert.equal(r.output.decision,'REVIEW_REQUIRED');assert(r.output.script_guardrails.some(x=>x.includes('HUMAN BLOCKED')))});
test('HFG03 new immutable review persists context and zero calls without rewriting history',async()=>{const f=await humanFixture(),before=await db.getJob(f.j.id,f.b),d=await f.humanService.record(f.humanCommand),cmd={...f.cmd,idempotency_key:'human:'+d.id,input:{...f.cmd.input,human_decision_id:d.id}},r=await f.s.run(cmd);assert.equal(r.status,'SUCCEEDED');assert.notEqual(r.run_id,f.original.run_id);assert.deepEqual(r.output.context_only_claims,['CLAIM-001']);assert.equal(r.output.approved_claims.length,0);assert.equal(r.output.required_corrections.length,0);assert.equal(r.output.decision,'REVIEW_REQUIRED');assert.equal(r.metadata.usage.external_calls,0);assert.equal(r.request.input.policy_context.brand_snapshot.content_hash,f.policies.brand.content_hash);assert.equal((await f.s.run(cmd)).run_id,r.run_id);const reopened=new PostgresStore(url.href);try{const after=await reopened.getJob(f.j.id,f.b);assert.deepEqual(after.factGuard[0],before.factGuard[0]);assert.deepEqual(after.research,before.research);assert.deepEqual(after.recoveredResearch,before.recoveredResearch);assert.equal(after.factGuard.length,2);assert.equal(after.job.current_state,'REVIEW_REQUIRED');assert.equal(f.f.calls(),1);assert(after.stateHistory.some(t=>t.metadata.human_decision_id===d.id))}finally{await reopened.close()}});
test('HFG04 missing authoritative policy safely stops before persistence or rerun',async()=>{const f=await humanFixture(),before=await db.getJob(f.j.id,f.b);f.humanService.loadPolicies=()=>loadContentPolicies('arktrov',async()=>{throw Error('missing')});await assert.rejects(f.humanService.record(f.humanCommand),/POLICY_SOURCE_MISSING/);assert.deepEqual(await db.getJob(f.j.id,f.b),before)});
test('HFG05 changed policy content hash fails closed',async()=>{const f=await humanFixture();f.policies.brand.sources[0].content+='tampered';await assert.rejects(f.humanService.record(f.humanCommand),/POLICY_HASH_MISMATCH/)});
test('HFG06 cross tenant record and decision binding fail before invocation',async()=>{const f=await humanFixture();await assert.rejects(f.humanService.record({...f.humanCommand,business_id:'wrong'}));const d=await f.humanService.record(f.humanCommand),other=await guardFixture(true);await assert.rejects(other.s.run({...other.cmd,idempotency_key:'cross-tenant',input:{...other.cmd.input,human_decision_id:d.id}}),/HUMAN_DECISION_NOT_VERIFIED/);assert.equal(other.calls(),0)});
test('HFG07 unapproved review state transition cannot bypass human evidence',async()=>{const f=await humanFixture();const j=(await db.getJob(f.j.id,f.b)).job;await assert.rejects(db.transition(j.id,j.state_version,'FACT_GUARD_PENDING',{business_id:f.b}),/HUMAN_DECISION_NOT_VERIFIED/)});
test('HFG08 failed outcome persistence cannot produce passed state',async()=>{const f=await humanFixture(),d=await f.humanService.record(f.humanCommand),transition=db.transitionInTransaction.bind(db);db.transitionInTransaction=async(c,id,v,to,m)=>{if(id===f.j.id&&to==='REVIEW_REQUIRED')throw Error('FORCED_PERSISTENCE_FAILURE');return transition(c,id,v,to,m)};try{const r=await f.s.run({...f.cmd,idempotency_key:'human:'+d.id,input:{...f.cmd.input,human_decision_id:d.id}});assert.equal(r.status,'FAILED');assert.equal(r.error_category,'PERSISTENCE_FAILURE');assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'FAILED');assert.deepEqual((await db.getJob(f.j.id,f.b)).factGuard[0],f.original)}finally{db.transitionInTransaction=transition}});
test('HFG09 human decision cannot clear hold or promote a blocked claim',async()=>{const f=await humanFixture();await assert.rejects(f.humanService.record({...f.humanCommand,publication_hold:false}),/INVALID_HUMAN_DECISION/);await assert.rejects(f.humanService.record({...f.humanCommand,decisions:{'CLAIM-001':'APPROVED'}}),/INVALID_HUMAN_DECISION/)});
test('HFG10 repository policies retain authoritative source text and release rules',async()=>{const p=await loadContentPolicies('arktrov');for(const k of ['brand','quality'])verifyPolicySnapshot(p[k],'arktrov',k);assert(p.brand.sources.some(s=>s.content.includes('scientific figures preserve data integrity')));assert(p.quality.sources.some(s=>s.content.includes('RELEASE_ALLOWED')));assert(p.quality.sources.some(s=>s.content.includes('final_video_judge = APPROVED')));assert(p.research.policy.guardrails.includes('Do not invent evidence.'));await assert.rejects(loadContentPolicies('unknown'),/POLICY_SOURCE_MISSING/)});

import {validateFactGuard} from '../src/domain/research.js';
import {scriptStageInput,validateScriptClaimUses,validateContentScope} from '../src/domain/content-scope.js';
async function scopeFixture(disposition='CONTEXT_ONLY'){const f=await humanFixture(true),d=await f.humanService.record({...f.humanCommand,decisions:{'CLAIM-001':disposition}}),command={...f.cmd,idempotency_key:'scope:'+d.id,input:{...f.cmd.input,human_decision_id:d.id}},result=await f.s.run(command);assert.equal(result.status,'SUCCEEDED');return {...f,d,command,result}}
test('SCOPE01 safe approved subset with intentionally blocked claim can PASS',async()=>{const f=await scopeFixture('BLOCKED');assert.equal(f.result.output.decision,'PASS');assert.deepEqual(f.result.output.approved_claims,['SAFE-2']);assert.deepEqual(f.result.output.blocked_claims,['CLAIM-001'])});
test('SCOPE02 context-only claim coexists with PASS',async()=>{const f=await scopeFixture();assert.equal(f.result.output.decision,'PASS');assert.deepEqual(f.result.output.context_only_claims,['CLAIM-001'])});
test('SCOPE03 blocked claim cannot be consumed as factual script input',async()=>{const f=await scopeFixture('BLOCKED'),i=await new ResearchRepository(db).downstreamInput(f.b,f.j.id,f.result.run_id);assert.deepEqual(i.approved_claims.map(c=>c.claim_id),['SAFE-2']);assert.throws(()=>validateScriptClaimUses(i,[{claim_id:'CLAIM-001',use:'factual_assertion'}]),/BLOCKED_CLAIM_USE/)});
test('SCOPE04 context restriction is enforceable and mandatory',async()=>{const f=await scopeFixture(),i=scriptStageInput(f.result,f.b,f.j.id);assert.throws(()=>validateScriptClaimUses(i,[{claim_id:'CLAIM-001',use:'factual_assertion'}]),/UNAPPROVED_FACTUAL_USE/);assert(validateScriptClaimUses(i,[{claim_id:'CLAIM-001',use:'limitation',qualifier:i.scope.mandatory_qualifiers['CLAIM-001']}]));const o=structuredClone(f.result.output);delete o.downstream_scope.context_restrictions['CLAIM-001'];assert.throws(()=>validateFactGuard(o,f.result.request.input.research))});
test('SCOPE05 unresolved correction prevents PASS',async()=>{const f=await scopeFixture();const o=structuredClone(f.result.output);o.required_corrections.push('Unresolved factual correction');assert.throws(()=>validateFactGuard(o,f.result.request.input.research),/UNSAFE_PASS_SCOPE/);const request=structuredClone(f.result.request);delete request.input.human_fact_guard_decision.payload.decisions['CLAIM-001'];const r=await new OfflineFactGuardProvider().execute(request,{run_id:'offline'});assert.equal(r.output.decision,'REVIEW_REQUIRED');assert(r.output.required_corrections.length>0)});
test('SCOPE06 missing human decision remains REVIEW_REQUIRED',async()=>{const f=await scopeFixture(),request=structuredClone(f.result.request);delete request.input.human_fact_guard_decision;const r=await new OfflineFactGuardProvider().execute(request,{run_id:'offline'});assert.equal(r.output.decision,'REVIEW_REQUIRED');assert(r.output.required_corrections.includes('Missing persisted human scope decision.'))});
test('SCOPE07 empty safe scope cannot PASS',async()=>{const f=await humanFixture(),d=await f.humanService.record(f.humanCommand),r=await f.s.run({...f.cmd,idempotency_key:'empty:'+d.id,input:{...f.cmd.input,human_decision_id:d.id}});assert.equal(r.output.decision,'REVIEW_REQUIRED');assert.equal(r.output.approved_claims.length,0)});
test('SCOPE08 publication HOLD persists despite PASS',async()=>{const f=await scopeFixture();assert.equal(f.result.output.downstream_scope.publication_hold,true);assert.equal(f.result.request.input.human_fact_guard_decision.payload.publication_hold,true);assert.equal((await db.getJob(f.j.id,f.b)).job.current_state,'FACT_GUARD_PASSED')});
test('SCOPE09 PASS never allows release bypass',async()=>{const f=await scopeFixture(),j=(await db.getJob(f.j.id,f.b)).job;assert.equal(j.release_allowed,undefined);await assert.rejects(db.transition(j.id,j.state_version,'RELEASE_APPROVED',{business_id:f.b}),/INVALID_TRANSITION/)});
test('SCOPE10 scope version hash and persisted output immutable',async()=>{const f=await scopeFixture(),scope=f.result.output.downstream_scope,{content_scope_hash,...body}=scope;assert.equal(hash(body),content_scope_hash);assert.equal(scope.version,'factual-scope/1.0');await assert.rejects(db.pool.query('UPDATE research_outcomes SET output=$1 WHERE run_id=$2',[{},f.result.run_id]),e=>e.code==='23514');const changed={...scope,version:'modified'};assert.throws(()=>validateContentScope(changed,f.result.output,f.result.request.input.research))});
test('SCOPE11 cross tenant downstream access denied',async()=>{const f=await scopeFixture();await assert.rejects(new ResearchRepository(db).downstreamInput('wrong',f.j.id,f.result.run_id));assert.throws(()=>scriptStageInput(f.result,'wrong',f.j.id),/SCOPE_NOT_APPROVED/)});
test('SCOPE12 historical guard and research remain unchanged',async()=>{const f=await scopeFixture(),d=await db.getJob(f.j.id,f.b);assert.deepEqual(d.factGuard[0],f.original);assert.equal(d.research[0].status,'FAILED');assert.equal((await f.s.run(f.command)).run_id,f.result.run_id);assert.equal(d.factGuard.length,2)});
test('SCOPE13 script input exposes only admitted facts and enforces qualifiers',async()=>{const f=await scopeFixture(),i=scriptStageInput(f.result,f.b,f.j.id);assert.equal(i.research,undefined);assert.deepEqual(i.approved_claims.map(c=>c.claim_id),['SAFE-2']);assert.throws(()=>validateScriptClaimUses(i,[{claim_id:'SAFE-2',use:'factual_assertion'}]),/MISSING_MANDATORY_QUALIFIER/);assert(validateScriptClaimUses(i,[{claim_id:'SAFE-2',use:'factual_assertion',qualifier:i.scope.mandatory_qualifiers['SAFE-2']}]));assert.throws(()=>validateScriptClaimUses(i,[{claim_id:'not-researched',use:'factual_assertion'}]))});
test('SCOPE14 authoritative snapshots remain bound and missing policy blocks PASS',async()=>{const f=await scopeFixture();assert.deepEqual(f.result.output.downstream_scope.policy_snapshot_refs,f.d.payload.policies);const request=structuredClone(f.result.request);request.input.policy_context.quality_policy_snapshot=null;const r=await new OfflineFactGuardProvider().execute(request,{run_id:'offline'});assert.equal(r.output.decision,'REVIEW_REQUIRED')});

test('REVIEW01 context-only use requires its persisted qualifier',async()=>{const f=await scopeFixture(),i=scriptStageInput(f.result,f.b,f.j.id);assert.throws(()=>validateScriptClaimUses(i,[{claim_id:'CLAIM-001',use:'limitation'}]),/MISSING_MANDATORY_QUALIFIER/)});
test('REVIEW02 normal successful Research can bind human policy review without recovery',async()=>{const f=await fixture(),adapter=await adapterFixture(()=>{},{authorizedAttempt:2}),repository=new ResearchRepository(db),service=new ResearchService({repository,researchProvider:adapter.provider,factGuardProvider:new OfflineFactGuardProvider(),prompts:{research:researchPrompt,fact_guard:offlineFactGuardPrompt},policy:genericPolicy});const research=await service.run({business_id:f.b,content_job_id:f.j.id,operation:'research',idempotency_key:'paid',input:f.run.request.input,retry:true});assert.equal(research.status,'SUCCEEDED');const command={business_id:f.b,content_job_id:f.j.id,operation:'fact_guard',idempotency_key:'normal',input:{research_run_id:research.run_id}},first=await service.run(command);assert.equal(first.output.decision,'REVIEW_REQUIRED');assert.equal(first.output.blocked_claims.length,0);const policies=await loadContentPolicies('arktrov');for(const kind of ['brand','quality']){const p=policies[kind];p.business_id=f.b;p.content_hash=hash({business_id:p.business_id,kind:p.kind,sources:p.sources});p.version='source-sha256:'+p.content_hash}policies.research.policy=genericPolicy;const h=await new HumanFactGuardReview(repository,async()=>policies).record({business_id:f.b,content_job_id:f.j.id,fact_guard_run_id:first.run_id,decisions:{},publication_hold:true});assert.equal(h.payload.research.processing_revision_id,null);assert.equal(h.payload.research.run_id,research.run_id);const reviewed=await service.run({...command,idempotency_key:'reviewed',input:{...command.input,human_decision_id:h.id}});assert.equal(reviewed.output.decision,'PASS');assert.equal(reviewed.output.downstream_scope.publication_hold,true);assert.equal((await db.getJob(f.j.id,f.b)).recoveredResearch.length,0)});
