import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {readFile} from 'node:fs/promises';
import {chromium} from 'playwright';
import {PostgresStore} from '../src/persistence-postgres.js';
import {ResearchRepository} from '../src/research-postgres.js';
import {ResearchService} from '../src/application/research-service.js';
import {LocalResearchProvider,LocalFactGuardProvider} from '../src/providers/local.js';
import {researchPrompt,factGuardPrompt,genericPolicy} from '../src/config/research.js';
import {hash,validateResearch,validateFactGuard} from '../src/domain/research.js';
import {migrate} from '../scripts/migrate.mjs';
const base=process.env.TEST_DATABASE_URL;if(!base)throw Error('TEST_DATABASE_URL_REQUIRED');
const url=new URL(base);if(!['127.0.0.1','localhost'].includes(url.hostname))throw Error('LOCAL_TEST_DB_REQUIRED');
const name='abo_test_'+randomUUID().replaceAll('-','');let admin,db,connection;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;connection=url.href;db=new PostgresStore(connection);await migrate(db.pool)});
after(async()=>{await db?.close();if(admin){await admin.query('DROP DATABASE IF EXISTS '+name);await admin.end()}});
async function fixture(research='success',guard='PASS'){
 const business_id='synthetic_'+randomUUID();await db.seed({id:business_id,tenant_id:randomUUID(),name:'Synthetic tests',brand:{}});
 const input={business_id,content_item_id:'synthetic:'+randomUUID(),format:'SHORT',idempotency_key:randomUUID(),workflow_version:'phase-2a.1'};
 let job=await db.createJob(input);for(const state of ['DISCOVERY_COMPLETE','RESEARCH_PENDING'])job=await db.transition(job.id,job.state_version,state,{business_id});
 const rp=new LocalResearchProvider(research),fp=new LocalFactGuardProvider(guard),repository=new ResearchRepository(db);
 const service=new ResearchService({repository,researchProvider:rp,factGuardProvider:fp,prompts:{research:researchPrompt,fact_guard:factGuardPrompt},policy:genericPolicy});
 const command={business_id,content_job_id:job.id,operation:'research',idempotency_key:'research-1',input:{topic:'Synthetic contract fixture'}};
 return {business_id,job,input,rp,fp,repository,service,command,async research(){return service.run(command)},async fg(r,extra={}){return service.run({...command,operation:'fact_guard',idempotency_key:'guard-1',input:{research_run_id:r.run_id},...extra})}};
}
const detail=f=>db.getJob(f.job.id,f.business_id);
const rows=async(table,f)=>(await db.pool.query('SELECT * FROM '+table+' WHERE business_id=$1 AND content_job_id=$2',[f.business_id,f.job.id])).rows;
async function completed(){const f=await fixture();const r=await f.research();return {f,r,g:await f.fg(r)}}
async function app(business,extra={}){
 const child=spawn(process.execPath,['src/server/index.js'],{env:{...process.env,DATABASE_URL:connection,BUSINESS_ID:business,PORT:'0',ENABLE_LOCAL_RESEARCH:'1',...extra},stdio:['ignore','pipe','pipe'],windowsHide:true});
 let output='';child.stderr.resume();
 const port=await new Promise((resolve,reject)=>{const t=setTimeout(()=>{child.kill();reject(Error('START_TIMEOUT'))},15000);child.once('exit',()=>{clearTimeout(t);reject(Error('APP_EXIT'))});child.stdout.on('data',b=>{output+=b;for(const line of output.split('\n'))try{const x=JSON.parse(line);if(x.event==='ready'){clearTimeout(t);resolve(x.port)}}catch{}})});
 return {url:'http://127.0.0.1:'+port,async stop(){if(child.exitCode!==null)return;const end=once(child,'exit');child.kill();await end}};
}
async function api(a,path,data){const res=await fetch(a.url+path,{method:data?'POST':'GET',headers:{'content-type':'application/json'},body:data?JSON.stringify(data):undefined});return {status:res.status,data:await res.json()}}
test('P2A01 ResearchRun tenant isolation',async()=>{const a=await fixture(),b=await fixture(),r=await a.research();assert.equal(r.business_id,a.business_id);await assert.rejects(b.service.run({...a.command,business_id:b.business_id}),/JOB_NOT_FOUND/);assert.equal((await detail(b)).research.length,0)});
test('P2A02 Same key and hash reuses successful result',async()=>{const f=await fixture(),a=await f.research(),b=await f.service.run({...f.command,input:{topic:'  Synthetic contract fixture  '}});assert.equal(a.run_id,b.run_id);assert.equal(f.rp.calls,1);assert.equal((await rows('research_attempts',f)).length,1)});
test('P2A03 Changed input rejects idempotency conflict',async()=>{const f=await fixture();await f.research();await assert.rejects(f.service.run({...f.command,input:{topic:'Changed'}}),/IDEMPOTENCY_CONFLICT/);assert.equal(f.rp.calls,1)});
test('P2A04 Parallel duplicates create one logical success',async()=>{const f=await fixture();const results=await Promise.all(Array.from({length:6},()=>f.research()));assert.equal(new Set(results.map(r=>r.run_id)).size,1);assert.equal(f.rp.calls,1);assert.equal((await rows('research_outcomes',f)).length,1)});
test('P2A05 Failed research requires explicit audited retry',async()=>{const f=await fixture('retry');const first=await f.research();assert.equal(first.status,'FAILED');assert.equal(first.error_category,'PROVIDER_FAILURE');await assert.rejects(f.research(),/EXPLICIT_RETRY_REQUIRED/);const second=await f.service.run({...f.command,retry:true});assert.equal(second.status,'SUCCEEDED');assert.equal(second.attempt,2);assert.notEqual(first.run_id,second.run_id);assert.equal((await detail(f)).stateHistory.filter(t=>t.to_state==='RESEARCH_RUNNING').length,2)});
test('P2A06 Research persistence failure cannot complete state',async()=>{const f=await fixture();await db.pool.query(`CREATE FUNCTION fail_claim() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected'; END $$; CREATE TRIGGER fail_claim BEFORE INSERT ON research_claims FOR EACH ROW EXECUTE FUNCTION fail_claim()`);try{const r=await f.research();assert.equal(r.status,'FAILED');assert.equal(r.error_category,'PERSISTENCE_FAILURE');assert.equal((await detail(f)).job.current_state,'FAILED');assert.equal((await rows('research_claims',f)).length,0);assert(!(await detail(f)).stateHistory.some(t=>t.to_state==='RESEARCH_COMPLETE'))}finally{await db.pool.query('DROP TRIGGER fail_claim ON research_claims; DROP FUNCTION fail_claim()')}});
test('P2A07 Claims persist structured fields',async()=>{const f=await fixture(),r=await f.research();assert.deepEqual((await rows('research_claims',f)).map(x=>x.data),r.output.claims);assert.equal(r.output.claims[0].verification_status,'verified')});
test('P2A08 Sources persist provenance and timestamps',async()=>{const f=await fixture(),r=await f.research();const sources=await rows('research_sources',f);assert.equal(sources.length,2);assert.deepEqual(sources.map(s=>s.data).sort((a,b)=>a.source_id.localeCompare(b.source_id)),r.output.sources)});
test('P2A09 Claim evidence relations enforce scoped foreign keys',async()=>{const f=await fixture();await f.research();const links=await rows('research_claim_evidence',f);assert.equal(links.length,2);const l=links[0];await assert.rejects(db.pool.query('INSERT INTO research_claim_evidence VALUES($1,$2,$3,$4,$5,$6)',[l.business_id,l.content_job_id,l.run_id,'missing',l.source_id,l.data]),e=>e.code==='23503')});
test('P2A10 Prompt version and content hash persist',async()=>{const f=await fixture(),r=await f.research();assert.deepEqual(r.request.prompt,researchPrompt);const d=(await db.pool.query("SELECT * FROM research_definitions WHERE business_id=$1 AND kind='prompt'",[f.business_id])).rows[0];assert.equal(d.content_hash,hash(researchPrompt));assert.equal(d.version,'1.0')});
test('P2A11 Policy snapshot remains immutable',async()=>{const f=await fixture(),r=await f.research();assert.deepEqual(r.request.policy,genericPolicy);await assert.rejects(db.pool.query("UPDATE research_definitions SET version='2' WHERE business_id=$1",[f.business_id]),e=>e.code==='23514')});
test('P2A12 Provider model metadata hashes and duration persist',async()=>{const f=await fixture(),r=await f.research();assert.equal(r.provider,'local-test');assert.equal(r.model,'research-fixture');assert.equal(r.metadata.cost.actual,0);assert.equal(r.metadata.synthetic,true);assert(r.metadata.duration_ms>=0);assert(r.metadata.provider_request_id);assert.equal(r.output_hash,hash(r.output));assert.equal(r.canonical_input_hash,hash(r.request))});
for(const [num,mode,state] of [[13,'PASS','FACT_GUARD_PASSED'],[14,'REVIEW_REQUIRED','REVIEW_REQUIRED'],[15,'REJECT','REJECTED']])test('P2A'+num+' Fact Guard '+mode,async()=>{const f=await fixture('success',mode),r=await f.research(),g=await f.fg(r);assert.equal(g.status,'SUCCEEDED');assert.equal(g.output.decision,mode);assert.equal((await detail(f)).job.current_state,state);assert.equal(g.request.input.research_output_hash,r.output_hash);assert.deepEqual(g.request.input.research,r.output)});
test('P2A16 Fact Guard persistence failure cannot pass state',async()=>{const f=await fixture(),r=await f.research();await db.pool.query(`CREATE FUNCTION fail_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.output->>'decision'='PASS' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER fail_guard BEFORE INSERT ON research_outcomes FOR EACH ROW EXECUTE FUNCTION fail_guard()`);try{const g=await f.fg(r);assert.equal(g.status,'FAILED');assert.equal(g.error_category,'PERSISTENCE_FAILURE');assert.equal((await detail(f)).job.current_state,'FAILED');assert(!(await detail(f)).stateHistory.some(t=>t.to_state==='FACT_GUARD_PASSED'))}finally{await db.pool.query('DROP TRIGGER fail_guard ON research_outcomes; DROP FUNCTION fail_guard()')}});
test('P2A17 Required corrections persist',async()=>{const f=await fixture('success','REVIEW_REQUIRED'),g=await f.fg(await f.research());assert.deepEqual(g.output.required_corrections,['Resolve the synthetic factual blocker.']);assert.deepEqual((await detail(f)).factGuard[0].output.required_corrections,g.output.required_corrections)});
test('P2A18 Script guardrails persist',async()=>{const {f,g}=await completed();assert.equal(g.output.script_guardrails.length,2);assert.deepEqual((await detail(f)).factGuard[0].output.script_guardrails,g.output.script_guardrails)});
test('P2A19 Approved and blocked claims persist distinctly',async()=>{for(const decision of ['PASS','REJECT']){const f=await fixture('success',decision),g=await f.fg(await f.research());assert.deepEqual(g.output.approved_claims,decision==='PASS'?['CLAIM-001']:[]);assert.deepEqual(g.output.blocked_claims,decision==='REJECT'?['CLAIM-001']:[])}});
test('P2A20 Cross tenant research read rejected',async()=>{const f=await fixture(),r=await f.research(),b=await fixture();await assert.rejects(f.repository.getResearch(b.business_id,f.job.id,r.run_id),/JOB_NOT_FOUND/);await assert.rejects(b.fg(r),/RESEARCH_NOT_FOUND/)});
test('P2A21 Cross tenant Fact Guard read rejected',async()=>{const {f,g}=await completed(),b=await fixture();await assert.rejects(f.repository.result(b.business_id,f.job.id,g.run_id),/JOB_NOT_FOUND/);const a=await app(b.business_id);try{assert.equal((await api(a,'/api/jobs/'+f.job.id+'/fact-guard')).status,404)}finally{await a.stop()}});
test('P2A22 Job Detail Research API exposes persisted canonical result',async()=>{const f=await fixture(),r=await f.research(),a=await app(f.business_id);try{const response=await api(a,'/api/jobs/'+f.job.id+'/research');assert.equal(response.status,200);assert.deepEqual(response.data[0].output,r.output);assert.equal(response.data[0].metadata.synthetic,true)}finally{await a.stop()}});
test('P2A23 Job Detail Fact Guard API exposes persisted decision',async()=>{const {f,g}=await completed(),a=await app(f.business_id);try{const response=await api(a,'/api/jobs/'+f.job.id+'/fact-guard');assert.equal(response.status,200);assert.deepEqual(response.data[0].output,g.output)}finally{await a.stop()}});
test('P2A24 Real app restart retains Research and Fact Guard',async()=>{const f=await fixture();let a=await app(f.business_id);try{const path='/api/jobs/'+f.job.id;const r=await api(a,path+'/research',{idempotency_key:'r',input:{topic:'Synthetic restart fixture'}});assert.equal(r.status,201);const g=await api(a,path+'/fact-guard',{idempotency_key:'f',input:{research_run_id:r.data.run_id}});assert.equal(g.status,201);const prior=(await api(a,path)).data;assert.equal(prior.job.current_state,'FACT_GUARD_PASSED');await a.stop();a=await app(f.business_id);assert.deepEqual((await api(a,path)).data,prior);assert.equal((await api(a,path+'/research',{idempotency_key:'r',input:{topic:'Synthetic restart fixture'}})).data.run_id,r.data.run_id)}finally{await a.stop()}});
test('P2A25 Upgrade real Phase 1 schema preserves existing data',async()=>{const upgrade='abo_test_'+randomUUID().replaceAll('-','');await admin.query('CREATE DATABASE '+upgrade);const u=new URL(base);u.pathname='/'+upgrade;const p=new pg.Pool({connectionString:u.href});try{for(const file of ['001_control_plane.sql','002_evidence_artifact_boundaries.sql'])await p.query(await readFile(new URL('../db/migrations/'+file,import.meta.url),'utf8'));const business='upgrade',job=randomUUID();await p.query("INSERT INTO businesses(id,tenant_id,name) VALUES('upgrade','upgrade','Upgrade')");await p.query("INSERT INTO content_jobs(id,business_id,format,current_state,idempotency_key,workflow_version,brand_rule_version,quality_policy_version,created_at,updated_at) VALUES($1,$2,'SHORT','IDEA_CREATED','upgrade','w1','b1','q1',now(),now())",[job,business]);await p.query('CREATE TABLE schema_migrations(name text PRIMARY KEY)');await p.query("INSERT INTO schema_migrations VALUES('001_control_plane.sql'),('002_evidence_artifact_boundaries.sql')");await migrate(p);assert.equal((await p.query('SELECT id FROM content_jobs WHERE id=$1',[job])).rowCount,1);assert.equal((await p.query('SELECT * FROM schema_migrations')).rowCount,6);assert.equal((await p.query('SELECT * FROM research_operations')).rowCount,0)}finally{await p.end();await admin.query('DROP DATABASE '+upgrade+' WITH (FORCE)')}});
test('P2A Research and Fact Guard UI show real persisted test evidence',async()=>{const f=await fixture('success','REVIEW_REQUIRED');await f.fg(await f.research());const a=await app(f.business_id);let browser;try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();await page.goto(a.url);await page.locator('#jobs button').first().click();await page.locator('#research pre').waitFor();assert.match(await page.locator('#research').innerText(),/SYNTHETISCHE TESTDATEN/);assert.match(await page.locator('#research').innerText(),/CLAIM-001/);assert.match(await page.locator('#research').innerText(),/fixture.invalid/);assert.match(await page.locator('#fact-guard').innerText(),/Resolve the synthetic factual blocker/);assert.match(await page.locator('#fact-guard').innerText(),/REVIEW_REQUIRED/)}finally{await browser?.close();await a.stop()}});
test('P2A Malformed provider output fails closed',async()=>{const f=await fixture('parsing_failure'),r=await f.research();assert.equal(r.error_category,'PARSING_FAILURE');assert.equal((await detail(f)).job.current_state,'FAILED');assert.equal((await rows('research_claims',f)).length,0)});
test('P2A Fact Guard failure retry and duplicates are audited',async()=>{const f=await fixture('success','retry'),r=await f.research(),g=await f.fg(r);assert.equal(g.status,'FAILED');await assert.rejects(f.fg(r),/EXPLICIT_RETRY_REQUIRED/);const second=await f.fg(r,{retry:true});assert.equal(second.status,'SUCCEEDED');assert.equal(second.attempt,2);assert.equal((await f.fg(r)).run_id,second.run_id);assert.equal(f.fp.calls,2)});
test('P2A Research uncertainties and contradictions retain safe outcomes',async()=>{for(const mode of ['uncertain','contradiction']){const f=await fixture(mode),r=await f.research();assert.equal((await detail(f)).job.current_state,mode==='uncertain'?'REVIEW_REQUIRED':'REJECTED');assert(r.output.uncertainties.length);if(mode==='contradiction')assert(r.output.contradictions.length);await assert.rejects(f.fg(r),/RESEARCH_NOT_COMPLETE/)}});
test('P2A Completion bypass and cross tenant evidence writes rejected',async()=>{const f=await fixture();await assert.rejects(db.transition(f.job.id,f.job.state_version,'RESEARCH_COMPLETE',{business_id:f.business_id}),/PERSISTED_EVIDENCE_REQUIRED/);const r=await f.research(),b=await fixture();await assert.rejects(db.pool.query('INSERT INTO research_claims VALUES($1,$2,$3,$4,$5)',[b.business_id,f.job.id,r.run_id,'cross',{}]),e=>e.code==='23503');await assert.rejects(db.pool.query('DELETE FROM research_outcomes WHERE run_id=$1',[r.run_id]),e=>e.code==='23514')});
test('P2A Same prompt version cannot change content',async()=>{const f=await fixture('retry');await f.research();f.service.prompts={...f.service.prompts,research:{...researchPrompt,content:'Changed content'}};await assert.rejects(f.service.run({...f.command,idempotency_key:'new-key',retry:true}),/VERSION_CONTENT_CONFLICT/);assert.equal(f.rp.calls,1)});
test('P2A Job changed input idempotency rejected in PostgreSQL',async()=>{const f=await fixture();await assert.rejects(db.createJob({...f.input,working_title:'Changed'}),/IDEMPOTENCY_CONFLICT/);assert.equal((await db.createJob(f.input)).id,f.job.id)});
test('P2A Unsafe payload never reaches provider or persistence',async()=>{const f=await fixture();await assert.rejects(f.service.run({...f.command,input:{topic:'Fixture',authorization:'sensitive'}}),/UNSAFE_PAYLOAD/);assert.equal(f.rp.calls,0);assert.equal((await detail(f)).research.length,0)});
test('P2A Fact Guard invalid claim IDs and inconsistent PASS rejected',async()=>{const f=await fixture(),r=await f.research(),g=await f.fg(r);assert.throws(()=>validateFactGuard({...g.output,blocked_claims:['CLAIM-001']},r.output),/PARSING_FAILURE/);assert.throws(()=>validateFactGuard({...g.output,approved_claims:['unknown']},r.output),/PARSING_FAILURE/);assert.throws(()=>validateResearch({...r.output,evidence:[]}),/PARSING_FAILURE/)});
test('P2A Interrupted attempt survives and needs explicit recovery',async()=>{
 const f=await fixture();const request={business_id:f.business_id,content_job_id:f.job.id,operation:'research',input:f.command.input,workflow_version:f.job.workflow_version,prompt:researchPrompt,policy:genericPolicy,provider:f.rp.describe()};
 const abandoned=await f.repository.withJobLock(f.business_id,f.job.id,()=>f.repository.begin(f.business_id,f.job.id,'research','research-1',request,false));
 assert.equal((await detail(f)).job.current_state,'RESEARCH_RUNNING');await assert.rejects(f.research(),/INTERRUPTED_RETRY_REQUIRED/);
 const result=await f.service.run({...f.command,retry:true});assert.equal(result.attempt,2);assert.equal(result.status,'SUCCEEDED');const d=await detail(f);assert.equal(d.research.find(x=>x.run_id===abandoned.run_id).error_category,'INTERRUPTED');assert.equal(d.stateHistory.filter(x=>x.to_state==='FAILED').length,1);
});
test('P2A Fact Guard foreign key cannot reference another tenant',async()=>{
 const a=await fixture(),r=await a.research(),b=await fixture();
 await assert.rejects(db.pool.query("INSERT INTO research_operations(id,business_id,content_job_id,operation,idempotency_key,canonical_input_hash,request,research_run_id) VALUES($1,$2,$3,'fact_guard','cross','hash','{}',$4)",[randomUUID(),b.business_id,b.job.id,r.run_id]),e=>e.code==='23503');
});
test('P2A Provider config and policy changes conflict under same key',async()=>{const f=await fixture();await f.research();f.service.policy={...genericPolicy,version:'2.0'};await assert.rejects(f.research(),/IDEMPOTENCY_CONFLICT/);f.service.policy=genericPolicy;f.rp.mode='uncertain';await assert.rejects(f.research(),/IDEMPOTENCY_CONFLICT/);assert.equal(f.rp.calls,1)});
test('P2A Live content jobs cannot receive local synthetic API results',async()=>{const f=await fixture(),real=await db.createJob({...f.input,idempotency_key:randomUUID(),content_item_id:'unconfirmed-real-content'}),a=await app(f.business_id);try{assert.equal((await api(a,'/api/jobs/'+real.id+'/research',{idempotency_key:'test',input:{topic:'No fake research'}})).data.error,'SYNTHETIC_JOB_REQUIRED');assert.equal((await db.getJob(real.id,f.business_id)).research.length,0)}finally{await a.stop()}});
test('P2A Provider output cannot persist undeclared secret or private reasoning fields',async()=>{const f=await fixture();const execute=f.rp.execute.bind(f.rp);f.rp.execute=async(...args)=>{const r=await execute(...args);r.output.private_thoughts='not part of public contract';return r};const r=await f.research();assert.equal(r.error_category,'PARSING_FAILURE');assert.equal(r.output,null)});
test('P2A Pipeline automatically completes both stages and safely reuses results',async()=>{const f=await fixture();const r=await f.service.runPipeline(f.command);assert.equal(r.research.status,'SUCCEEDED');assert.equal(r.factGuard.output.decision,'PASS');assert.equal((await detail(f)).job.current_state,'FACT_GUARD_PASSED');const again=await f.service.runPipeline(f.command);assert.equal(again.factGuard.run_id,r.factGuard.run_id);assert.equal(f.rp.calls,1);assert.equal(f.fp.calls,1)});
test('P2A Pipeline stops before Fact Guard on research failure or hold',async()=>{for(const mode of ['provider_failure','uncertain']){const f=await fixture(mode);const r=await f.service.runPipeline(f.command);assert.equal(r.factGuard,null);assert.equal(f.fp.calls,0)}});
test('P2A Parallel load above pool capacity does not deadlock',async()=>{const f=await fixture();const r=await Promise.allSettled(Array.from({length:24},()=>f.research()));assert(r.every(x=>x.status==='fulfilled'));assert.equal(new Set(r.map(x=>x.value.run_id)).size,1);assert.equal(f.rp.calls,1)});
test('P2A Late completion is fenced after explicit recovery',async()=>{const f=await fixture();const request={business_id:f.business_id,content_job_id:f.job.id,operation:'research',input:f.command.input,workflow_version:f.job.workflow_version,prompt:researchPrompt,policy:genericPolicy,provider:f.rp.describe()};const old=await f.repository.begin(f.business_id,f.job.id,'research','research-1',request,false);const r=await f.service.run({...f.command,retry:true});await assert.rejects(f.repository.finish(f.business_id,f.job.id,'research',old,request,r.output,r.metadata),/STALE_STATE_VERSION/);assert.equal((await detail(f)).research.filter(x=>x.status==='SUCCEEDED').length,1)});
test('P2A Fact Guard changed configuration conflicts and malformed result fails',async()=>{const f=await fixture(),r=await f.research();await f.fg(r);f.fp.mode='REJECT';await assert.rejects(f.fg(r),/IDEMPOTENCY_CONFLICT/);const bad=await fixture('success','parsing_failure');assert.equal((await bad.fg(await bad.research())).error_category,'PARSING_FAILURE')});
test('P2A Different provider implementation fits unchanged domain and persistence',async()=>{const f=await fixture(),fixtureResponse=await f.rp.execute({input:{topic:'Injection fixture'}},{attempt:1,run_id:'fixture'});f.service.researchProvider={describe(){return {provider:'independent-local-contract-test',model:'canonical-test',adapter_version:'2',configuration:{}}},async execute(){return fixtureResponse}};const r=await f.research();assert.equal(r.provider,'independent-local-contract-test');assert.equal(r.status,'SUCCEEDED');assert.equal((await f.fg(r)).output.decision,'PASS')});

test('P2A Parallel pool shutdown drains socket ends before database drop',async()=>{
 for(let cycle=0;cycle<3;cycle++){
  const database='abo_test_'+randomUUID().replaceAll('-','');await admin.query('CREATE DATABASE '+database);
  const u=new URL(base);u.pathname='/'+database;const store=new PostgresStore(u.href);let connected=0,ended=0;
  store.pool.on('connect',client=>{connected++;client.once('end',()=>ended++);});
  try{
   const clients=await Promise.all(Array.from({length:10},()=>store.pool.connect()));
   await Promise.all(clients.map(async client=>{try{await client.query('SELECT 1')}finally{client.release()}}));
   await store.close();assert.equal(connected,10);assert.equal(ended,connected);assert.equal(store.pool.totalCount,0);assert.equal(store.pool.waitingCount,0);
  }finally{await store.close();await admin.query('DROP DATABASE '+database);}
 }
});

test('REVIEW03 public evidence endpoint cannot forge internal approval or policy evidence',async()=>{const f=await fixture(),a=await app(f.business_id);try{const before=await detail(f);for(const evidence_type of ['provider_response','confirmed_research_input','human_research_approval','human_fact_guard_decision','policy_snapshot','policy_binding_audit']){const r=await api(a,'/api/jobs/'+f.job.id+'/evidence',{evidence_type,reference:'forged',payload:{actor:'human'}});assert.equal(r.data.error,'RESERVED_EVIDENCE_TYPE')}assert.deepEqual((await detail(f)).evidence,before.evidence)}finally{await a.stop()}});
