import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {hash} from '../src/domain/research.js';
import {seal,makeManifest} from '../src/domain/assets.js';
import {wavQA} from '../src/domain/asset-qa.js';
import {approveVoice,voiceDecisions,retimeProduction,applyProductionTiming} from '../src/domain/production-timing.js';
import {PostgresStore} from '../src/persistence-postgres.js';
import {migrate} from '../scripts/migrate.mjs';
import {scriptFixture} from './fixtures/script.js';
import {HumanProductionApproval} from '../src/application/human-production-approval.js';
import {AssetRepository} from '../src/assets-postgres.js';
import {VoiceTimingService} from '../src/application/voice-timing.js';
import {ScriptRepository} from '../src/script-postgres.js';
const now='2026-01-01T00:00:00.000Z',source={reference:'synthetic-human-review',sha256:hash('synthetic-review')};
function wav(seconds){const count=Math.round(seconds*8000),bytes=Buffer.alloc(44+count*2);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(8000,24);bytes.writeUInt32LE(16000,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(count*2,40);for(let i=0;i<count;i++)bytes.writeInt16LE(Math.round(Math.sin(i/8)*9000),44+i*2);return bytes}
function asset(plan,profile){const bytes=wav(plan.voice.expected_duration*1.2),data={format:'wav',bytes_base64:bytes.toString('base64')};return seal({asset_id:randomUUID(),version:1,type:'VOICE',business_id:plan.business_id,content_job_id:plan.content_job_id,plan_hash:plan.content_hash,production_package_hash:plan.production_package_hash,script_hash:plan.script_hash,text_hash:plan.voice.text_hash,voice_requirement_id:'VOICE',data,data_hash:hash(data),rights:{status:'REVIEW_REQUIRED',evidence:null},provenance:{origin:'synthetic',created_at:now,profile,request_id:'synthetic'},qa:{...wavQA(bytes,plan.voice.expected_duration),leading_silence_seconds:0.05,trailing_silence_seconds:0.1}})}
function fixture(){
 const segments=Array.from({length:7},(_,i)=>({segment_id:'s'+i,text:'Exact synthetic words '+i,duration_target:1,claim_id:'c'+i})),body={script_id:'script',output_hash:undefined,voiceover_text:segments.map(s=>s.text).join('\n'),segments};delete body.output_hash;
 const script={...body,output_hash:hash(body)};let at=0;
 const beats=segments.flatMap((s,i)=>Array.from({length:i<4?2:1},(_,n)=>{const b={visual_beat_id:s.segment_id+'b'+n,segment_id:s.segment_id+'b'+n,narration_segment_id:s.segment_id,start_target:at,duration_target:i<4?0.5:1,claim_refs:[s.claim_id],visual_classification:'ILLUSTRATIVE',concrete_visual_brief:'Existing synthetic staged diagram brief with continuous restrained motion',motion_intent:'Existing continuous reveal',rights_requirement:'Review required',disclosure_requirement:'Illustration',visual_type:'CONTROLLED_DIAGRAM',asset_requirement:{requirement_id:s.segment_id+'b'+n,reuse_status:'NOT_CLEARED'}};at+=b.duration_target;return b}));
 const pkg=seal({production_package_id:'pkg',package_version:4,business_id:'tenant',content_job_id:'job',script_id:script.script_id,script_output_hash:script.output_hash,target_duration:7,target_platform_profile:{id:'test',max_seconds:10},timeline_segments:beats,narration_segments:segments,audio_plan:{pause_cues:[{after_claim:'c1'}],emphasis_cues:['Exact'],estimated_vo_duration:7},publication_hold:true,release_allowed:false,created_at:now});
 const plan=seal({plan_id:'plan',business_id:'tenant',content_job_id:'job',script_id:script.script_id,script_hash:script.output_hash,production_package_id:'pkg',production_package_hash:pkg.content_hash,voice:{text:script.voiceover_text,text_hash:hash(script.voiceover_text),expected_duration:7},requirements:beats.map(b=>({visual_beat_id:b.visual_beat_id,resolution_type:'NATIVE_SCENE',classification:b.visual_classification,disclosure:b.disclosure_requirement})),music:{required:true},sfx:{required:true},subtitles:{required:true},publication_hold:true,release_allowed:false});
 const voice=asset(plan,{status:'APPROVED',voice_profile_id:'profile',version:3,content_hash:'profile-hash'});
 const args={id:'approval',plan,script,pkg,voice,actor:'human',decisions:voiceDecisions,source,created_at:now},approval=approveVoice(args);
 return {...args,approval};
}
const revision=f=>retimeProduction({...f,id:'timed-package',version:5});
const reseal=x=>{const {content_hash,...body}=x;return seal(body)};
test('VT01 decoded duration replaces estimate with non-destructive sample-accurate trim',()=>{const f=fixture(),r=revision(f);assert.equal(r.target_duration,8.25);assert.equal(r.timing.actual_audio_duration,8.4);assert.equal(r.timing.trim.source_in_frame,400);assert.equal(r.timing.trim.source_out_frame,66400);assert.equal(r.audio_plan.production_trim.playback_rate,1);assert.equal(r.timing.trim.application_status,'METADATA_ONLY_NOT_RENDERED');assert.equal(r.timing.previous_estimated_duration,7)});
test('VT02 source voice script and creative package remain byte-identical',()=>{const f=fixture(),before=JSON.stringify(f);revision(f);assert.equal(JSON.stringify(f),before)});
test('VT03 all eleven beats and seven narration segments cover the exact effective timeline',()=>{const r=revision(fixture());assert.equal(r.timeline_segments.length,11);assert.equal(r.narration_segments.length,7);let end=0;for(const b of r.timeline_segments){assert(Math.abs(b.start_target-end)<1e-10);end=b.start_target+b.duration_target}assert(Math.abs(end-r.target_duration)<1e-10);assert.equal(r.narration_segments.at(-1).end_frame/r.timing.trim.sample_rate,r.target_duration)});
test('VT04 factual links classifications briefs rights disclosures routing and motion remain identical',()=>{const f=fixture(),r=revision(f);for(let i=0;i<11;i++){const strip=b=>{const {start_target,duration_target,...rest}=b;return rest};assert.deepEqual(strip(r.timeline_segments[i]),strip(f.pkg.timeline_segments[i]))}assert.deepEqual(r.audio_plan.pause_cues,f.pkg.audio_plan.pause_cues);assert.deepEqual(r.audio_plan.emphasis_cues,f.pkg.audio_plan.emphasis_cues)});
test('VT05 subtitles keep exact text but approximate boundaries cannot be final',()=>{const f=fixture(),r=revision(f);assert.equal(r.subtitle_timing.script_text,f.script.voiceover_text);assert.equal(r.subtitle_timing.finalized,false);assert.equal(r.subtitle_timing.alignment_status,'APPROXIMATE_NOT_FINAL');assert(r.narration_segments.every(s=>s.alignment_precision==='APPROXIMATE_PROPORTIONAL'));assert.equal(r.subtitle_timing.segments[0].source_start,0.05)});
test('VT06 hard profile conflict stays explicit and never speeds up audio',()=>{const f=fixture();f.pkg=reseal({...f.pkg,target_platform_profile:{id:'limited',max_seconds:8}});f.plan=reseal({...f.plan,production_package_hash:f.pkg.content_hash});f.voice=reseal({...f.voice,plan_hash:f.plan.content_hash,production_package_hash:f.pkg.content_hash});f.approval=approveVoice(f);const r=revision(f);assert.equal(r.timing.platform_conflict.code,'PLATFORM_DURATION_LIMIT');assert.equal(r.timing.platform_conflict.actual_seconds,8.25);assert.equal(r.timing.trim.playback_rate,1)});
test('VT07 manifest resolves voice independently from rights and invalidates old visual timing readiness',()=>{const f=fixture(),r=revision(f),base=makeManifest({id:'m',plan:f.plan,assets:[f.voice],attempts:[],created_at:now}),m=applyProductionTiming(base,r,f.approval);assert(!m.unresolved.includes('VOICE'));assert(m.unresolved.includes('VOICE_RIGHTS:VOICE'));assert.equal(m.mapping.length,11);assert(m.mapping.every(b=>b.ready===false&&b.timing_status==='RETIME_REVIEW_REQUIRED'));assert.equal(m.voice_approval_id,f.approval.approval_id);assert.equal(m.effective_production_package_id,r.production_package_id);assert.equal(m.status,'ASSETS_PARTIAL');assert.equal(m.renderer_ready,false);assert.equal(m.publication_hold,true);assert.equal(m.release_allowed,false)});
test('VT08 approval binds exact asset bytes profile script package request and human decision',()=>{const f=fixture(),a=f.approval;assert.equal(a.voice_asset_hash,f.voice.content_hash);assert.equal(a.audio_hash,f.voice.qa.file_sha256);assert.equal(a.voice_profile_hash,'profile-hash');assert.equal(a.script_hash,f.script.output_hash);assert.equal(a.production_package_hash,f.pkg.content_hash);assert.equal(a.provider_request_id,'synthetic');assert.equal(a.decision,'APPROVED_FOR_PRODUCTION');for(const change of [{actor:'agent'},{decisions:{...voiceDecisions,pacing:'REJECTED'}},{source:{}}])assert.throws(()=>approveVoice({...f,...change}),/EXPLICIT_HUMAN_VOICE_APPROVAL_REQUIRED/)});
test('VT09 invalid trim altered script foreign voice and mismatched approval fail closed',()=>{const f=fixture();assert.throws(()=>revision({...f,voice:reseal({...f.voice,business_id:'other'})}),/VOICE_APPROVAL_MISMATCH/);assert.throws(()=>revision({...f,script:{...f.script,voiceover_text:'changed'}}),/SCRIPT_HASH_MISMATCH/);assert.throws(()=>approveVoice({...f,voice:reseal({...f.voice,business_id:'other'})}),/ASSET_TENANT_MISMATCH/);const v=reseal({...f.voice,qa:{...f.voice.qa,leading_silence_seconds:100}}),approval=approveVoice({...f,voice:v});assert.throws(()=>revision({...f,voice:v,approval}),/TIMING_TRIM_INVALID/)});

const base=process.env.TEST_DATABASE_URL,url=new URL(base),name='abo_test_'+randomUUID().replaceAll('-','');let admin,db;
before(async()=>{admin=new pg.Pool({connectionString:base});await admin.query('CREATE DATABASE '+name);url.pathname='/'+name;db=new PostgresStore(url.href);await migrate(db.pool)});after(async()=>{await db?.close();await admin.query('DROP DATABASE '+name);await admin.end()});
async function persisted(){const f=await scriptFixture(db),r=await f.service.run(f.command);await new HumanProductionApproval(f.repository).record({business_id:f.b,content_job_id:f.j.id,script_id:r.scripts[0].script_id,package_id:r.packages[0].production_package_id,decisions:{script_creative_quality:'APPROVED',script_factual_safety:'APPROVED',production_package:'APPROVED_FOR_NEXT_PRODUCTION_STAGE'}});const repo=new AssetRepository(f.repository),plan=await repo.plan(f.b,f.j.id),candidate=await repo.voiceProfiles.candidate(f.b,{provider:'synthetic',model:'local',provider_voice_reference:'synthetic',voice_kind:'CATALOGUE',language:'en'}),profile=await repo.voiceProfiles.decision(f.b,candidate.voice_profile_id,{expected_hash:candidate.content_hash,decision:'APPROVED',actor:{type:'human',id:'synthetic-human'},reference:'synthetic'}),voice=asset(plan,profile);await repo.artifact(plan,voice);const old=await repo.manifest(plan),command={plan,voice_asset_id:voice.asset_id,actor:'human',decisions:voiceDecisions,source};return {f,repo,plan,voice,old,command,service:new VoiceTimingService(repo)}}
test('VT10 PostgreSQL atomically persists approval package timing and new manifest with zero provider attempts',async()=>{const x=await persisted(),before=await db.getJob(x.f.j.id,x.f.b),r=await x.service.record(x.command),after=await db.getJob(x.f.j.id,x.f.b);assert.equal(r.reused,false);assert.equal(after.productionPackages.length,before.productionPackages.length+1);assert.equal(after.assetProduction.voiceApprovals.length,1);assert.equal(after.assetProduction.attempts.length,0);assert.equal(after.assetProduction.manifests.length,2);assert.equal(after.assetProduction.manifests[0].content_hash,x.old.content_hash);assert.deepEqual(after.assetProduction.artifacts,before.assetProduction.artifacts);assert.deepEqual(after.scripts,before.scripts);assert.deepEqual(after.stateHistory,before.stateHistory);assert.equal(after.job.current_state,'ASSETS_PENDING');assert.equal(after.assetProduction.manifests[1].effective_production_package_id,r.package.production_package_id)});
test('VT11 duplicate and concurrent human commands reuse the same immutable result',async()=>{const x=await persisted(),[a,b]=await Promise.all([x.service.record(x.command),x.service.record(x.command)]);assert.equal(a.approval.approval_id,b.approval.approval_id);assert.equal(a.package.production_package_id,b.package.production_package_id);assert.equal(a.manifest.manifest_id,b.manifest.manifest_id);assert.equal((await x.repo.records(x.plan)).manifests.length,2);await assert.rejects(x.service.record({...x.command,source:{reference:'changed',sha256:hash('changed')}}),/VOICE_APPROVAL_IDENTITY_CONFLICT/)});
test('VT12 restart and future manifest snapshots retain the authoritative timing revision',async()=>{const x=await persisted(),r=await x.service.record(x.command),fresh=new PostgresStore(url.href);try{const repo=new AssetRepository(new ScriptRepository(fresh)),m=await repo.manifest(x.plan);assert.equal(m.version,3);assert.equal(m.effective_production_package_hash,r.package.content_hash);assert.equal(m.production_timing.effective_narration_duration,r.package.target_duration);assert(m.unresolved.includes('SUBTITLE_TIMING'));assert.equal(m.status,'ASSETS_PARTIAL')}finally{await fresh.close()}});
test('VT13 immutable database history rejects overwrites and deletion of voice approval and timing package',async()=>{const x=await persisted(),r=await x.service.record(x.command);await assert.rejects(db.pool.query('DELETE FROM production_packages WHERE id=$1',[r.package.production_package_id]),e=>e.code==='23514');await assert.rejects(db.pool.query("UPDATE evidence_records SET payload='{}' WHERE business_id=$1 AND job_id=$2 AND type='asset_human_voice_approval'",[x.f.b,x.f.j.id]),e=>e.code==='23514');assert.equal((await x.repo.records(x.plan)).voiceApprovals[0].content_hash,r.approval.content_hash)});
test('VT14 foreign asset and failed transaction never leave a partial approval',async()=>{const x=await persisted();await assert.rejects(x.service.record({...x.command,voice_asset_id:'foreign'}),/VOICE_ASSET_NOT_FOUND/);const original=db.transaction.bind(db);db.transaction=fn=>original(async c=>{const originalQuery=c.query.bind(c);c.query=async(...args)=>{if(typeof args[0]==='string'&&args[0].startsWith('INSERT INTO production_packages'))throw Error('SYNTHETIC_STORAGE_FAILURE');return originalQuery(...args)};try{return await fn(c)}finally{c.query=originalQuery}});try{await assert.rejects(x.service.record(x.command),/SYNTHETIC_STORAGE_FAILURE/)}finally{db.transaction=original}const d=await x.repo.records(x.plan);assert.equal(d.voiceApprovals.length,0);assert.equal(d.timingRevisions.length,0);assert.equal(d.manifests.length,1)});
