import {wavQA,pngQA} from './asset-qa.js';
import {hash,assertSafe} from './research.js';
export const assetTypes=['VOICE','IMAGE','VIDEO','SVG','DATA_VISUAL','SOURCE_MEDIA','MUSIC','SFX','NATIVE_SCENE_SPEC'];
export const rightsStatuses=['UNKNOWN','REVIEW_REQUIRED','CLEARED','RESTRICTED','NOT_ALLOWED'];
export const need=(v,e)=>{if(!v)throw Error(e)};
export function seal(body){assertSafe(body);return {...body,content_hash:hash(body)}}
export function verify(x){const {content_hash,...body}=x;need(hash(body)===content_hash,'ASSET_HASH_MISMATCH');assertSafe(x);return x}
export function rights(status='UNKNOWN',evidence=null){need(rightsStatuses.includes(status),'INVALID_RIGHTS');if(status==='CLEARED')need(evidence?.authority&&evidence?.reference&&evidence?.basis,'RIGHTS_EVIDENCE_REQUIRED');return {status,evidence}}
export function routeBeat(beat,capabilities=[]){
 if(beat.visual_classification==='OBSERVED')return {resolution_type:'SOURCE_ASSET',provider_class:'SourceMediaProvider',expected_type:'SOURCE_MEDIA',reason:'Observed imagery requires authenticated source and rights',estimated_calls:1,estimated_cost:null};
 const native=['CONTROLLED_DIAGRAM','ORIGINAL_DATA_VISUALIZATION','MOTION_GRAPHICS','REMOTION_NATIVE'].includes(beat.visual_type);
 if(native||['DATA_DERIVED','SCIENTIFIC_VISUALIZATION'].includes(beat.visual_classification))return {resolution_type:'NATIVE_SCENE',provider_class:null,expected_type:'NATIVE_SCENE_SPEC',reason:'Controlled native composition preserves factual constraints and renderer control',estimated_calls:0,estimated_cost:null};
 if(beat.visual_classification==='OBSERVED'||beat.visual_type==='OFFICIAL_SOURCE_MEDIA')return {resolution_type:'SOURCE_ASSET',provider_class:'SourceMediaProvider',expected_type:'SOURCE_MEDIA',reason:'Authenticated source and explicit reuse rights required',estimated_calls:1,estimated_cost:null};
 if(beat.visual_type==='STOCK_OR_LICENSED_MEDIA')return {resolution_type:'LICENSED_MEDIA',provider_class:'SourceMediaProvider',expected_type:'SOURCE_MEDIA',reason:'License evidence required',estimated_calls:1,estimated_cost:null};
 need(beat.visual_classification==='ILLUSTRATIVE','UNSAFE_GENERATION');
 if(beat.generation_eligibility!=='ELIGIBLE_AFTER_REVIEW')return {resolution_type:'NATIVE_SCENE',provider_class:null,expected_type:'NATIVE_SCENE_SPEC',reason:'Generation not eligible; original illustrative native composition',estimated_calls:0,estimated_cost:null};
 const video=['TEXT_TO_VIDEO','IMAGE_TO_VIDEO'].includes(beat.visual_type),type=beat.visual_type==='IMAGE_TO_VIDEO'?'IMAGE_TO_VIDEO':video?'GENERATED_VIDEO':'GENERATED_STILL';
 return {resolution_type:type,provider_class:video?'VideoGenerationProvider':'ImageGenerationProvider',expected_type:video?'VIDEO':'IMAGE',reason:'Illustrative generation subject to rights, human plan review and configured capabilities',estimated_calls:1,estimated_cost:null};
}
export function chooseProvider(route,registry,policy){
 const candidates=registry.filter(p=>p.capabilities?.includes(route.provider_class)&&p.available===true&&policy.allowed_providers.includes(p.id)&&(!policy.aspect_ratio||p.aspect_ratios?.includes(policy.aspect_ratio))&&p.quality>=policy.min_quality&&(!policy.max_duration||p.max_duration>=policy.max_duration)&&(policy.max_cost==null||(Number.isFinite(p.estimated_cost)&&p.estimated_cost<=policy.max_cost)));
 candidates.sort((a,b)=>b.quality-a.quality||a.id.localeCompare(b.id));need(candidates.length,'PROVIDER_NOT_AVAILABLE');return candidates[0];
}
export function makeAssetPlan({id,approval,script,pkg,blocked_claim_ids=[],created_at}){
 need(approval.selected_script_id===script.script_id&&approval.script_hash===script.output_hash&&approval.selected_package_id===pkg.production_package_id&&approval.package_hash===pkg.content_hash,'STALE_PRODUCTION_PACKAGE');
 need(approval.publication_hold===true&&approval.release_allowed===false&&pkg.publication_hold===true&&!pkg.release_allowed,'UNSAFE_RELEASE');
 const scope={business_id:pkg.business_id,content_job_id:pkg.content_job_id,script_id:script.script_id,script_hash:script.output_hash,script_version:script.script_version??1,production_package_id:pkg.production_package_id,production_package_hash:pkg.content_hash,approval_id:approval.approval_id};
 const requirements=pkg.timeline_segments.map(b=>{need(!b.claim_refs.some(c=>blocked_claim_ids.includes(c)),'BLOCKED_CLAIM_USE');return {requirement_id:b.asset_requirement.requirement_id,visual_beat_id:b.visual_beat_id??b.segment_id,...routeBeat(b),classification:b.visual_classification??b.visual_intent.classification,claim_refs:b.claim_refs,evidence_references:b.asset_requirement.evidence_references,brief:b.concrete_visual_brief??b.visual_intent.instruction,motion_intent:b.motion_intent??b.motion_requirement,duration:b.duration_target,aspect_ratio:pkg.target_platform_profile.aspect_ratio,source_requirement:b.asset_requirement.source_requirement,rights_requirement:b.asset_requirement.rights_requirement,disclosure:b.asset_requirement.disclosure_requirement??'Preserve classification disclosure',generation_eligibility:b.generation_eligibility??'NOT_ELIGIBLE',provider:null}});
 need(requirements.length&&new Set(requirements.map(r=>r.visual_beat_id)).size===requirements.length,'INVALID_BEAT_MAP');
 return seal({plan_id:id,version:1,...scope,policy_snapshot_refs:pkg.policy_snapshot_refs,requirements,voice:{requirement_id:id+':voice',text:script.voiceover_text,text_hash:hash(script.voiceover_text),language:script.language,expected_duration:script.estimated_duration,audio_plan:pkg.audio_plan},music:{required:!!pkg.audio_plan.music_intent,status:'UNRESOLVED',intent:pkg.audio_plan.music_intent},sfx:{required:!!pkg.audio_plan.sfx_requirements,status:'UNRESOLVED',cues:pkg.audio_plan.sfx_cues??[]},subtitles:{required:true,status:'TIMING_PENDING',text_hash:hash(script.voiceover_text),strategy:pkg.subtitle_strategy},publication_hold:true,release_allowed:false,created_at});
}
export function nativeScene(plan,req,layers){
 verify(plan);need(req.resolution_type==='NATIVE_SCENE'&&plan.requirements.some(r=>hash(r)===hash(req)),'INVALID_NATIVE_ROUTE');need(Array.isArray(layers)&&layers.length,'SCENE_LAYERS_REQUIRED');
 for(const l of layers){need(['text','symbol','group','connector','boundary','signal','detector','material'].includes(l.kind)&&typeof l.label==='string'&&Number.isFinite(l.x)&&Number.isFinite(l.y)&&l.x>=0&&l.x<=1&&l.y>=0&&l.y<=1,'INVALID_SCENE_LAYER')}
 return {schema:'native-scene/1',aspect_ratio:req.aspect_ratio,duration:req.duration,classification:req.classification,disclosure:req.disclosure,brief:req.brief,motion:req.motion_intent,layers,external_media:false,renderer_adaptation_required:true};
}
export function validateAsset(plan,asset){
 verify(plan);verify(asset);need(asset.business_id===plan.business_id&&asset.content_job_id===plan.content_job_id,'ASSET_TENANT_MISMATCH');need(asset.plan_hash===plan.content_hash&&asset.production_package_hash===plan.production_package_hash,'STALE_PRODUCTION_PACKAGE');need(assetTypes.includes(asset.type),'INVALID_ASSET_TYPE');rights(asset.rights.status,asset.rights.evidence);need(asset.provenance?.origin&&asset.provenance?.created_at&&asset.data_hash===hash(asset.data),'ASSET_DATA_INVALID');
 if(asset.type==='VOICE'){need(asset.script_hash===plan.script_hash&&asset.text_hash===plan.voice.text_hash&&asset.qa.status==='PASS'&&asset.data.format==='wav','VOICE_NOT_VALIDATED');const qa=wavQA(Buffer.from(asset.data.bytes_base64,'base64'),plan.voice.expected_duration);need(qa.file_sha256===asset.qa.file_sha256&&qa.duration===asset.qa.duration,'VOICE_QA_MISMATCH')}
 else {need(asset.beat_ids?.length,'MISSING_BEAT');for(const id of asset.beat_ids){const r=plan.requirements.find(r=>r.visual_beat_id===id);need(r,'MISSING_BEAT');need(asset.classification===r.classification&&asset.disclosure===r.disclosure&&hash(asset.claim_refs)===hash(r.claim_refs)&&asset.aspect_ratio===r.aspect_ratio,'ASSET_SCOPE_MISMATCH');if(asset.type==='NATIVE_SCENE_SPEC'){nativeScene(plan,r,asset.data.layers);need(asset.data.aspect_ratio===r.aspect_ratio&&asset.data.classification===r.classification&&asset.data.disclosure===r.disclosure&&asset.data.duration===r.duration,'NATIVE_SPEC_MISMATCH');}else {need(asset.qa.status==='PASS'&&asset.data.bytes_base64?.length,'VISUAL_NOT_VALIDATED');if(asset.data.format==='png')need(pngQA(asset.data).aspect_ratio===r.aspect_ratio,'VISUAL_DECODE_FAILED');}if(asset.provenance.generated)need(r.classification==='ILLUSTRATIVE','GENERATED_NOT_OBSERVED')}}return asset;
}
export function makeManifest({id,plan,assets,attempts,created_at,version=1}){
 verify(plan);for(const a of assets)validateAsset(plan,a);const admissible=assets.filter(a=>a.qa.status==='PASS'&&a.rights.status==='CLEARED'),voice=admissible.find(a=>a.type==='VOICE');
 const mapping=plan.requirements.map(r=>({visual_beat_id:r.visual_beat_id,resolution_type:r.resolution_type,asset_id:assets.find(a=>a.beat_ids?.includes(r.visual_beat_id))?.asset_id??null,ready:admissible.some(a=>a.beat_ids?.includes(r.visual_beat_id)),rights_status:assets.find(a=>a.beat_ids?.includes(r.visual_beat_id))?.rights.status??'UNKNOWN',classification:r.classification,disclosure:r.disclosure}));
 const missing=[...mapping.filter(m=>!m.ready).map(m=>m.visual_beat_id),...(!voice?['VOICE']:[]),...(plan.music.required?['MUSIC']:[]),...(plan.sfx.required?['SFX']:[]),...(plan.subtitles.required?['SUBTITLE_TIMING']:[])];
 return seal({manifest_id:id,version,business_id:plan.business_id,content_job_id:plan.content_job_id,plan_id:plan.plan_id,plan_hash:plan.content_hash,script_id:plan.script_id,script_hash:plan.script_hash,production_package_id:plan.production_package_id,production_package_hash:plan.production_package_hash,voice_asset_id:voice?.asset_id??null,mapping,music:plan.music,sfx:plan.sfx,subtitles:plan.subtitles,assets:assets.map(a=>({asset_id:a.asset_id,hash:a.content_hash,rights:a.rights,disclosure:a.disclosure??null})),provider_attempts:attempts,unresolved:missing,status:missing.length?'ASSETS_PARTIAL':'ASSETS_READY',renderer_ready:missing.length===0,human_review_required:true,publication_hold:true,release_allowed:false,created_at});
}
