import {randomUUID,createHash} from 'node:crypto';import {hash,assertSafe} from '../domain/research.js';import {seal,verify,need,nativeScene,validateAsset,rights,chooseProvider} from '../domain/assets.js';import {putAssetEvidence} from '../assets-postgres.js';import {voiceInput,verifyProvider,wavQA} from '../providers/asset-boundaries.js';
export class AssetService{
 constructor(repository){this.repository=repository}
 async routeAndProduce({plan,requirement,registry,policy,profile,credentialPresent,authorization,decoder}){if(requirement==='VOICE')voiceInput(plan,profile,credentialPresent);const req=plan.requirements.find(r=>r.requirement_id===requirement);const capability=requirement==='VOICE'?'VoiceGenerationProvider':req?.provider_class;need(capability,'NATIVE_PROVIDER_NOT_REQUIRED');const descriptors=registry.map(p=>p.describe());const chosen=chooseProvider({provider_class:capability},descriptors,{...policy,allowed_providers:requirement==='VOICE'?[profile?.provider]:policy.allowed_providers});const provider=registry.find(p=>p.describe().id===chosen.id);return this.produce({plan,requirement,provider,profile,credentialPresent,authorization,decoder})}

 async native(plan,req,layers){const data=nativeScene(plan,req,layers),id=hash({plan:plan.content_hash,beat:req.visual_beat_id,data}),record=seal({asset_id:id,version:1,business_id:plan.business_id,content_job_id:plan.content_job_id,plan_hash:plan.content_hash,production_package_hash:plan.production_package_hash,script_hash:plan.script_hash,script_id:plan.script_id,script_version:plan.script_version,type:'NATIVE_SCENE_SPEC',beat_ids:[req.visual_beat_id],claim_refs:req.claim_refs,classification:req.classification,disclosure:req.disclosure,aspect_ratio:req.aspect_ratio,data,data_hash:hash(data),rights:rights('REVIEW_REQUIRED'),provenance:{origin:'original-native-composition',provider:null,model:null,generated:false,created_at:plan.created_at,policy_snapshot_refs:plan.policy_snapshot_refs,evidence_references:req.evidence_references,prompt_spec_hash:hash(data)},qa:{status:'PASS',checks:['schema','dimensions','scope','disclosure','provenance'],human_visual_review_required:true},status:'TECHNICALLY_VALIDATED',created_at:plan.created_at});await this.repository.artifact(plan,record);return record}
 async blocked(plan,requirement,reason){const payload=seal({outcome_id:randomUUID(),plan_hash:plan.content_hash,requirement_id:requirement,status:'BLOCKED',reason,external_calls:0,created_at:new Date().toISOString()});return this.repository.save(plan,'asset_outcome',payload.outcome_id,payload)}
 async produce({plan,requirement,provider,profile=null,credentialPresent=false,authorization,decoder=null}){
 verify(plan);const voice=requirement==='VOICE',req=voice?null:plan.requirements.find(r=>r.requirement_id===requirement);need(voice||req,'MISSING_BEAT');
 const request=voice?voiceInput(plan,profile,credentialPresent):{requirement:req};
 const capability=voice?'VoiceGenerationProvider':req.provider_class;verifyProvider(provider,capability);const descriptor=provider.describe();assertSafe(descriptor);if(voice)need(descriptor.id===profile.provider,'VOICE_PROFILE_PROVIDER_MISMATCH');
 need(authorization?.max_calls===1&&authorization.plan_hash===plan.content_hash&&authorization.requirement_id===requirement,'ASSET_CALL_NOT_AUTHORIZED');
 if(!voice&&['GENERATED_STILL','GENERATED_VIDEO','IMAGE_TO_VIDEO'].includes(req.resolution_type))need(req.generation_eligibility==='ELIGIBLE_AFTER_REVIEW'&&authorization.human_visual_approval===true,'VISUAL_REVIEW_REQUIRED');
 const attempt=seal({attempt_id:randomUUID(),business_id:plan.business_id,content_job_id:plan.content_job_id,plan_hash:plan.content_hash,requirement_id:requirement,request_hash:hash(request),provider:descriptor.id,model:descriptor.model,workflow_version:'assets/1.0',call_permit:authorization,created_at:new Date().toISOString()});
 await this.repository.transact(plan,async c=>{const old=(await c.query("SELECT id FROM evidence_records WHERE business_id=$1 AND job_id=$2 AND type='asset_attempt' AND payload->>'plan_hash'=$3 AND payload->>'requirement_id'=$4",[plan.business_id,plan.content_job_id,plan.content_hash,requirement])).rows;need(!old.length,'ASSET_ATTEMPT_ALREADY_EXISTS');await putAssetEvidence(c,plan.business_id,plan.content_job_id,'asset_attempt',attempt.attempt_id,attempt)});
 let calls=0;try{calls=descriptor.external===true?1:0;const raw=await provider.request(request),data=voice?{format:raw.format,bytes_base64:Buffer.from(raw.bytes).toString('base64')}:{format:raw.data?.format??null,bytes_base64:raw.data?.bytes_base64??null};
 const response=seal({attempt_id:attempt.attempt_id,plan_hash:plan.content_hash,requirement_id:requirement,data,transcript:voice?(raw.transcript??null):null,source_reference:raw.source_reference??null,metadata:{request_id:raw.request_id??null,provider:descriptor.id,model:descriptor.model,profile:voice?profile:null,usage:raw.usage??null,cost:raw.cost??null,cost_status:raw.cost==null?'UNKNOWN':'REPORTED',duration_ms:raw.duration_ms??null,external_calls:calls},received_at:new Date().toISOString()});
 await this.repository.save(plan,'asset_response',attempt.attempt_id,response);const readback=(await this.repository.store.pool.query("SELECT payload,content_hash FROM evidence_records WHERE business_id=$1 AND job_id=$2 AND type='asset_response' AND reference=$3",[plan.business_id,plan.content_job_id,attempt.attempt_id])).rows[0];need(readback&&hash(readback.payload)===readback.content_hash,'RESPONSE_PERSISTENCE_FAILED');
 const asset=this.reprocess(plan,response,{decoder,rightsEvidence:authorization.rights_evidence??null});await this.repository.artifact(plan,asset);await this.outcome(plan,attempt,'SUCCEEDED',null,calls);return asset;
 }catch(e){const code=/^[A-Z_]+$/.test(e.message)?e.message:'ASSET_PROVIDER_FAILED';await this.outcome(plan,attempt,'REVIEW_REQUIRED',code,calls);throw Error(code)}
 }
 async outcome(plan,attempt,status,error,calls){const p=seal({outcome_id:randomUUID(),attempt_id:attempt.attempt_id,plan_hash:plan.content_hash,status,error,external_calls:calls,created_at:new Date().toISOString()});return this.repository.save(plan,'asset_outcome',attempt.attempt_id,p)}
 reprocess(plan,response,{decoder=null,rightsEvidence=null}={}){
 verify(plan);verify(response);need(response.plan_hash===plan.content_hash,'STALE_PRODUCTION_PACKAGE');const voice=response.requirement_id==='VOICE',req=voice?null:plan.requirements.find(r=>r.requirement_id===response.requirement_id);need(voice||req,'MISSING_BEAT');const data=response.data;let qa;
 if(voice){qa=wavQA(Buffer.from(data.bytes_base64,'base64'),plan.voice.expected_duration);if(response.transcript!=null){need(response.transcript===plan.voice.text,'VOICE_TRANSCRIPT_MISMATCH');qa.transcript_alignment='EXACT_TEXT_MATCH'}}
 else {need(typeof decoder==='function','VISUAL_DECODER_REQUIRED');qa=decoder(data);need(qa.status==='PASS'&&qa.aspect_ratio===req.aspect_ratio,'VISUAL_DECODE_FAILED')}
 const asset=seal({asset_id:hash({response:response.content_hash,processor:'asset-normalizer/1.0'}),version:1,business_id:plan.business_id,content_job_id:plan.content_job_id,plan_hash:plan.content_hash,production_package_hash:plan.production_package_hash,script_hash:plan.script_hash,script_id:plan.script_id,script_version:plan.script_version,language:voice?plan.voice.language:null,generation_settings:voice?(response.metadata.profile?.settings??{}):null,text_hash:voice?plan.voice.text_hash:null,type:voice?'VOICE':req.expected_type,beat_ids:voice?[]:[req.visual_beat_id],claim_refs:req?.claim_refs??[],classification:req?.classification??null,disclosure:req?.disclosure??null,aspect_ratio:req?.aspect_ratio??null,data,data_hash:hash(data),rights:rights(rightsEvidence?'CLEARED':'REVIEW_REQUIRED',rightsEvidence),provenance:{origin:voice?'voice-generation':req.resolution_type,generated:!voice&&['GENERATED_STILL','GENERATED_VIDEO','IMAGE_TO_VIDEO'].includes(req.resolution_type),created_at:response.received_at,...response.metadata,source_reference:response.source_reference??null,rights_reference:rightsEvidence?.reference??null,response_hash:response.content_hash,attempt_id:response.attempt_id},qa,status:'TECHNICALLY_VALIDATED',created_at:response.received_at});return validateAsset(plan,asset);
 }
}
